{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanDidChallengeSolved"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}],"name":"appId"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Called when the challenge was solved."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humandelegate\/humandidchallengesolved(forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humandelegate\/humandidchallengesolved(forappid:)"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeSolved(forAppId:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"]]},"metadata":{"title":"humanDidChallengeSolved(forAppId:)","navigatorTitle":[{"text":"humanDidChallengeSolvedForAppId:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanDidChallengeSolved"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"HUMAN"}],"symbolKind":"method","externalID":"c:@M@HUMAN@objc(pl)HumanDelegate(im)humanDidChallengeSolvedForAppId:","role":"symbol","required":true},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidChallengeSolved(forAppId:)":{"title":"humanDidChallengeSolved(forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeSolved(forAppId:)","navigatorTitle":[{"text":"humanDidChallengeSolvedForAppId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when the challenge was solved."}],"url":"\/documentation\/human\/humandelegate\/humandidchallengesolved(forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanDidChallengeSolved"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","required":true},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"humanDidChallengeSolvedForAppId:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"humanDidChallengeSolvedForAppId:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"humanDidChallengeSolvedForAppId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appId"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title","value":"HumanDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","value":[{"text":"HumanDelegate","kind":"identifier"}]},{"op":"replace","value":"humanDidChallengeSolvedForAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeSolved(forAppId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeSolved(forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"humanDidChallengeSolvedForAppId:"}]}]}]}