{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRenderChallenge(forAppId:)","interfaceLanguage":"swift"},"abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"humanDidRenderChallenge","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"appId","content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/human\/humandelegate\/humandidrenderchallenge(forappid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humandelegate\/humandidrenderchallenge(forappid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"]]},"metadata":{"modules":[{"name":"HUMAN"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"humanDidRenderChallengeForAppId:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"humanDidRenderChallenge","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@HUMAN@objc(pl)HumanDelegate(im)humanDidRenderChallengeForAppId:","symbolKind":"method","title":"humanDidRenderChallenge(forAppId:)","required":true},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidRenderChallenge(forAppId:)":{"abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"url":"\/documentation\/human\/humandelegate\/humandidrenderchallenge(forappid:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"humanDidRenderChallenge","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRenderChallenge(forAppId:)","title":"humanDidRenderChallenge(forAppId:)","required":true,"role":"symbol","navigatorTitle":[{"text":"humanDidRenderChallengeForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"humanDidRenderChallengeForAppId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"humanDidRenderChallengeForAppId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"humanDidRenderChallengeForAppId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"humanDidRenderChallengeForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRenderChallenge(forAppId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRenderChallenge(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"humanDidRenderChallengeForAppId:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"HumanDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title"},{"value":[{"kind":"identifier","text":"HumanDelegate"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","op":"replace"}]}]}