{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humandelegate\/humandidrequestblocked(url:appid:)"]},{"paths":["\/documentation\/human\/humandelegate\/humandidrequestblocked(url:appid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRequestBlocked(url:appId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanDidRequestBlocked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}],"name":"appId"},{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request’s URL that was blocked. Will be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"},{"text":" is set to ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true,"type":"reference"},{"type":"text","text":" in the policy."}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"title":"humanDidRequestBlocked(url:appId:)","externalID":"c:@M@HUMAN@objc(pl)HumanDelegate(im)humanDidRequestBlockedWithUrl:appId:","navigatorTitle":[{"text":"humanDidRequestBlockedWithUrl:appId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanDidRequestBlocked"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"required":true,"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"HUMAN"}],"symbolKind":"method"},"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidRequestBlocked(url:appId:)":{"title":"humanDidRequestBlocked(url:appId:)","navigatorTitle":[{"kind":"identifier","text":"humanDidRequestBlockedWithUrl:appId:"}],"url":"\/documentation\/human\/humandelegate\/humandidrequestblocked(url:appid:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"humanDidRequestBlocked","kind":"identifier"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","required":true,"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRequestBlocked(url:appId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"HSAutomaticInterceptorType.none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"humanDidRequestBlockedWithUrl:appId:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"humanDidRequestBlockedWithUrl:appId:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"humanDidRequestBlockedWithUrl:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"text":"appId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appId"},{"text":";","kind":"text"}]}]}},{"value":"humanDidRequestBlockedWithUrl:appId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRequestBlocked(url:appId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"humanDidRequestBlockedWithUrl:appId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRequestBlocked(url:appId:)\/fragments"},{"value":"HumanDelegate","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments"},{"op":"replace","value":"HSAutomaticInterceptorType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace"}]}]}