{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidFailRenderChallenge(forAppId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanDidFailRenderChallenge"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}],"name":"appId"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"humanDidFailRenderChallenge(forAppId:)","externalID":"c:@M@HUMAN@objc(pl)HumanDelegate(im)humanDidFailRenderChallengeForAppId:","navigatorTitle":[{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanDidFailRenderChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"HUMAN"}]},"abstract":[{"type":"text","text":"Called when the challenge was failed to render."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humandelegate\/humandidfailrenderchallenge(forappid:)"]},{"paths":["\/documentation\/human\/humandelegate\/humandidfailrenderchallenge(forappid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidFailRenderChallenge(forAppId:)":{"url":"\/documentation\/human\/humandelegate\/humandidfailrenderchallenge(forappid:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanDidFailRenderChallenge"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidFailRenderChallenge(forAppId:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the challenge was failed to render."}],"title":"humanDidFailRenderChallenge(forAppId:)","navigatorTitle":[{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"humanDidFailRenderChallengeForAppId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"humanDidFailRenderChallengeForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidFailRenderChallenge(forAppId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidFailRenderChallenge(forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"humanDidFailRenderChallengeForAppId:"}]},{"value":"HumanDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","value":[{"text":"HumanDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}