{"sections":[],"variants":[{"paths":["\/documentation\/human\/humandelegate\/humanheaderswereupdated(headers:forappid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humandelegate\/humanheaderswereupdated(headers:forappid:)"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@HUMAN@objc(pl)HumanDelegate(im)humanHeadersWereUpdatedWithHeaders:forAppId:","symbolKind":"method","title":"humanHeadersWereUpdated(headers:forAppId:)","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"humanHeadersWereUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanHeadersWereUpdated(headers:forAppId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the "},{"code":"Human\/headersForURLRequest(forAppId:)","type":"codeVoice"},{"type":"text","text":" function for every URL request."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanHeadersWereUpdated"},{"kind":"text","text":"("},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"headers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HTTP headers."}]}]},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID that related to the event."}]}]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanHeadersWereUpdated(headers:forAppId:)":{"navigatorTitle":[{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"abstract":[{"text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the ","type":"text"},{"code":"Human\/headersForURLRequest(forAppId:)","type":"codeVoice"},{"type":"text","text":" function for every URL request."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanHeadersWereUpdated(headers:forAppId:)","title":"humanHeadersWereUpdated(headers:forAppId:)","type":"topic","url":"\/documentation\/human\/humandelegate\/humanheaderswereupdated(headers:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"humanHeadersWereUpdated","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"humanHeadersWereUpdatedWithHeaders:forAppId:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"humanHeadersWereUpdatedWithHeaders:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"headers"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanHeadersWereUpdated(headers:forAppId:)\/title","value":"humanHeadersWereUpdatedWithHeaders:forAppId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanHeadersWereUpdated(headers:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"op":"replace"},{"value":"HumanDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","value":[{"kind":"identifier","text":"HumanDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}