{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@HUMAN@E@HumanSecurityErrorType","extendedModule":"Swift","role":"symbol","roleHeading":"Operator","symbolKind":"op","modules":[{"relatedModules":["Swift"],"name":"HUMAN"}],"title":"!=(_:_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/Equatable-Implementations"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humansecurityerrortype\/!=(_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/!=(_:_:)"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"title":"HumanSecurityErrorType","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/human\/humansecurityerrortype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/!=(_:_:)":{"url":"\/documentation\/human\/humansecurityerrortype\/!=(_:_:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/!=(_:_:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"!=(_:_:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/Equatable-Implementations":{"abstract":[],"kind":"article","title":"Equatable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/human\/humansecurityerrortype\/equatable-implementations","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/Equatable-Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"patch":[{"value":"HumanSecurityErrorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle","op":"replace","value":[{"text":"HumanSecurityErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}