{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/humansecurityerrortype\/automaticinterceptorisnotconfiguredcorrectly"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurityerrortype\/automaticinterceptorisnotconfiguredcorrectly"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The Automatic Interceptor is not configured correctly."}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorIsNotConfiguredCorrectly"}],"externalID":"c:@M@HUMAN@E@HumanSecurityErrorType@HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","symbolKind":"case","modules":[{"name":"HUMAN"}],"roleHeading":"Case","role":"symbol","title":"HumanSecurityErrorType.automaticInterceptorIsNotConfiguredCorrectly","navigatorTitle":[{"text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/automaticInterceptorIsNotConfiguredCorrectly","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"role":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}],"url":"\/documentation\/human\/humansecurityerrortype","abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}],"kind":"symbol","type":"topic","title":"HumanSecurityErrorType","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/automaticInterceptorIsNotConfiguredCorrectly":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorIsNotConfiguredCorrectly"}],"navigatorTitle":[{"text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}],"abstract":[{"text":"The Automatic Interceptor is not configured correctly.","type":"text"}],"url":"\/documentation\/human\/humansecurityerrortype\/automaticinterceptorisnotconfiguredcorrectly","role":"symbol","title":"HumanSecurityErrorType.automaticInterceptorIsNotConfiguredCorrectly","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/automaticInterceptorIsNotConfiguredCorrectly"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title","value":"HumanSecurityErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1automaticInterceptorIsNotConfiguredCorrectly\/title","op":"replace","value":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly"},{"op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1automaticInterceptorIsNotConfiguredCorrectly\/fragments"}]}]}