{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/human\/humansecurityerrortype\/httpbodyinputstreamreadfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurityerrortype\/httpbodyinputstreamreadfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/httpBodyInputStreamReadFailed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"]]},"abstract":[{"text":"Failed to read body from input stream of the request.","type":"text"}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed"}],"modules":[{"name":"HUMAN"}],"role":"symbol","title":"HumanSecurityErrorType.httpBodyInputStreamReadFailed","externalID":"c:@M@HUMAN@E@HumanSecurityErrorType@HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"role":"symbol","title":"HumanSecurityErrorType","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","kind":"symbol","url":"\/documentation\/human\/humansecurityerrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/httpBodyInputStreamReadFailed":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/httpBodyInputStreamReadFailed","title":"HumanSecurityErrorType.httpBodyInputStreamReadFailed","url":"\/documentation\/human\/humansecurityerrortype\/httpbodyinputstreamreadfailed","abstract":[{"text":"Failed to read body from input stream of the request.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HumanSecurityErrorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title"},{"value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments"},{"value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle"},{"value":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1httpBodyInputStreamReadFailed\/title"},{"value":[{"text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1httpBodyInputStreamReadFailed\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}