{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}]}]}],"metadata":{"roleHeading":"Case","title":"HumanSecurityErrorType.invalidAppId","externalID":"c:@M@HUMAN@E@HumanSecurityErrorType@HumanSecurityErrorTypeInvalidAppId","role":"symbol","symbolKind":"case","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"HumanSecurityErrorTypeInvalidAppId","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/invalidAppId","interfaceLanguage":"swift"},"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},{"text":" functions were called with invalid AppID.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"]]},"variants":[{"paths":["\/documentation\/human\/humansecurityerrortype\/invalidappid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurityerrortype\/invalidappid"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/invalidAppId":{"url":"\/documentation\/human\/humansecurityerrortype\/invalidappid","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" or ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},{"text":" functions were called with invalid AppID.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeInvalidAppId"}],"kind":"symbol","title":"HumanSecurityErrorType.invalidAppId","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/invalidAppId"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}],"abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}],"url":"\/documentation\/human\/humansecurityerrortype","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","type":"topic","title":"HumanSecurityErrorType","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"kind":"symbol","title":"start(appIds:policy:)","role":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"type":"topic","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HumanSecurityErrorTypeInvalidAppId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeInvalidAppId"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HumanSecurityErrorTypeInvalidAppId","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1invalidAppId\/title","op":"replace","value":"HumanSecurityErrorTypeInvalidAppId"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1invalidAppId\/fragments","op":"replace","value":[{"text":"HumanSecurityErrorTypeInvalidAppId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title","op":"replace","value":"HumanSecurityErrorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","op":"replace","value":"startWithAppId:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","op":"replace","value":"startWithAppIds:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}