{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The SDK failed to generate token. Make sure the AppID is set correctly."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenWasNotGenerated","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"HUMAN"}],"symbolKind":"case","navigatorTitle":[{"text":"HumanSecurityErrorTypeTokenWasNotGenerated","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HumanSecurityErrorType@HumanSecurityErrorTypeTokenWasNotGenerated","title":"HumanSecurityErrorType.tokenWasNotGenerated"},"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/tokenWasNotGenerated","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/human\/humansecurityerrortype\/tokenwasnotgenerated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurityerrortype\/tokenwasnotgenerated"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenWasNotGenerated"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}],"abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}],"url":"\/documentation\/human\/humansecurityerrortype","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","type":"topic","title":"HumanSecurityErrorType","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/tokenWasNotGenerated":{"navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeTokenWasNotGenerated"}],"abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/tokenWasNotGenerated","title":"HumanSecurityErrorType.tokenWasNotGenerated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenWasNotGenerated"}],"type":"topic","role":"symbol","url":"\/documentation\/human\/humansecurityerrortype\/tokenwasnotgenerated","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"HumanSecurityErrorTypeTokenWasNotGenerated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeTokenWasNotGenerated"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"HumanSecurityErrorTypeTokenWasNotGenerated","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title","op":"replace","value":"HumanSecurityErrorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1tokenWasNotGenerated\/title","op":"replace","value":"HumanSecurityErrorTypeTokenWasNotGenerated"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1tokenWasNotGenerated\/fragments","op":"replace","value":[{"text":"HumanSecurityErrorTypeTokenWasNotGenerated","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}