{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humansecurity\/ad"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/ad"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AD","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAccountDefender","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAccountDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AD"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAccountDefender","kind":"typeIdentifier","text":"HSAccountDefender"}],"modules":[{"name":"HUMAN"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"AD"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cpy)AD","title":"AD","role":"symbol","symbolKind":"property"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/AD"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"HSAccountDefender","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","title":"HSAccountDefender","url":"\/documentation\/human\/hsaccountdefender","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAccountDefender","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/humansecurity","abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"title":"HumanSecurity"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/AD":{"type":"topic","abstract":[],"title":"AD","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AD","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAccountDefender","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAccountDefender"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/AD","navigatorTitle":[{"text":"AD","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/ad","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"AD"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AD","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAccountDefender","text":"HSAccountDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"AD","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title","op":"replace","value":"HSAccountDefender"},{"value":[{"kind":"identifier","text":"HSAccountDefender"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments"},{"value":[{"kind":"identifier","text":"HSAccountDefender"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle"},{"value":"HumanSecurity","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1AD\/title","op":"replace","value":"AD"},{"value":[{"text":"AD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1AD\/fragments"}]}]}