{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BD","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSBotDefender","text":"HSBotDefender","kind":"typeIdentifier"}],"roleHeading":"Type Property","role":"symbol","modules":[{"name":"HUMAN"}],"symbolKind":"property","title":"BD","navigatorTitle":[{"text":"BD","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cpy)BD"},"variants":[{"paths":["\/documentation\/human\/humansecurity\/bd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurity\/bd"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/BD","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BD","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSBotDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSBotDefender","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/BD":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/BD","kind":"symbol","abstract":[],"title":"BD","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BD","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSBotDefender","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSBotDefender","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"BD","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/bd"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"title":"HSBotDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefender"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefender"}],"url":"\/documentation\/human\/hsbotdefender","kind":"symbol","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"url":"\/documentation\/human\/humansecurity","title":"HumanSecurity","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"BD","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"BD","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSBotDefender","text":"HSBotDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"BD","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1BD\/title","value":"BD","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1BD\/fragments","value":[{"text":"BD","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","value":"HSBotDefender","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","value":"HumanSecurity","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}