{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleResponse"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HumanChallengeResult","text":"HumanChallengeResult"},{"text":") -> ())?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"handleResponse(response:data:forAppId:callback:)","modules":[{"name":"HUMAN"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)handleResponseWithResponse:data:forAppId:callback:","role":"symbol","roleHeading":"Type Method"},"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleResponse","kind":"identifier"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"HumanChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","preciseIdentifier":"c:@M@HUMAN@E@HumanChallengeResult","kind":"typeIdentifier"},{"kind":"text","text":") -> ())?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"parameters":[{"name":"response","content":[{"inlineContent":[{"type":"text","text":"The response that was received from the URL request."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data that was received from the URL request."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}],"type":"paragraph"}],"name":"appId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback that indicate the challenge’s result. The callback will be called once the user solved (or cancelled)  the challenge. You may use this to retry the URL request."}]}],"name":"callback"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the Human’s payload in the response was handled by the SDK. This function should be used only when the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none"},{"type":"text","text":" in the policy."}],"type":"paragraph"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"variants":[{"paths":["\/documentation\/human\/humansecurity\/handleresponse(response:data:forappid:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurity\/handleresponse(response:data:forappid:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/handleResponse(response:data:forAppId:callback:)","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"url":"\/documentation\/human\/humansecurity","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"role":"symbol","title":"HumanSecurity","kind":"symbol","type":"topic","abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult":{"url":"\/documentation\/human\/humanchallengeresult","type":"topic","abstract":[{"type":"text","text":"Challenge result."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HumanChallengeResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HumanChallengeResult"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","title":"HumanChallengeResult","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/handleResponse(response:data:forAppId:callback:)":{"title":"handleResponse(response:data:forAppId:callback:)","abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}],"type":"topic","role":"symbol","url":"\/documentation\/human\/humansecurity\/handleresponse(response:data:forappid:callback:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/handleResponse(response:data:forAppId:callback:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier","text":"URLResponse"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"text":"HumanChallengeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HumanChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"HSAutomaticInterceptorType.none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"handleResponseWithResponse:data:forAppId:callback:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleResponseWithResponse:"},{"kind":"text","text":"("},{"text":"NSURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"text":"forAppId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"HumanChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","preciseIdentifier":"c:@M@HUMAN@E@HumanChallengeResult"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"HumanSecurity","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"value":"HumanChallengeResult","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/fragments","value":[{"text":"HumanChallengeResult","kind":"identifier"}],"op":"replace"},{"value":"HSAutomaticInterceptorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1handleResponse(response:data:forAppId:callback:)\/title","value":"handleResponseWithResponse:data:forAppId:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1handleResponse(response:data:forAppId:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}]}]}]}