{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"headersForURLRequest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil) -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The AppID of your account. Ignore this param if you use only one AppID.","type":"text"}],"type":"paragraph"}],"name":"appId"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This function should be used only when the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","type":"reference"},{"type":"text","text":" is set to "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]}],"abstract":[{"type":"text","text":"Returns HTTP headers that should be added to the URL request."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/headersForURLRequest(forAppId:)"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"headersForURLRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)headersForURLRequestForAppId:","title":"headersForURLRequest(forAppId:)","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol"},"variants":[{"paths":["\/documentation\/human\/humansecurity\/headersforurlrequest(forappid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/headersforurlrequest(forappid:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"HSAutomaticInterceptorType.none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/headersForURLRequest(forAppId:)":{"type":"topic","abstract":[{"text":"Returns HTTP headers that should be added to the URL request.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/headersForURLRequest(forAppId:)","title":"headersForURLRequest(forAppId:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"headersForURLRequestForAppId:"}],"url":"\/documentation\/human\/humansecurity\/headersforurlrequest(forappid:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headersForURLRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"url":"\/documentation\/human\/humansecurity","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"role":"symbol","title":"HumanSecurity","kind":"symbol","type":"topic","abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"headersForURLRequestForAppId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"headersForURLRequestForAppId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1headersForURLRequest(forAppId:)\/title","value":"headersForURLRequestForAppId:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"headersForURLRequestForAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1headersForURLRequest(forAppId:)\/fragments"},{"value":"HumanSecurity","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"kind":"identifier","text":"HumanSecurity"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}