{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"sections":[],"metadata":{"modules":[{"name":"HUMAN"}],"title":"init","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/init","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/human\/humansecurity\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/init","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","type":"topic","title":"HumanSecurity","url":"\/documentation\/human\/humansecurity","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}],"abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"HumanSecurity","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle"}]}]}