{"variants":[{"paths":["\/documentation\/human\/humansecurity\/ischallengesolvederror(error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/ischallengesolvederror(error:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"HUMAN"}],"roleHeading":"Type Method","externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)isChallengeSolvedErrorWithError:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"}],"title":"isChallengeSolvedError(error:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/isChallengeSolvedError(error:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The error to check","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This kind error should returned when the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true},{"text":" is set to any value rather than ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","type":"reference","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"kind":"symbol","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the error is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","isActive":true},{"text":" error.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/challengeSolved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","kind":"symbol","abstract":[{"type":"text","text":"Challenge was solved by the user."}],"title":"HumanErrorCode.challengeSolved","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeChallengeSolved"}],"url":"\/documentation\/human\/humanerrorcode\/challengesolved","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"challengeSolved","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"HSAutomaticInterceptorType.none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"url":"\/documentation\/human\/humansecurity","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"role":"symbol","title":"HumanSecurity","kind":"symbol","type":"topic","abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/isChallengeSolvedError(error:)":{"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/isChallengeSolvedError(error:)","title":"isChallengeSolvedError(error:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the error is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","isActive":true},{"text":" error.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"}],"url":"\/documentation\/human\/humansecurity\/ischallengesolvederror(error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isChallengeSolvedErrorWithError:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType","op":"replace"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","op":"replace"},{"op":"replace","value":"HumanErrorCodeChallengeSolved","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeSolved\/title"},{"value":[{"text":"HumanErrorCodeChallengeSolved","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeSolved\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"op":"replace"},{"value":"HumanSecurity","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"kind":"identifier","text":"HumanSecurity"}]},{"value":"isChallengeSolvedErrorWithError:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1isChallengeSolvedError(error:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1isChallengeSolvedError(error:)\/fragments","op":"replace"}]}]}