{"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)setupWebViewWithWebView:navigationDelegate:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupWebView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationDelegate","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"kind":"text","text":"?)"}],"modules":[{"name":"HUMAN"}],"roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"title":"setupWebView(webView:navigationDelegate:)"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"abstract":[{"text":"Setup the web view to be synced with SDK. Do not set a ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":" to the web view after calling this function.","type":"text"},{"text":" ","type":"text"},{"text":"If you wish to set a web view client, call this function again with the new ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":". You should not call this method when the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupWebView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"navigationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"parameter webView The web view."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"parameter navigationDelegate an optional "},{"type":"codeVoice","code":"WKNavigationDelegate"},{"type":"text","text":". Ignore this param if you don’t need to set a delegate."}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","role":"symbol","title":"HumanSecurity","url":"\/documentation\/human\/humansecurity","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Hybrid_App_Integration":{"role":"article","type":"topic","kind":"article","url":"\/documentation\/human\/hybrid_app_integration","title":"Hybrid App Integration","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"title":"automaticSetup","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}],"type":"topic","abstract":[{"type":"text","text":"When this property is "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the SDK detects all "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true},{"text":" function. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticSetup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Setup the web view to be synced with SDK. Do not set a "},{"code":"WKNavigationDelegate","type":"codeVoice"},{"type":"text","text":" to the web view after calling this function."},{"type":"text","text":" "},{"type":"text","text":"If you wish to set a web view client, call this function again with the new "},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":". You should not call this method when the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","title":"setupWebView(webView:navigationDelegate:)","url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupWebView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationDelegate"},{"text":": ","kind":"text"},{"text":"WKNavigationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"text":"?)","kind":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"url":"\/documentation\/human\/how_to_upgrade_from_v3","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","type":"topic","role":"article","abstract":[{"type":"text","text":"There are few major changes in the SDK’s API. In this article we will cover all of them."}],"kind":"article","title":"How to upgrade from v3"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setupWebViewWithWebView:navigationDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setupWebViewWithWebView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"navigationDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@HUMAN@objc(pl)WKNavigationDelegate","kind":"typeIdentifier","text":"id<WKNavigationDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"navigationDelegate"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","value":"HumanSecurity"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"text":"HumanSecurity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle","value":[{"kind":"identifier","text":"HumanSecurity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title","value":"automaticSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments","value":[{"text":"automaticSetup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title","value":"setupWebViewWithWebView:navigationDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}