{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"variants":[{"paths":["\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"title":"start(appIds:delegate:policy:)","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)startWithAppIds:delegate:policy:error:","symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","kind":"typeIdentifier","text":"HSPolicy"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"abstract":[{"type":"text","text":"Start the SDK."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HumanDelegate","preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The list of AppIDs for your account.","type":"text"}],"type":"paragraph"}],"name":"appIds"},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A delegate object that conform to "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","type":"reference","isActive":true},{"type":"text","text":" protocol."}]}]},{"name":"policy","content":[{"type":"paragraph","inlineContent":[{"text":"The policy object that config the SDK.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"Call this function to start th SDK with multiple AppIDs. You should call this function only once. You should call this function only from the main thread. This function may throw an error.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"url":"\/documentation\/human\/humansecurity","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"role":"symbol","title":"HumanSecurity","kind":"symbol","type":"topic","abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:delegate:policy:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appIds:delegate:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"topic","title":"HSPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"url":"\/documentation\/human\/hspolicy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"startWithAppIds:delegate:policy:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"startWithAppIds:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"appIds","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<HumanDelegate>","preciseIdentifier":"c:Qo@M@HUMAN@objc(pl)HumanDelegate"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"policy:"},{"kind":"text","text":"("},{"text":"HSPolicy","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":" *) ","kind":"text"},{"text":"policy","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title","value":"HumanDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments","value":[{"kind":"identifier","text":"HumanDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","value":"HumanSecurity"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanSecurity"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/title","value":"startWithAppIds:delegate:policy:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/fragments","op":"replace"},{"op":"replace","value":"HSPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"text":"HSPolicy","kind":"identifier"}]}]}]}