{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)"]}],"sections":[],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)startWithAppId:delegate:policy:error:","roleHeading":"Type Method","role":"symbol","title":"start(appId:delegate:policy:)","navigatorTitle":[{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID of your account."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A delegate object that conform to "},{"type":"codeVoice","code":"HumanXDelegate"},{"text":" protocol.","type":"text"}],"type":"paragraph"}],"name":"delegate"},{"name":"policy","content":[{"type":"paragraph","inlineContent":[{"text":"The policy object that config the SDK.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Call this function to start th SDK with a single AppID. You should call this function only once. You should call this function only from the main thread. This function may throw an error."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:delegate:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"start(appId:delegate:policy:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"url":"\/documentation\/human\/humansecurity","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"text":"HumanSecurity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurity","kind":"identifier"}],"role":"symbol","title":"HumanSecurity","kind":"symbol","type":"topic","abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"topic","title":"HSPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"url":"\/documentation\/human\/hspolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"startWithAppId:delegate:policy:error:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithAppId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@HUMAN@objc(pl)HumanDelegate","text":"id<HumanDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"text":"policy:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"policy"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"startWithAppId:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/fragments","op":"replace"},{"value":"HumanDelegate","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title"},{"op":"replace","value":[{"text":"HumanDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments"},{"op":"replace","value":"HumanSecurity","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"value":[{"kind":"identifier","text":"HumanSecurity"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","op":"replace"},{"value":"HSPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"kind":"identifier","text":"HSPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}