{"kind":"symbol","variants":[{"paths":["\/documentation\/human\/humansecurity\/start(appids:policy:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurity\/start(appids:policy:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"appIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The list of AppIDs for your account."}]}]},{"name":"policy","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The policy object that config the SDK."}]}]}],"kind":"parameters"},{"mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"],"kind":"mentions"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this function to start th SDK with multiple AppIDs. You should call this function only once. You should call this function only from the main thread. This function may throw an error."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","interfaceLanguage":"swift"},"abstract":[{"text":"Start the SDK.","type":"text"}],"metadata":{"roleHeading":"Type Method","title":"start(appIds:policy:)","symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HumanSecurity(cm)startWithAppIds:policy:error:","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"HUMAN"}],"role":"symbol"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Integration_Guide":{"abstract":[],"url":"\/documentation\/human\/integration_guide","type":"topic","title":"Integration Guide","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide","kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"kind":"symbol","title":"HSPolicy","url":"\/documentation\/human\/hspolicy","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Advanced_Functionality":{"type":"topic","role":"article","title":"Native - Advanced Functionality","abstract":[],"url":"\/documentation\/human\/native_advanced_functionality","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","role":"symbol","url":"\/documentation\/human\/humansecurity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HumanSecurity","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}],"type":"topic","abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"title":"HumanSecurity"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_sheet":{"abstract":[],"url":"\/documentation\/human\/visionos_integration_sheet","role":"article","title":"visionOS Integration (sheet)","kind":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"kind":"article","role":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","url":"\/documentation\/human\/native_basic_implementation","abstract":[],"title":"Native - Basic Implementation"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/gRPC_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","role":"article","url":"\/documentation\/human\/grpc_integration","kind":"article","type":"topic","abstract":[],"title":"gRPC Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"type":"topic","role":"article","title":"visionOS Integration (window)","kind":"article","url":"\/documentation\/human\/visionos_integration_window","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Flutter_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","role":"article","url":"\/documentation\/human\/flutter_integration","kind":"article","type":"topic","abstract":[],"title":"Flutter Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Ionic_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","role":"article","url":"\/documentation\/human\/ionic_integration","kind":"article","type":"topic","abstract":[],"title":"Ionic Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"kind":"symbol","title":"start(appIds:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"topic","abstract":[{"text":"Start the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"type":"topic","role":"article","title":"Native - Easiest Implementation","kind":"article","abstract":[],"url":"\/documentation\/human\/native_easiest_implementation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/React_Native_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","role":"article","url":"\/documentation\/human\/react_native_integration","kind":"article","type":"topic","abstract":[],"title":"React Native Integration"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startWithAppIds:policy:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithAppIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"policy"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"appIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The list of AppIDs for your account."}]}]},{"name":"policy","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The policy object that config the SDK."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}],"kind":"content"},"op":"add","path":"\/primaryContentSections\/2"},{"value":"HSPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"value":[{"text":"HSPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"value":[{"text":"HSPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle"},{"value":"HumanSecurity","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments"},{"value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle"},{"value":"startWithAppIds:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}