{"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/allowSharingPolicyWithHuman","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSPolicy(py)allowSharingPolicyWithHuman","modules":[{"name":"HUMAN"}],"title":"allowSharingPolicyWithHuman","navigatorTitle":[{"text":"allowSharingPolicyWithHuman","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowSharingPolicyWithHuman"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"abstract":[{"type":"text","text":"Allow the SDK to share the policy with HUMAN. The policy does not contain PII."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/human\/hspolicy\/allowsharingpolicywithhuman"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hspolicy\/allowsharingpolicywithhuman"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSharingPolicyWithHuman","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"role":"symbol","url":"\/documentation\/human\/hspolicy","type":"topic","title":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/allowSharingPolicyWithHuman":{"url":"\/documentation\/human\/hspolicy\/allowsharingpolicywithhuman","navigatorTitle":[{"text":"allowSharingPolicyWithHuman","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/allowSharingPolicyWithHuman","title":"allowSharingPolicyWithHuman","abstract":[{"text":"Allow the SDK to share the policy with HUMAN. The policy does not contain PII.","type":"text"},{"text":" ","type":"text"},{"text":"Default is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSharingPolicyWithHuman","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"allowSharingPolicyWithHuman","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowSharingPolicyWithHuman"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowSharingPolicyWithHuman"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy","op":"replace"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle"},{"value":"allowSharingPolicyWithHuman","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1allowSharingPolicyWithHuman\/title"},{"value":[{"text":"allowSharingPolicyWithHuman","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1allowSharingPolicyWithHuman\/fragments"}]}]}