{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"automaticInterceptorPolicy"}],"title":"automaticInterceptorPolicy","role":"symbol","symbolKind":"property","modules":[{"name":"HUMAN"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticInterceptorPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy","kind":"typeIdentifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSPolicy(py)automaticInterceptorPolicy","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Configure the Automatic Interceptor policy."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"automaticInterceptorPolicy","kind":"identifier"},{"kind":"text","text":": "},{"text":"HSAutomaticInterceptorPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hspolicy\/automaticinterceptorpolicy"]},{"paths":["\/documentation\/human\/hspolicy\/automaticinterceptorpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/automaticInterceptorPolicy"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"type":"topic","kind":"symbol","title":"HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/automaticInterceptorPolicy":{"kind":"symbol","role":"symbol","title":"automaticInterceptorPolicy","type":"topic","abstract":[{"type":"text","text":"Configure the Automatic Interceptor policy."}],"url":"\/documentation\/human\/hspolicy\/automaticinterceptorpolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/automaticInterceptorPolicy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"automaticInterceptorPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy","text":"HSAutomaticInterceptorPolicy","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"automaticInterceptorPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"role":"symbol","title":"HSAutomaticInterceptorPolicy","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the Automatic Interceptor.","type":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"automaticInterceptorPolicy","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"automaticInterceptorPolicy","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy"},{"text":" * ","kind":"text"},{"text":"automaticInterceptorPolicy","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"automaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1automaticInterceptorPolicy\/title","op":"replace"},{"value":[{"text":"automaticInterceptorPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1automaticInterceptorPolicy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy"},{"op":"replace","value":[{"kind":"identifier","text":"HSPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle"},{"op":"replace","value":"HSAutomaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}