{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/copy(with:)"},"metadata":{"symbolKind":"method","title":"copy(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@HUMAN@objc(cs)HSPolicy(im)copyWithZone:","modules":[{"name":"HUMAN"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NSCopying.copy(with:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"zone"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"kind":"text","text":"? = nil) -> "},{"kind":"keyword","text":"Any"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hspolicy\/copy(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hspolicy\/copy(with:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"topic","title":"HSPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"url":"\/documentation\/human\/hspolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/copy(with:)":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copy(with:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/copy(with:)","url":"\/documentation\/human\/hspolicy\/copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"Any"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"copyWithZone:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"HSPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"value":[{"text":"HSPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","op":"replace"},{"value":"copyWithZone:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1copy(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}