{"variants":[{"paths":["\/documentation\/human\/hspolicy\/detectionpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hspolicy\/detectionpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"detectionPolicy"}],"externalID":"c:@M@HUMAN@objc(cs)HSPolicy(py)detectionPolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSDetectionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDetectionPolicy"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"detectionPolicy","modules":[{"name":"HUMAN"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDetectionPolicy","text":"HSDetectionPolicy","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/detectionPolicy"},"abstract":[{"type":"text","text":"Configure the detection policy."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","title":"HSPolicy","type":"topic","role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/detectionPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/detectionPolicy","url":"\/documentation\/human\/hspolicy\/detectionpolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDetectionPolicy","text":"HSDetectionPolicy","kind":"typeIdentifier"}],"title":"detectionPolicy","abstract":[{"type":"text","text":"Configure the detection policy."}],"role":"symbol","navigatorTitle":[{"text":"detectionPolicy","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"type":"topic","title":"HSDetectionPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK’s detection.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","kind":"symbol","url":"\/documentation\/human\/hsdetectionpolicy","role":"symbol","navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectionPolicy","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"detectionPolicy"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"HSDetectionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDetectionPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"},{"text":" * ","kind":"text"},{"text":"detectionPolicy","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HSPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1detectionPolicy\/title","op":"replace","value":"detectionPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1detectionPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title","op":"replace","value":"HSDetectionPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSDetectionPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}]}]}]}