{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Configure the Doctor App policy.","type":"text"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/doctorAppPolicy","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorAppPolicy"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy","text":"HSDoctorAppPolicy"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hspolicy\/doctorapppolicy"]},{"paths":["\/documentation\/human\/hspolicy\/doctorapppolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"doctorAppPolicy","kind":"identifier"}],"title":"doctorAppPolicy","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"doctorAppPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy","text":"HSDoctorAppPolicy","kind":"typeIdentifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSPolicy(py)doctorAppPolicy","symbolKind":"property"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/doctorAppPolicy":{"url":"\/documentation\/human\/hspolicy\/doctorapppolicy","abstract":[{"text":"Configure the Doctor App policy.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"doctorAppPolicy"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/doctorAppPolicy","kind":"symbol","title":"doctorAppPolicy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorAppPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy","text":"HSDoctorAppPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"title":"HSPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/human\/hspolicy","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","title":"HSDoctorAppPolicy","navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the Doctor App.","type":"text"}],"type":"topic","url":"\/documentation\/human\/hsdoctorapppolicy","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"doctorAppPolicy","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"doctorAppPolicy"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy","text":"HSDoctorAppPolicy","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"doctorAppPolicy","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"doctorAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1doctorAppPolicy\/title"},{"value":[{"kind":"identifier","text":"doctorAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1doctorAppPolicy\/fragments"},{"value":"HSPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"value":[{"text":"HSPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle"},{"value":"HSDoctorAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title"},{"value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments"},{"value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle"}]}]}