{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybridAppPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","text":"HSHybridAppPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy"}],"languages":["swift"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hybridAppPolicy"},{"kind":"text","text":": "},{"text":"HSHybridAppPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy","kind":"typeIdentifier"}],"modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"hybridAppPolicy","kind":"identifier"}],"role":"symbol","title":"hybridAppPolicy","externalID":"c:@M@HUMAN@objc(cs)HSPolicy(py)hybridAppPolicy"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/hybridAppPolicy","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Configure the Hybrid App support policy."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"variants":[{"paths":["\/documentation\/human\/hspolicy\/hybridapppolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hspolicy\/hybridapppolicy"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/hybridAppPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/hybridAppPolicy","abstract":[{"text":"Configure the Hybrid App support policy.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybridAppPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy","kind":"typeIdentifier","text":"HSHybridAppPolicy"}],"url":"\/documentation\/human\/hspolicy\/hybridapppolicy","type":"topic","navigatorTitle":[{"text":"hybridAppPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"hybridAppPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"topic","title":"HSPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"url":"\/documentation\/human\/hspolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSHybridAppPolicy"}],"abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}],"role":"symbol","title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","navigatorTitle":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"hybridAppPolicy"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"hybridAppPolicy","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","text":"HSHybridAppPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"hybridAppPolicy","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1hybridAppPolicy\/title","value":"hybridAppPolicy","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"hybridAppPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1hybridAppPolicy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"text":"HSPolicy","kind":"identifier"}],"op":"replace"},{"value":"HSHybridAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}