{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSPolicy(im)init","roleHeading":"Instance Method","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"HUMAN"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/init","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hspolicy\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/init":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","abstract":[],"title":"init","type":"topic","url":"\/documentation\/human\/hspolicy\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hspolicy","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"HSPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","value":[{"text":"HSPolicy","kind":"identifier"}]}]}]}