{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanchallengeresult\/cancelled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanchallengeresult\/cancelled"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/cancelled","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult"]]},"abstract":[{"type":"text","text":"Challenge was cancelled."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"HUMAN"}],"roleHeading":"Case","externalID":"c:@M@HUMAN@E@HumanChallengeResult@HumanChallengeResultCancelled","navigatorTitle":[{"text":"HumanChallengeResultCancelled","kind":"identifier"}],"title":"HumanChallengeResult.cancelled"},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult":{"url":"\/documentation\/human\/humanchallengeresult","type":"topic","abstract":[{"type":"text","text":"Challenge result."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HumanChallengeResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HumanChallengeResult"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","title":"HumanChallengeResult","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/human\/humanchallengeresult\/cancelled","abstract":[{"text":"Challenge was cancelled.","type":"text"}],"navigatorTitle":[{"text":"HumanChallengeResultCancelled","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/cancelled","type":"topic","title":"HumanChallengeResult.cancelled"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"HumanChallengeResultCancelled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"HumanChallengeResultCancelled"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HumanChallengeResultCancelled"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/title","value":"HumanChallengeResult","op":"replace"},{"op":"replace","value":[{"text":"HumanChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/fragments"},{"op":"replace","value":"HumanChallengeResultCancelled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1cancelled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1cancelled\/fragments","value":[{"text":"HumanChallengeResultCancelled","kind":"identifier"}]}]}]}