{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solved"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/solved"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanchallengeresult\/solved"]},{"paths":["\/documentation\/human\/humanchallengeresult\/solved"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult"]]},"metadata":{"modules":[{"name":"HUMAN"}],"role":"symbol","externalID":"c:@M@HUMAN@E@HumanChallengeResult@HumanChallengeResultSolved","title":"HumanChallengeResult.solved","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solved","kind":"identifier"}],"navigatorTitle":[{"text":"HumanChallengeResultSolved","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"Challenge was solved."}],"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/solved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/solved","role":"symbol","title":"HumanChallengeResult.solved","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solved","kind":"identifier"}],"navigatorTitle":[{"text":"HumanChallengeResultSolved","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/human\/humanchallengeresult\/solved","abstract":[{"type":"text","text":"Challenge was solved."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult":{"url":"\/documentation\/human\/humanchallengeresult","type":"topic","abstract":[{"type":"text","text":"Challenge result."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HumanChallengeResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HumanChallengeResult"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","title":"HumanChallengeResult","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"HumanChallengeResultSolved"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HumanChallengeResultSolved"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"HumanChallengeResultSolved","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HumanChallengeResultSolved","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1solved\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1solved\/fragments","value":[{"text":"HumanChallengeResultSolved","kind":"identifier"}],"op":"replace"},{"value":"HumanChallengeResult","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/title"},{"op":"replace","value":[{"text":"HumanChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/fragments"}]}]}