{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeReferenceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The value is unique per app run. Meaning, for each challenge in the app run the value will be the same for all challenges.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that the value in the challenge screen will be different from the returned value when:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Doctor App is enabled, due to internal implementation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The “X-PX-AUTHORIZATION” HTTP header is missing or does not contain a token."}]}]}],"type":"orderedList"}],"kind":"content"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@HUMAN@objc(cs)HSBotDefender(im)challengeReferenceId","navigatorTitle":[{"kind":"identifier","text":"challengeReferenceId"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeReferenceId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"challengeReferenceId()","modules":[{"name":"HUMAN"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/challengeReferenceId()"},"abstract":[{"type":"text","text":"Returns the challenge’s Reference ID. This value will appear in the challenge screen."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefender\/challengereferenceid()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefender\/challengereferenceid()"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"title":"HSBotDefender","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","kind":"symbol","url":"\/documentation\/human\/hsbotdefender","navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/challengeReferenceId()":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/challengeReferenceId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeReferenceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/human\/hsbotdefender\/challengereferenceid()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"challengeReferenceId"}],"abstract":[{"type":"text","text":"Returns the challenge’s Reference ID. This value will appear in the challenge screen."}],"title":"challengeReferenceId()"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"challengeReferenceId","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"challengeReferenceId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"challengeReferenceId","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HSBotDefender","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle"},{"op":"replace","value":"challengeReferenceId","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1challengeReferenceId()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"challengeReferenceId"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1challengeReferenceId()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}