{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/delegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefender\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefender\/delegate"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","text":"HSBotDefenderDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate","text":"HSBotDefenderDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@HUMAN@objc(cs)HSBotDefender(py)delegate","modules":[{"name":"HUMAN"}],"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"role":"symbol","navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"title":"HSBotDefender","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/human\/hsbotdefenderdelegate","title":"HSBotDefenderDelegate"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/delegate":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/delegate","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender\/delegate","title":"delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate","text":"HSBotDefenderDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<HSBotDefenderDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@HUMAN@objc(pl)HSBotDefenderDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","value":"HSBotDefender","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title","value":"HSBotDefenderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}