{"variants":[{"paths":["\/documentation\/human\/hsbotdefender\/errortype(error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsbotdefender\/errortype(error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType"}]}]},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The error to check","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Returns the relevant ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","type":"reference","isActive":true},{"text":" of the given error. If the error is not related, this function will return ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","type":"reference","isActive":true},{"text":".","type":"text"}],"metadata":{"title":"errorType(error:)","role":"symbol","modules":[{"name":"HUMAN"}],"symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HSBotDefender(im)errorTypeWithError:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HSBotDefenderErrorType","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"errorTypeWithError:","kind":"identifier"}]},"kind":"symbol","sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"role":"symbol","navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"title":"HSBotDefender","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"url":"\/documentation\/human\/hsbotdefendererrortype","type":"topic","navigatorTitle":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"abstract":[],"title":"HSBotDefenderErrorType","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/errorType(error:)":{"role":"symbol","navigatorTitle":[{"text":"errorTypeWithError:","kind":"identifier"}],"type":"topic","title":"errorType(error:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"HSBotDefenderErrorType","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the relevant "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","isActive":true},{"type":"text","text":" of the given error. If the error is not related, this function will return "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/human\/hsbotdefender\/errortype(error:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/unknown":{"navigatorTitle":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsbotdefendererrortype\/unknown","kind":"symbol","title":"HSBotDefenderErrorType.unknown","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"errorTypeWithError:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"errorTypeWithError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","kind":"typeIdentifier","text":"HSBotDefenderErrorType","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType"},{"kind":"text","text":") "},{"kind":"identifier","text":"errorTypeWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error to check"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","value":"HSBotDefender"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"kind":"identifier","text":"HSBotDefender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle","value":[{"text":"HSBotDefender","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","value":"HSBotDefenderErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/title","value":"errorTypeWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorTypeWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/title","value":"HSBotDefenderErrorTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/fragments","value":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}