{"variants":[{"paths":["\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"response","content":[{"inlineContent":[{"type":"text","text":"The response that was received from the URL request."}],"type":"paragraph"}]},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"The data that was received from the URL request."}],"type":"paragraph"}]},{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"The callback that indicate the challenge’s result. The callback will be called once the user solved (or cancelled)  the challenge. You may use this to retry the URL request."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the Human’s payload in the response was handled by the SDK. This function should be used only when the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true},{"type":"text","text":" is set to "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true},{"type":"text","text":" in the policy."}]}]}],"metadata":{"title":"handleResponse(response:data:callback:)","role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"text":"HSBotDefenderChallengeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult"},{"text":") -> ())?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@HUMAN@objc(cs)HSBotDefender(im)handleResponseWithResponse:data:callback:"},"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/React_Native_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","role":"article","url":"\/documentation\/human\/react_native_integration","kind":"article","type":"topic","abstract":[],"title":"React Native Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/gRPC_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","role":"article","url":"\/documentation\/human\/grpc_integration","kind":"article","type":"topic","abstract":[],"title":"gRPC Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","role":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"title":"HSAutomaticInterceptorType.none"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"type":"topic","role":"symbol","title":"HSBotDefender","kind":"symbol","url":"\/documentation\/human\/hsbotdefender","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSBotDefender"}],"navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"kind":"article","role":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","url":"\/documentation\/human\/native_basic_implementation","abstract":[],"title":"Native - Basic Implementation"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","role":"symbol","url":"\/documentation\/human\/hsbotdefenderchallengeresult","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"type":"topic","abstract":[],"title":"HSBotDefenderChallengeResult"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Ionic_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","role":"article","url":"\/documentation\/human\/ionic_integration","kind":"article","type":"topic","abstract":[],"title":"Ionic Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Flutter_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","role":"article","url":"\/documentation\/human\/flutter_integration","kind":"article","type":"topic","abstract":[],"title":"Flutter Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"type":"topic","role":"article","title":"visionOS Integration (window)","kind":"article","url":"\/documentation\/human\/visionos_integration_window","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"url":"\/documentation\/human\/hsautomaticinterceptortype","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","role":"symbol","url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleResponseWithResponse:data:callback:"}],"type":"topic","abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"title":"handleResponse(response:data:callback:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"handleResponseWithResponse:data:callback:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"handleResponseWithResponse:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","text":"HSBotDefenderChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The response that was received from the URL request.","type":"text"}],"type":"paragraph"}],"name":"response"},{"content":[{"inlineContent":[{"text":"The data that was received from the URL request.","type":"text"}],"type":"paragraph"}],"name":"data"},{"content":[{"inlineContent":[{"type":"text","text":"The callback that indicate the challenge’s result. The callback will be called once the user solved (or cancelled)  the challenge. You may use this to retry the URL request."}],"type":"paragraph"}],"name":"callback"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","value":"HSBotDefender","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"text":"HSBotDefender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle","op":"replace","value":[{"text":"HSBotDefender","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","value":"HSBotDefenderChallengeResult"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType"},{"op":"replace","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"},{"op":"replace","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title","value":"handleResponseWithResponse:data:callback:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}