{"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy(py)allowJavaScriptEvaluation","title":"allowJavaScriptEvaluation","symbolKind":"property","modules":[{"name":"HUMAN"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowJavaScriptEvaluation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}]},"abstract":[{"type":"text","text":"Allow the SDK to evaluate JavaScript code in your web views (for hybrid app support). You should disable JavaScript code when using ApplePay in your web view. When you disable JavaScript evaluation, the SDK could store cookies instead (depending on the run time environment). Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowJavaScriptEvaluation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/allowJavaScriptEvaluation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hshybridapppolicy\/allowjavascriptevaluation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hshybridapppolicy\/allowjavascriptevaluation"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSHybridAppPolicy"}],"title":"HSHybridAppPolicy","abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/allowJavaScriptEvaluation":{"navigatorTitle":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/allowjavascriptevaluation","title":"allowJavaScriptEvaluation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/allowJavaScriptEvaluation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowJavaScriptEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Allow the SDK to evaluate JavaScript code in your web views (for hybrid app support). You should disable JavaScript code when using ApplePay in your web view. When you disable JavaScript evaluation, the SDK could store cookies instead (depending on the run time environment). Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowJavaScriptEvaluation"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"allowJavaScriptEvaluation","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"HSHybridAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","value":[{"kind":"identifier","text":"HSHybridAppPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]},{"value":"allowJavaScriptEvaluation","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1allowJavaScriptEvaluation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1allowJavaScriptEvaluation\/fragments","value":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}]}]}]}