{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup"},"kind":"symbol","abstract":[{"text":"When this property is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the SDK detects all ","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true,"type":"reference"},{"text":" function. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy(py)automaticSetup","navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}],"title":"automaticSetup","modules":[{"name":"HUMAN"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticSetup","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/human\/hshybridapppolicy\/automaticsetup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hshybridapppolicy\/automaticsetup"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticSetup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Hybrid_App_Integration":{"role":"article","type":"topic","kind":"article","url":"\/documentation\/human\/hybrid_app_integration","title":"Hybrid App Integration","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"title":"automaticSetup","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}],"type":"topic","abstract":[{"type":"text","text":"When this property is "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the SDK detects all "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true},{"text":" function. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticSetup"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Setup the web view to be synced with SDK. Do not set a "},{"code":"WKNavigationDelegate","type":"codeVoice"},{"type":"text","text":" to the web view after calling this function."},{"type":"text","text":" "},{"type":"text","text":"If you wish to set a web view client, call this function again with the new "},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":". You should not call this method when the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","title":"setupWebView(webView:navigationDelegate:)","url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupWebView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationDelegate"},{"text":": ","kind":"text"},{"text":"WKNavigationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"text":"?)","kind":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"url":"\/documentation\/human\/how_to_upgrade_from_v3","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","type":"topic","role":"article","abstract":[{"type":"text","text":"There are few major changes in the SDK’s API. In this article we will cover all of them."}],"kind":"article","title":"How to upgrade from v3"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"title":"HSHybridAppPolicy","navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"url":"\/documentation\/human\/hshybridapppolicy","kind":"symbol","abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"automaticSetup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"automaticSetup"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"automaticSetup","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title","value":"automaticSetup"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments","op":"replace","value":[{"text":"automaticSetup","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title","op":"replace","value":"setupWebViewWithWebView:navigationDelegate:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWebViewWithWebView:navigationDelegate:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title","op":"replace","value":"HSHybridAppPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSHybridAppPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}