{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy"]]},"sections":[],"variants":[{"paths":["\/documentation\/human\/hshybridapppolicy\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/init"},"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy(im)init","role":"symbol","title":"init","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","modules":[{"name":"HUMAN"}]},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"kind":"symbol","title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","navigatorTitle":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","type":"topic","abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/human\/hshybridapppolicy\/init","title":"init","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"HSHybridAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title"},{"value":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments"},{"value":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}