{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webRootDomains","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"domains","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"List if your website’s root domains.","type":"text"}]}],"name":"domains"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account.","type":"text"}]}],"name":"appId"}],"kind":"parameters"},{"mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"],"kind":"mentions"}],"abstract":[{"type":"text","text":"The SDK is setting cookies in your web views in order to sync between the native and the web sessions. For that, the SDK has to know you website’s root domain for the HTTP cookie (e.g “.example.com”). Those domains can be set in the HUMAN’s Portal, however, it recommended to set them directly in the SDK’s policy."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}],"roleHeading":"Instance Method","role":"symbol","title":"set(webRootDomains:forAppId:)","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy(im)setWithWebRootDomains:forAppId:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webRootDomains","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hshybridapppolicy\/set(webrootdomains:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hshybridapppolicy\/set(webrootdomains:forappid:)"]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","kind":"article","role":"article","type":"topic","url":"\/documentation\/human\/how_to_upgrade_from_v3","abstract":[{"text":"There are few major changes in the SDK’s API. In this article we will cover all of them.","type":"text"}],"title":"How to upgrade from v3"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/set(webRootDomains:forAppId:)":{"role":"symbol","type":"topic","kind":"symbol","title":"set(webRootDomains:forAppId:)","abstract":[{"text":"The SDK is setting cookies in your web views in order to sync between the native and the web sessions. For that, the SDK has to know you website’s root domain for the HTTP cookie (e.g “.example.com”). Those domains can be set in the HUMAN’s Portal, however, it recommended to set them directly in the SDK’s policy.","type":"text"}],"navigatorTitle":[{"text":"setWithWebRootDomains:forAppId:","kind":"identifier"}],"url":"\/documentation\/human\/hshybridapppolicy\/set(webrootdomains:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webRootDomains","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"navigatorTitle":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"type":"topic","abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}],"role":"symbol","title":"HSHybridAppPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","kind":"symbol","url":"\/documentation\/human\/hshybridapppolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setWithWebRootDomains:forAppId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setWithWebRootDomains:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" *) ","kind":"text"},{"text":"domains","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"domains","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List if your website’s root domains."}]}]},{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID of your account."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"setWithWebRootDomains:forAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setWithWebRootDomains:forAppId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/fragments"},{"op":"replace","value":"HSHybridAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title"},{"op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments"},{"op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}