{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hshybridapppolicy\/supportexternalwebviews"]},{"paths":["\/documentation\/human\/hshybridapppolicy\/supportexternalwebviews"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/supportExternalWebViews","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportExternalWebViews","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy(py)supportExternalWebViews","role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportExternalWebViews"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"supportExternalWebViews","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"supportExternalWebViews"},"abstract":[{"text":"Set this property to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" to support external web views, which are web views created outside the native side of the app but are still based on ","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"text":" (for example, ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview","type":"reference"},{"text":"). Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/supportExternalWebViews":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/supportExternalWebViews","role":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/supportexternalwebviews","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportExternalWebViews","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"supportExternalWebViews","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Set this property to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" to support external web views, which are web views created outside the native side of the app but are still based on "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" (for example, "},{"identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview","type":"reference","isActive":true},{"type":"text","text":"). Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"title":"supportExternalWebViews"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"https://github.com/react-native-webview/react-native-webview":{"titleInlineContent":[{"type":"text","text":"react-native-webview"}],"type":"link","url":"https:\/\/github.com\/react-native-webview\/react-native-webview","title":"react-native-webview","identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"kind":"symbol","title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","navigatorTitle":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","type":"topic","abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"supportExternalWebViews","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"supportExternalWebViews","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"supportExternalWebViews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"supportExternalWebViews","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1supportExternalWebViews\/title","op":"replace"},{"value":[{"text":"supportExternalWebViews","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1supportExternalWebViews\/fragments","op":"replace"},{"value":"HSHybridAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title","op":"replace"},{"value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","op":"replace"},{"value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle","op":"replace"}]}]}