{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bypassMonitorHeaderKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"This value represent the bypass monitor header key that will be sent when the Doctor App is enabled. It should be use when the Enforcer is configured to "},{"code":"monitor mode","type":"codeVoice"},{"type":"text","text":". This value should be configured in the Enforcer as well. As a result, URL requests will be blocked despite the "},{"code":"monitor mode","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsdoctorapppolicy\/bypassmonitorheaderkey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsdoctorapppolicy\/bypassmonitorheaderkey"]}],"sections":[],"metadata":{"title":"bypassMonitorHeaderKey","modules":[{"name":"HUMAN"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy(py)bypassMonitorHeaderKey","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bypassMonitorHeaderKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"bypassMonitorHeaderKey","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/bypassMonitorHeaderKey","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"kind":"symbol","role":"symbol","url":"\/documentation\/human\/hsdoctorapppolicy","navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"abstract":[{"type":"text","text":"The policy that define the behaviour of the Doctor App."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","title":"HSDoctorAppPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/bypassMonitorHeaderKey":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/bypassMonitorHeaderKey","navigatorTitle":[{"text":"bypassMonitorHeaderKey","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bypassMonitorHeaderKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/human\/hsdoctorapppolicy\/bypassmonitorheaderkey","title":"bypassMonitorHeaderKey","type":"topic","abstract":[{"type":"text","text":"This value represent the bypass monitor header key that will be sent when the Doctor App is enabled. It should be use when the Enforcer is configured to "},{"type":"codeVoice","code":"monitor mode"},{"type":"text","text":". This value should be configured in the Enforcer as well. As a result, URL requests will be blocked despite the "},{"type":"codeVoice","code":"monitor mode"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bypassMonitorHeaderKey","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"bypassMonitorHeaderKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"bypassMonitorHeaderKey","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HSDoctorAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments","value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle","value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1bypassMonitorHeaderKey\/title","value":"bypassMonitorHeaderKey","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1bypassMonitorHeaderKey\/fragments","value":[{"text":"bypassMonitorHeaderKey","kind":"identifier"}],"op":"replace"}]}]}