{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy"]]},"sections":[],"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy(py)enabled","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"HUMAN"}],"role":"symbol","title":"enabled"},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/human\/hsdoctorapppolicy\/enabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsdoctorapppolicy\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/enabled":{"title":"enabled","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/human\/hsdoctorapppolicy\/enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","abstract":[],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"role":"symbol","navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"kind":"symbol","title":"HSDoctorAppPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsdoctorapppolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Doctor App."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"enabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"enabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"enabled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/title"},{"value":[{"text":"enabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/fragments"},{"value":"HSDoctorAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title"},{"value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments"},{"value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}