{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsdoctorapppolicy\/init"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}],"navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsdoctorapppolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Doctor App."}],"title":"HSDoctorAppPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/init":{"url":"\/documentation\/human\/hsdoctorapppolicy\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/init","kind":"symbol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"HSDoctorAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title"},{"value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments"},{"value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle"}]}]}