{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDomain:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"domain","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code:"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"text":"dict","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/hserror\/initwithdomain:code:userinfo:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"initWithDomain:code:userInfo:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDomain:code:userInfo:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDomain:code:userInfo:","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSError(im)initWithDomain:code:userInfo:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithDomain:code:userInfo:"},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError/initWithDomain:code:userInfo:":{"type":"topic","url":"\/documentation\/human\/hserror\/initwithdomain:code:userinfo:","role":"symbol","title":"initWithDomain:code:userInfo:","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithDomain:code:userInfo:","navigatorTitle":[{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError":{"url":"\/documentation\/human\/hserror","type":"topic","role":"symbol","title":"HSError","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","navigatorTitle":[{"text":"HSError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSError","kind":"identifier"}],"abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"HSError","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/title","op":"replace"},{"value":[{"text":"HSError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/navigatorTitle","value":[{"kind":"identifier","text":"HSError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}