{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"title":"registerOutgoingUrlRequest(url:forAppId:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSAccountDefender(im)registerOutgoingUrlRequestWithUrl:forAppId:error:","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"url","content":[{"inlineContent":[{"text":"The URL.","type":"text"}],"type":"paragraph"}]},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account. If you use only one AppID you may pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}]},{"mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"],"kind":"mentions"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must call the "},{"type":"codeVoice","code":"HumanSecurity\/setUserId(userId:forAppId:)"},{"type":"text","text":" function before calling this function. If the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true},{"type":"text","text":" is set to any value rather than "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true},{"type":"text","text":", you should not need to use this function (it will be called automatically by the SDK)."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Provide outgoing URL request to the Account Defender feature.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"url":"\/documentation\/human\/hsautomaticinterceptortype","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"title":"HSAutomaticInterceptorType","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_sheet":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","role":"article","kind":"article","abstract":[],"title":"visionOS Integration (sheet)","url":"\/documentation\/human\/visionos_integration_sheet","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","kind":"symbol","role":"symbol","title":"HSAccountDefender","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HSAccountDefender","kind":"identifier"}],"abstract":[],"url":"\/documentation\/human\/hsaccountdefender","navigatorTitle":[{"text":"HSAccountDefender","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/registerOutgoingUrlRequest(url:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","kind":"symbol","role":"symbol","title":"registerOutgoingUrlRequest(url:forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Provide outgoing URL request to the Account Defender feature.","type":"text"}],"url":"\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)","navigatorTitle":[{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"role":"article","type":"topic","url":"\/documentation\/human\/native_basic_implementation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","title":"Native - Basic Implementation","abstract":[],"kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/none","title":"HSAutomaticInterceptorType.none","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","kind":"article","role":"article","title":"visionOS Integration (window)","abstract":[],"url":"\/documentation\/human\/visionos_integration_window","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"registerOutgoingUrlRequestWithUrl:forAppId:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL.","type":"text"}]}],"name":"url"},{"content":[{"inlineContent":[{"text":"The AppID of your account. If you use only one AppID you may pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"appId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"code":"YES","type":"codeVoice"},{"text":" if the method succeeded, otherwise ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},"op":"add","path":"\/primaryContentSections\/2"},{"value":"HSAutomaticInterceptorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title","value":"HSAccountDefender"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments","value":[{"kind":"identifier","text":"HSAccountDefender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle","value":[{"kind":"identifier","text":"HSAccountDefender"}]},{"op":"replace","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/fragments"},{"op":"replace","value":"HSAutomaticInterceptorTypeNone","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments"}]}]}