{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdditionalData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Custom parameters."}],"type":"paragraph"}],"name":"parameters"},{"content":[{"inlineContent":[{"text":"The AppID to associate the custom parameters with. If you use only one AppID you may pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"appId"}]},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"You must call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" function before calling this function.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)"]}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSAccountDefender(im)setAdditionalDataWithParameters:forAppId:error:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdditionalData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"title":"setAdditionalData(parameters:forAppId:)","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender"]]},"abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Advanced_Functionality":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","role":"article","kind":"article","abstract":[],"title":"Native - Advanced Functionality","url":"\/documentation\/human\/native_advanced_functionality","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","kind":"symbol","role":"symbol","title":"HSAccountDefender","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HSAccountDefender","kind":"identifier"}],"abstract":[],"url":"\/documentation\/human\/hsaccountdefender","navigatorTitle":[{"text":"HSAccountDefender","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","kind":"article","role":"article","title":"visionOS Integration (window)","abstract":[],"url":"\/documentation\/human\/visionos_integration_window","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_sheet":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","role":"article","kind":"article","abstract":[],"title":"visionOS Integration (sheet)","url":"\/documentation\/human\/visionos_integration_sheet","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}],"url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","title":"setAdditionalData(parameters:forAppId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdditionalData"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"startWithAppId:policy:error:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"role":"article","type":"topic","url":"\/documentation\/human\/native_basic_implementation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","title":"Native - Basic Implementation","abstract":[],"kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"title":"Native - Easiest Implementation","url":"\/documentation\/human\/native_easiest_implementation","abstract":[],"kind":"article","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setAdditionalDataWithParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"parameters","content":[{"inlineContent":[{"type":"text","text":"Custom parameters."}],"type":"paragraph"}]},{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID to associate the custom parameters with. If you use only one AppID you may pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"add","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title","op":"replace","value":"HSAccountDefender"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments","op":"replace","value":[{"text":"HSAccountDefender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HSAccountDefender"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title","op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","op":"replace","value":"startWithAppId:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}]}]}]}