{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"metadata":{"roleHeading":"Article","role":"article","title":"Flutter Integration","modules":[{"name":"HUMAN"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/human\/flutter_integration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/flutter_integration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Intro","level":2,"text":"Intro"},{"type":"paragraph","inlineContent":[{"text":"The SDK can be integrated into a ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/flutter.dev\/"},{"text":" project.","type":"text"}]},{"type":"heading","anchor":"How-to-start-the-SDK","level":2,"text":"How to start the SDK"},{"items":[{"content":[{"inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"Application","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"onCreate","type":"codeVoice"},{"type":"text","text":" function on Android."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"AppDelegate"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"didFinishLaunchingWithOptions"},{"type":"text","text":" function on iOS."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"You should start the SDK on the ","type":"text"},{"type":"strong","inlineContent":[{"text":"main thread","type":"text"}]},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Create a "},{"code":"HumanManager","type":"codeVoice"},{"type":"text","text":" object that will handle calls from Flutter side."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"On Android, register the ","type":"text"},{"type":"codeVoice","code":"HumanManager"},{"text":" in the ","type":"text"},{"type":"codeVoice","code":"FlutterEngine"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"On iOS, setup the channel.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}]},{"type":"heading","anchor":"Android","level":3,"text":"Android"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin \/ MainApplication.kt:"}]},{"type":"codeListing","syntax":"kotlin","code":["import android.app.Application","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        HumanManager.start(this)","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Kotlin \/ HumanManager.kt:","type":"text"}]},{"type":"codeListing","syntax":"kotlin","code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.policy.HSPolicy","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType","import com.humansecurity.mobile_sdk.main.HSBotDefenderChallengeResult","import io.flutter.plugin.common.MethodCall","import io.flutter.plugin.common.MethodChannel","import org.json.JSONObject","","class HumanManager {","","    companion object {","        fun start(application: Application) {","            try {","                val policy = HSPolicy()","                policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorType.NONE","                HumanSecurity.start(application, \"<APP_ID>\", policy)","            }","            catch (exception: Exception) {","                println(\"Exception: ${exception.message}\")","            }","        }","","        fun handleEvent(call: MethodCall, result: MethodChannel.Result) {","            if (call.method == \"humanGetHeaders\") {","                val json = JSONObject((HumanSecurity.BD.headersForURLRequest(\"<APP_ID>\") as Map<*, *>?))","                result.success(json.toString())","            }","            else if (call.method == \"humanHandleResponse\") {","                val handled = HumanSecurity.BD.handleResponse(call.arguments!! as String) { challengeResult: HSBotDefenderChallengeResult ->","                    result.success(if (challengeResult == HSBotDefenderChallengeResult.SOLVED) \"solved\" else \"cancelled\")","                    null","                }","                if (!handled) {","                    result.success(\"false\")","                }","            }","            else {","                result.notImplemented()","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Kotlin \/ MainActivity.kt:","type":"text"}]},{"syntax":"kotlin","code":["import androidx.annotation.NonNull","import io.flutter.embedding.android.FlutterActivity","import io.flutter.embedding.engine.FlutterEngine","import io.flutter.plugin.common.MethodChannel","","class MainActivity: FlutterActivity() {","","    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {","        super.configureFlutterEngine(flutterEngine)","        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, \"com.humansecurity\/sdk\").setMethodCallHandler {","                call, result ->","            HumanManager.handleEvent(call, result)","        }","    }","}"],"type":"codeListing"},{"text":"iOS","type":"heading","level":3,"anchor":"iOS"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift \/ HumanManager.swift:"}]},{"syntax":"swift","code":["import Foundation","import Flutter","import HUMAN","","class HumanManager {","    ","    static let shared = HumanManager()","    ","    func start() {","        do {","            let policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = .none","","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","","    func setupChannel(with controller: FlutterViewController) {","        let humanChannel = FlutterMethodChannel(name: \"com.humansecurity\/sdk\", binaryMessenger: controller.binaryMessenger)","        humanChannel.setMethodCallHandler({(call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in","            if call.method == \"humanGetHeaders\" {","                var json: String?","                do {","                    let headers = HumanSecurity.BD.headersForURLRequest(forAppId: \"<APP_ID>\")","                    let data = try JSONSerialization.data(withJSONObject: headers)","                    json = String(data: data, encoding: .utf8)","                }","                catch {","                    print(\"Error: \\(error)\")","                }","                result(json)","            }","            else if call.method == \"humanHandleResponse\" {","                if let response = call.arguments as? String, let data = response.data(using: .utf8), let httpURLResponse = HTTPURLResponse(url: URL(string: \"https:\/\/example.com\")!, statusCode: 403, httpVersion: nil, headerFields: nil) {","                    let handled = HumanSecurity.BD.handleResponse(response: httpURLResponse, data: data) { challengeResult in","                        result(challengeResult == .solved ? \"solved\" : \"cancelled\")","                    }","                    if handled {","                        return","                    }","                }","                result(\"false\")","            }","            else {","                result(\"\")","            }","        })","    }","}"],"type":"codeListing"},{"inlineContent":[{"text":"Swift \/ AppDelegate.swift:","type":"text"}],"type":"paragraph"},{"code":["import UIKit","import Flutter","","@UIApplicationMain","@objc class AppDelegate: FlutterAppDelegate {","    ","    override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        GeneratedPluginRegistrant.register(with: self)","        ","        HumanManager.shared.start()","        ","        let controller : FlutterViewController = window?.rootViewController as! FlutterViewController","        HumanManager.shared.setupChannel(with: controller)","        ","        return super.application(application, didFinishLaunchingWithOptions: launchOptions)","    }","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We start the SDK as soon as possible and on the main thread."}]}]},{"content":[{"inlineContent":[{"text":"We create a ","type":"text"},{"type":"codeVoice","code":"HSPolicy"},{"text":" instance. This object is used to configure the SDK’s behavior. Here, we set the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType"},{"text":" property to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none"},{"text":". This means that the ","type":"text"},{"inlineContent":[{"type":"text","text":"Automatic Interception"}],"type":"emphasis"},{"text":" feature of the SDK is disabled. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. However, this feature is not supported in Flutter.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" function of the SDK. We provide the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Application"},{"text":" instance (Android only).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Your AppID."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The policy object that we configured.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"orderedList"},{"inlineContent":[{"text":"Note: If your app communicates with several servers that have different AppID, you can call the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference"},{"text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK.","type":"text"}],"type":"paragraph"},{"level":2,"text":"How to add HTTP headers and handle block response","anchor":"How-to-add-HTTP-headers-and-handle-block-response","type":"heading"},{"inlineContent":[{"type":"text","text":"In your Dart code, you should do the following:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Crate a ","type":"text"},{"code":"MethodChannel","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add The SDK’s HTTP headers to your URL requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a request is blocked, send the block response to the SDK."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle the challenge’s result."}]}]}],"type":"orderedList"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Dart:"}],"type":"paragraph"},{"code":["import 'package:flutter\/material.dart';","import 'package:flutter\/services.dart';","import '..\/settings\/settings_view.dart';","import 'dart:async';","import 'dart:convert';","import 'package:http\/http.dart' as http;","","class MyView extends StatelessWidget {","  ","    static const humanPlatform = MethodChannel('com.humansecurity\/sdk');","","    Future<void> sendUrlRequest() async {","        try {","            final String humanHeaders = await humanPlatform.invokeMethod('humanGetHeaders');","            final Map<String, String> humanHeadersMap = Map.from(json.decode(humanHeaders));","            var url = Uri.https('example.com', '\/action');","            var response = await http.get(url, headers: humanHeadersMap);","            if (response.statusCode == 403) {","                final String result = await humanPlatform.invokeMethod('humanHandleResponse', response.body);","                if (result == 'solved') {","                    print(\"Challenge was solved\");","                } else if (result == 'false') {","                    print(\"Request was not blocked by HUMAN\");","                } else if (result == 'cancelled') {","                    print(\"Challenge was cancelled\");","                }","            }","        } on PlatformException catch (exception) {","            print(\"Exception: '${exception.message}'\");","        }","    }","}"],"syntax":"dart","type":"codeListing"},{"level":2,"text":"Understanding the block response","anchor":"Understanding-the-block-response","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The HUMAN’s Enforcer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:","type":"text"}]},{"code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"],"syntax":"json","type":"codeListing"}]},{"content":[{"inlineContent":[{"text":"The JSON contains metadata for the SDK.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Your app should pass the whole JSON to the SDK via the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","isActive":true},{"type":"text","text":" function. Otherwise, the SDK won’t present a challenge to the user."}],"type":"paragraph"}]}],"type":"orderedList"}]}],"kind":"article","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"title":"HSAutomaticInterceptorType.none","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","url":"\/documentation\/human\/hsautomaticinterceptortype\/none"},"https://flutter.dev/":{"titleInlineContent":[{"text":"Flutter","type":"text"}],"url":"https:\/\/flutter.dev\/","type":"link","title":"Flutter","identifier":"https:\/\/flutter.dev\/"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"HSBotDefenderChallengeResult","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","kind":"typeIdentifier"},{"text":") -> ())?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","type":"topic","navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)","kind":"symbol","title":"handleResponse(response:data:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"abstract":[],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAutomaticInterceptorType","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"interceptorType","kind":"identifier"}],"type":"topic","title":"interceptorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"kind":"symbol","title":"start(appIds:policy:)","role":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"type":"topic","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title","value":"handleResponseWithResponse:data:callback:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title","value":"interceptorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","value":[{"text":"interceptorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","value":"startWithAppIds:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","value":"startWithAppId:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}