{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"metadata":{"roleHeading":"Article","title":"gRPC Integration","modules":[{"name":"HUMAN"}],"role":"article"},"kind":"article","primaryContentSections":[{"content":[{"level":2,"text":"Intro","type":"heading","anchor":"Intro"},{"inlineContent":[{"text":"The SDK can be integrated into a ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/grpc.io\/"},{"type":"text","text":" project."}],"type":"paragraph"},{"anchor":"How-to-start-the-SDK","type":"heading","text":"How to start the SDK","level":2},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"Application","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"onCreate"},{"text":" function on Android.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"AppDelegate"},{"text":"’s ","type":"text"},{"code":"didFinishLaunchingWithOptions","type":"codeVoice"},{"text":" function on iOS.","type":"text"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should start the SDK on the "},{"inlineContent":[{"text":"main thread","type":"text"}],"type":"strong"},{"text":".","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"type":"heading","level":3,"anchor":"Android","text":"Android"},{"inlineContent":[{"type":"text","text":"Kotlin:"}],"type":"paragraph"},{"syntax":"kotlin","code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.policy.HSPolicy","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        startHumanSDK()","    }","","    private fun startHumanSDK() {","        try {","            val policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorType.NONE","","            HumanSecurity.start(this, \"<APP_ID>\", policy)","        }","        catch (exception: Exception) {","            println(\"Exception: ${exception.message}\")","        }","    }","}"],"type":"codeListing"},{"text":"iOS","type":"heading","level":3,"anchor":"iOS"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"code":["import HUMAN","","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        startHumanSDK()","        return true","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = .none","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We start the SDK as soon as possible and on the main thread."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We create a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"},{"type":"text","text":" instance. This object is used to configure the SDK’s behavior. Here, we set the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","type":"reference","isActive":true},{"type":"text","text":" property to "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true},{"type":"text","text":". This means that the "},{"type":"emphasis","inlineContent":[{"text":"Automatic Interception","type":"text"}]},{"text":" feature of the SDK is disabled. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. However, this feature is not supported in gRPC.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true},{"type":"text","text":" function of the SDK. We provide the following parameters:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Application"},{"text":" instance (Android only).","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Your AppID.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The policy object that we configured."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"inlineContent":[{"type":"text","text":"Note: If your app communicates with several servers that have different AppID, you can call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference","isActive":true},{"type":"text","text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK."}],"type":"paragraph"},{"level":2,"text":"Bot Defender integration","anchor":"Bot-Defender-integration","type":"heading"},{"text":"How to add the SDK’s HTTP headers to your URL requests and handle the blocked request","type":"heading","level":3,"anchor":"How-to-add-the-SDKs-HTTP-headers-to-your-URL-requests-and-handle-the-blocked-request"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK provides HTTP headers that should be added to your app’s URL requests. ","type":"text"},{"inlineContent":[{"type":"text","text":"It is essential that those HTTP headers will be included on every URL request"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"You "},{"type":"strong","inlineContent":[{"type":"text","text":"should not"}]},{"type":"text","text":" cache those HTTP headers. They contain a token with expiration date. The SDK manages this token to be up-to-date."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK handles the blocked request and present a challenge to the user.","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"anchor":"Android","level":4,"text":"Android","type":"heading"},{"inlineContent":[{"type":"text","text":"Kotlin:"}],"type":"paragraph"},{"syntax":"kotlin","code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun sendRequest() {","    val headers = HumanSecurity.BD.headersForURLRequest(\"<APP_ID>\")","    val metadata = Metadata()","    for ((key, value) in headers) {","        metadata.put(Metadata.Key.of(key, Metadata.ASCII_STRING_MARSHALLER), value)","    }","    \/\/ send you gRPC request with `metadata`...","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func sendUrlRequest() {","    let headers = HumanSecurity.BD.headersForURLRequest(forAppId: \"<APP_ID>\")","    var callOption = CallOptions()","    for (key, value) in headers {","        callOption.customMetadata.replaceOrAdd(name: key, value: value)","    }","    \/\/ send you gRPC request with `callOption`...","}"]},{"text":"Understanding the block response","anchor":"Understanding-the-block-response","level":2,"type":"heading"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The HUMAN’s Enforcer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:"}],"type":"paragraph"},{"syntax":"json","code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"],"type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON contains metadata for the SDK."}]}]},{"content":[{"inlineContent":[{"text":"Your app should pass the whole JSON to the SDK via the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","isActive":true,"type":"reference"},{"type":"text","text":" function. Otherwise, the SDK won’t present a challenge to the user."}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/grpc_integration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/grpc_integration"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"abstract":[{"text":"Start the SDK.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"title":"start(appIds:policy:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"abstract":[{"type":"text","text":"Start the SDK."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"startWithAppId:policy:error:","kind":"identifier"}],"title":"start(appId:policy:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"kind":"symbol","type":"topic","title":"handleResponse(response:data:callback:)","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":"?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","kind":"typeIdentifier","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"title":"HSAutomaticInterceptorType.none","url":"\/documentation\/human\/hsautomaticinterceptortype\/none"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","type":"topic","abstract":[],"title":"interceptorType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptorType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HSAutomaticInterceptorType","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType"}],"navigatorTitle":[{"kind":"identifier","text":"interceptorType"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype","role":"symbol"},"https://grpc.io/":{"identifier":"https:\/\/grpc.io\/","type":"link","url":"https:\/\/grpc.io\/","title":"gRPC","titleInlineContent":[{"text":"gRPC","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"type":"topic","kind":"symbol","title":"HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","value":"startWithAppIds:policy:error:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","op":"replace","value":"startWithAppId:policy:error:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title","value":"handleResponseWithResponse:data:callback:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}]},{"value":"HSPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"text":"HSPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"op":"replace"},{"value":"interceptorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"interceptorType"}]}]}]}