{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Bot-Defender-testing","level":2,"text":"Bot Defender testing"},{"type":"paragraph","inlineContent":[{"text":"For Bot Defender, you should simulate challenges in various screens and scenarios in your app.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"How to simulate a challenge"}]}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Open the ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/console.humansecurity.com\/botDefender\/settings\/challenge"},{"text":" in the portal.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Select the “Testing (Native Mobile)” tab."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Retrieve the VID of your device:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Using the VID Extractor","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Click on the “Find your VID” button."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enter your device’s public IP."}]}]},{"content":[{"inlineContent":[{"text":"Select the relevant session.","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Using the SDK’s API"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Use the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/vid(forAppId:)","isActive":true},{"type":"text","text":" function to get VID."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Enter the value in the VID field."}],"type":"paragraph"}]}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Insert the VID into the relevant field.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Click on the “Start testing” button."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In your app, trigger URL requests to your server. You should get a challenge. if not:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Move your app to the background"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bring it back to the foreground after few seconds."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Trigger URL requests to your server again.","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"text":"Solve (or cancel) the challenge and verify how your app behaves.","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Account-Defender-testing","level":2,"text":"Account Defender testing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Coming soon…"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App"},"abstract":[{"type":"text","text":"Testing the SDK integration in your app is essential to ensure the best experience for your users."}],"metadata":{"modules":[{"name":"HUMAN"}],"role":"article","roleHeading":"Article","title":"How to Test the SDK in Your App"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/how_to_test-the_sdk-in_your_app"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/how_to_test-the_sdk-in_your_app"]}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/vid(forAppId:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vid","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"vid(forAppId:)","abstract":[{"text":"Get the VID for given AppID.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/vid(forAppId:)","role":"symbol","kind":"symbol","url":"\/documentation\/human\/humansecurity\/vid(forappid:)","navigatorTitle":[{"text":"vidForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"https://console.humansecurity.com/botDefender/settings/challenge":{"type":"link","title":"Testing tool","titleInlineContent":[{"text":"Testing tool","type":"text"}],"url":"https:\/\/console.humansecurity.com\/botDefender\/settings\/challenge","identifier":"https:\/\/console.humansecurity.com\/botDefender\/settings\/challenge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1vid(forAppId:)\/title","value":"vidForAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1vid(forAppId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"vidForAppId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}