{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App"},"metadata":{"roleHeading":"Article","title":"How to Verify the SDK Integration in Your App","modules":[{"name":"HUMAN"}],"role":"article"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"kind":"article","primaryContentSections":[{"content":[{"text":"Intro","anchor":"Intro","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK comes with an integration verification tool - “Doctor App”. This is a tool that helps verify the SDK integration in your project by simulating a typical user flow in the application. When the “Doctor App” is enabled, a pop up will appear as part of the app flow and guide the developer to simulate a user flow in order to gather the required information for testing the integration."}]},{"text":"Android","level":3,"type":"heading","anchor":"Android"},{"type":"paragraph","inlineContent":[{"text":"The “Doctor App” includes assets that are used for the UI. Those assets are required only for the “Doctor App” usage and are not needed in your app production build. In order minimize the SDK footprint, those assets are loaded dynamically in run time.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you run the “Doctor App”, those assets will be loaded automatically (internet connection is required)."}]},{"type":"heading","level":3,"text":"iOS","anchor":"iOS"},{"type":"paragraph","inlineContent":[{"text":"The “Doctor App” includes assets that are used for the UI. Those assets are required only for the “Doctor App” usage and are not needed in your app production build. In order minimize the SDK footprint, those assets are loaded dynamically in run time. If you run the “Doctor App” on a real device with iOS 14 or above, those assets will be loaded automatically (internet connection is required). ","type":"text"},{"inlineContent":[{"text":"However, if you run the “Doctor App” on a simulator or on a real device with iOS 13 or less, you will need to add the ","type":"text"},{"code":"HUMAN.bundle","type":"codeVoice"},{"text":" file to your project.","type":"text"}],"type":"strong"},{"text":" It is important to remember to remove it from your project before you build and deploy your app to production.","type":"text"}]},{"inlineContent":[{"type":"text","text":"You can get the "},{"code":"HUMAN.bundle","type":"codeVoice"},{"type":"text","text":" by running the following command in the Terminal (please refer to the relevant SDK version):"}],"type":"paragraph"},{"syntax":null,"code":["    curl -LO https:\/\/perimeterx.jfrog.io\/artifactory\/files\/doctor-app-assets\/ios\/2.1\/HUMAN.bundle.zip"],"type":"codeListing"},{"inlineContent":[{"inlineContent":[{"text":"How to add the ","type":"text"},{"type":"codeVoice","code":"HUMAN.bundle"},{"type":"text","text":" file to your project"}],"type":"strong"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Download the "},{"type":"codeVoice","code":"HUMAN.bundle.zip"},{"type":"text","text":" file from the link above."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unzip it and drag the "},{"code":"HUMAN.bundle","type":"codeVoice"},{"type":"text","text":" file to your project (make sure to link it to relevant targets)."}]}]}],"type":"orderedList"},{"level":2,"type":"heading","text":"The Doctor App’s flow","anchor":"The-Doctor-Apps-flow"},{"items":[{"content":[{"inlineContent":[{"text":"Start the SDK with the “Doctor App” enabled. You can enabled it by setting the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","type":"reference"},{"text":" to be ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" when initiating the SDK."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Android:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Kotlin:","type":"text"}]},{"code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.HSPolicy","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        startHumanSDK()","    }","","    private fun startHumanSDK() {","        try {","            val policy = HSPolicy()","            policy.doctorAppPolicy.enabled = true","","            HumanSecurity.start(this, \"<APP_ID>\", null, policy)","        }","        catch (exception: Exception) {","            println(\"Exception: ${exception.message}\")","        }","    }","}"],"type":"codeListing","syntax":"kotlin"},{"type":"paragraph","inlineContent":[{"text":"Java:","type":"text"}]},{"code":["import android.app.Application;","import android.util.Log;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.HSPolicy;","","public class MainApplication extends Application {","","    @Override","    public void onCreate() {","        super.onCreate();","        startHumanSDK();","    }","","    void startHumanSDK() {","        try {","            HSPolicy policy = new HSPolicy();","            policy.getDoctorAppPolicy().setEnabled(true);","","            HumanSecurity.INSTANCE.start(this, \"<APP_ID>\", null, policy);","        }","        catch (Exception exception) {","            Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","        }","    }","}"],"type":"codeListing","syntax":"java"}]},{"content":[{"inlineContent":[{"text":"iOS:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Swift:","type":"text"}],"type":"paragraph"},{"code":["import HUMAN","","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        startHumanSDK()","        return true","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            policy.doctorAppPolicy.enabled = true","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", delegate: nil, policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Objective-C:","type":"text"}]},{"code":["@import HUMAN;","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","    [self startHumanSDK];","    return YES;","}","","- (void)startHumanSDK() {","    HSPolicy *policy = [[HSPolicy alloc] init];","    policy.doctorAppPolicy.enabled = YES;","","    NSError *error = nil;","    [HumanSecurity startWithAppId:@\"<APP_ID>\" delegate:nil policy:policy error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"],"syntax":"objc","type":"codeListing"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Run your app. You should see the “Doctor App” UI shown."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Welcome screen"}]},{"type":"text","text":" - In this screen you select whether to start a new test or load the summary of a previous test, if one exists."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"doctor_app_integration_pic1"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Product Selection screen","type":"text"}]},{"text":" - In this screen you select which product to test:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Bot Defender","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Account Defender"}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"identifier":"doctor_app_integration_pic2","type":"image"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Instruction screen"}]},{"type":"text","text":" - In this screen you get a detailed explanation on how to start a new test, what is expected to happen and what you can do in case someting is wrong."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"identifier":"doctor_app_integration_pic3","type":"image"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Test selection screen"}],"type":"strong"},{"text":" - In this screen you can select between two different types of tests:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Native app framework - to test your native URL requests."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Web view framework - to test your web view URL requests.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"doctor_app_integration_pic4"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Run the test","type":"text"}],"type":"strong"},{"type":"text","text":" - use your app according the instruction."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Summary screen"}],"type":"strong"},{"type":"text","text":" - In this screen you review the test results. You can go into details regarding each test and get troubleshooting tips in case a test failed, to help you analyze what is causing this issue."}]},{"inlineContent":[{"identifier":"doctor_app_integration_pic5","type":"image"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In the summary screen you can export the test result to a JSON string. You can send it to our support team if you encounter an unresolved issue."}]}]},{"content":[{"inlineContent":[{"text":"When you exit the “Doctor App”, ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"your app is also terminated"}]},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that retrying blocked request after the challenge was solved will not work while running the “Doctor App”. In this case, your request handler should get the “challenge was solved” error."}]},{"type":"paragraph","inlineContent":[{"text":"Don’t forget to switch the the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","type":"reference","isActive":true},{"type":"text","text":" to be "},{"code":"false","type":"codeVoice"},{"type":"text","text":" when you finish validating the SDK integration."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/how_to_verify_the_sdk_integration_in_your_app"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/how_to_verify_the_sdk_integration_in_your_app"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doctor_app_integration_pic5":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/doctor_app_integration_pic5.png"}],"type":"image","identifier":"doctor_app_integration_pic5"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/enabled":{"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","kind":"symbol","role":"symbol","title":"enabled","url":"\/documentation\/human\/hsdoctorapppolicy\/enabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Set this property to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable the "},{"code":"Doctor App","type":"codeVoice"},{"type":"text","text":" - a tool to verify the integration of the SDK in your app. Make sure to set this property to "},{"type":"codeVoice","code":"false"},{"text":" before deploying you app to production. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}]},"doctor_app_integration_pic1":{"alt":null,"identifier":"doctor_app_integration_pic1","variants":[{"traits":["1x","light"],"url":"\/images\/doctor_app_integration_pic1.png"}],"type":"image"},"doctor_app_integration_pic2":{"alt":null,"variants":[{"url":"\/images\/doctor_app_integration_pic2.png","traits":["1x","light"]}],"type":"image","identifier":"doctor_app_integration_pic2"},"doctor_app_integration_pic3":{"alt":null,"identifier":"doctor_app_integration_pic3","variants":[{"url":"\/images\/doctor_app_integration_pic3.png","traits":["1x","light"]}],"type":"image"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doctor_app_integration_pic4":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/doctor_app_integration_pic4.png"}],"type":"image","identifier":"doctor_app_integration_pic4"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/title","value":"enabled"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/fragments","value":[{"kind":"identifier","text":"enabled"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}