{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"How to upgrade from v3","roleHeading":"Article","role":"article","modules":[{"name":"HUMAN"}]},"kind":"article","abstract":[{"text":"There are few major changes in the SDK’s API. In this article we will cover all of them.","type":"text"}],"primaryContentSections":[{"content":[{"level":2,"text":"Bye bye PerimeterX… Hello HumanSecurity","type":"heading","anchor":"Bye-bye-PerimeterX-Hello-HumanSecurity"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK name was changed from PerimeterX to HUMAN"},{"type":"text","text":" "},{"type":"text","text":"Android: "},{"type":"codeVoice","code":"import com.humansecurity.mobile_sdk.HumanSecurity"},{"type":"text","text":" "},{"type":"text","text":"iOS: "},{"type":"codeVoice","code":"import HUMAN"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"In Android you should change your "},{"type":"codeVoice","code":"build.gradle"},{"type":"text","text":" file to you the new SDK repo location: https:\/\/jfrog.humansecurity.com\/artifactory\/human-android-sdk\/"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The main class was renamed from ","type":"text"},{"code":"PerimeterX","type":"codeVoice"},{"text":" to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","type":"reference"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"All SDK’s classes now have "},{"type":"codeVoice","code":"HS"},{"type":"text","text":" as a prefix to their name instead of "},{"type":"codeVoice","code":"PX"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Some functions in ","type":"text"},{"code":"PerimeterX","type":"codeVoice"},{"text":" were moved to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","isActive":true},{"text":" classes according to their context.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"PerimeterXDelegate"},{"type":"text","text":" has been renamed to "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","isActive":true},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Error query functions were combined into ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)","isActive":true,"type":"reference"},{"text":" function.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Android’s "},{"type":"codeVoice","code":"HSTimeoutInterceptor"},{"type":"text","text":" class was removed, you can set the different timeouts directly in the okHttp client config."}],"type":"paragraph"}]}]},{"level":2,"text":"The policy","type":"heading","anchor":"The-policy"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Previously the policy object was a one-level object that includes all SDK’s configurations.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Now the policy object includes the following objects:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"},{"type":"text","text":" - “Automatic Interceptor” configurations."}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","isActive":true,"type":"reference"},{"text":" = “Hybrid App” configurations.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","isActive":true},{"type":"text","text":" - Configurations regarding the SDK’s detection."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","isActive":true,"type":"reference"},{"type":"text","text":" - “Doctor App” configurations."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Previously you had to set your server(s) domain(s) for both the “Automatic Interceptor” and “Hybrid App”. Now, there are two different functions for each of them.","type":"text"}],"type":"paragraph"}]}]},{"level":2,"text":"Bot Defender","type":"heading","anchor":"Bot-Defender"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Previously the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)"},{"type":"text","text":" function returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"null"},{"type":"text","text":" when you call it before calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"type":"text","text":" function."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Now this function will always return a value (not empty). However, It’s mandatory to call it "},{"type":"strong","inlineContent":[{"type":"text","text":"after"}]},{"type":"text","text":" calling the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true},{"type":"text","text":" function."}]}]}]},{"level":2,"text":"Hybrid App","type":"heading","anchor":"Hybrid-App"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"In order to enable “Hybrid App”, you should call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"},{"text":" function. Notice that you should set the ","type":"text"},{"type":"strong","inlineContent":[{"text":"web root domain","type":"text"}]},{"text":" (","type":"text"},{"code":".example.com","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}]}]},{"level":3,"text":"New in iOS","type":"heading","anchor":"New-in-iOS"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true,"type":"reference"},{"text":" function allows to do the “Hybrid App” integration manually, unlike the automatic way that was only available in previous versions.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","type":"reference"},{"text":" is an option to enable the same “Hybrid App” automatic integration that was available in previous versions.","type":"text"}],"type":"paragraph"}]}]},{"level":2,"text":"Environment","type":"heading","anchor":"Environment"},{"level":3,"text":"Android","type":"heading","anchor":"Android"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The SDK is now built for API 34 and Kotlin 2.0.0."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK has a new list of dependencies (see bellow). When fetching the SDK from our artifactory, those dependencies are automatically included. However, if you need to change the version of some dependencies, you may integrate the SDK manually and select the exact version that works for your app.","type":"text"}]},{"syntax":"groovy","type":"codeListing","code":["implementation 'androidx.core:core-ktx:1.13.1' \/\/ any version (select 1.10.1 if your app targets API 33)","implementation 'androidx.lifecycle:lifecycle-process:2.8.2' \/\/ min v2.6.0","implementation 'androidx.datastore:datastore-preferences:1.1.1' \/\/ any version (select 1.0.0 if your app targets API 33)","implementation 'com.google.android.material:material:1.12.0' \/\/ min v1.6.0","implementation 'com.fasterxml.uuid:java-uuid-generator:4.3.0' \/\/ min v3.0.0","implementation 'io.ktor:ktor-client-okhttp:2.3.11' \/\/ min v2.2.1"]}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/how_to_upgrade_from_v3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/how_to_upgrade_from_v3"]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/set(webRootDomains:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)","abstract":[{"text":"The SDK is setting cookies in your web views in order to sync between the native and the web sessions. For that, the SDK has to know you website’s root domain for the HTTP cookie (e.g “.example.com”). Those domains can be set in the HUMAN’s Portal, however, it recommended to set them directly in the SDK’s policy.","type":"text"}],"url":"\/documentation\/human\/hshybridapppolicy\/set(webrootdomains:forappid:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webRootDomains"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"set(webRootDomains:forAppId:)","navigatorTitle":[{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}],"role":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Hybrid App support."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSHybridAppPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"title":"setupWebView(webView:navigationDelegate:)","navigatorTitle":[{"kind":"identifier","text":"setupWebViewWithWebView:navigationDelegate:"}],"abstract":[{"text":"Setup the web view to be synced with SDK. Do not set a ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":" to the web view after calling this function.","type":"text"},{"text":" ","type":"text"},{"text":"If you wish to set a web view client, call this function again with the new ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":". You should not call this method when the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupWebView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"navigationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationDelegate","preciseIdentifier":"c:objc(pl)WKNavigationDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"url":"\/documentation\/human\/hsbotdefendererrortype","type":"topic","kind":"symbol","title":"HSBotDefenderErrorType","navigatorTitle":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","abstract":[],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","type":"topic","title":"HumanSecurity","url":"\/documentation\/human\/humansecurity","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}],"abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"kind":"symbol","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","title":"start(appId:policy:)","role":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/headersForURLRequest(forAppId:)":{"navigatorTitle":[{"kind":"identifier","text":"headersForURLRequestForAppId:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","url":"\/documentation\/human\/hsbotdefender\/headersforurlrequest(forappid:)","kind":"symbol","abstract":[{"type":"text","text":"Returns HTTP headers that should be added to the URL request."}],"title":"headersForURLRequest(forAppId:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"headersForURLRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/errorType(error:)":{"navigatorTitle":[{"text":"errorTypeWithError:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)","kind":"symbol","title":"errorType(error:)","url":"\/documentation\/human\/hsbotdefender\/errortype(error:)","role":"symbol","abstract":[{"type":"text","text":"Returns the relevant "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","isActive":true},{"type":"text","text":" of the given error. If the error is not related, this function will return "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","isActive":true},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType","text":"HSBotDefenderErrorType","kind":"typeIdentifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","role":"symbol","abstract":[{"type":"text","text":"When this property is "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the SDK detects all "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true},{"type":"text","text":" function. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticSetup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup","title":"automaticSetup","navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"navigatorTitle":[{"kind":"identifier","text":"HSAccountDefender"}],"title":"HSAccountDefender","kind":"symbol","type":"topic","url":"\/documentation\/human\/hsaccountdefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAccountDefender"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSDoctorAppPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"title":"HSDoctorAppPolicy","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","url":"\/documentation\/human\/hsdoctorapppolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Doctor App."}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"title":"HSBotDefender","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","kind":"symbol","url":"\/documentation\/human\/hsbotdefender","navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","title":"HSAutomaticInterceptorPolicy","abstract":[{"text":"The policy that define the behaviour of the Automatic Interceptor.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/unknown":{"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","url":"\/documentation\/human\/hsbotdefendererrortype\/unknown","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorTypeUnknown"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"kind":"symbol","title":"HSBotDefenderErrorType.unknown","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","kind":"symbol","title":"HSBotDefenderDelegate"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"url":"\/documentation\/human\/hsdetectionpolicy","type":"topic","role":"symbol","navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","kind":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK’s detection."}],"title":"HSDetectionPolicy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"setWithWebRootDomains:forAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/fragments"},{"op":"replace","value":"HSHybridAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title"},{"op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle"},{"op":"replace","value":"setupWebViewWithWebView:navigationDelegate:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments"},{"op":"replace","value":"HSBotDefenderErrorType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle"},{"op":"replace","value":"HumanSecurity","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title"},{"op":"replace","value":[{"text":"HumanSecurity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments"},{"op":"replace","value":[{"text":"HumanSecurity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle"},{"op":"replace","value":"startWithAppId:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments"},{"op":"replace","value":"headersForURLRequestForAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"headersForURLRequestForAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/fragments"},{"op":"replace","value":"errorTypeWithError:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorTypeWithError:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/fragments"},{"op":"replace","value":"automaticSetup","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title"},{"op":"replace","value":[{"text":"automaticSetup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments"},{"op":"replace","value":"HSAccountDefender","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title"},{"op":"replace","value":[{"text":"HSAccountDefender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSAccountDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle"},{"op":"replace","value":"HSDoctorAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments"},{"op":"replace","value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle"},{"op":"replace","value":"HSBotDefender","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title"},{"op":"replace","value":[{"text":"HSBotDefender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle"},{"op":"replace","value":"HSAutomaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title"},{"op":"replace","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle"},{"op":"replace","value":"HSBotDefenderErrorTypeUnknown","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/title"},{"op":"replace","value":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/fragments"},{"op":"replace","value":"HSBotDefenderDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments"},{"op":"replace","value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle"},{"op":"replace","value":"HSDetectionPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title"},{"op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments"},{"op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle"}]}]}