{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAccountDefender","kind":"identifier"}]}]},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"sections":[],"variants":[{"paths":["\/documentation\/human\/hsaccountdefender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsaccountdefender"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSAccountDefender","role":"symbol","title":"HSAccountDefender","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAccountDefender","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HSAccountDefender"}],"roleHeading":"Class","modules":[{"name":"HUMAN"}]},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setUserId(userId:forAppId:)"],"anchor":"Instance-Methods"}],"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/registerOutgoingUrlRequest(url:forAppId:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerOutgoingUrlRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Provide outgoing URL request to the Account Defender feature."}],"url":"\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)","title":"registerOutgoingUrlRequest(url:forAppId:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","navigatorTitle":[{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"kind":"symbol","role":"symbol","url":"\/documentation\/human\/hsaccountdefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSAccountDefender"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSAccountDefender"}],"title":"HSAccountDefender"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"abstract":[{"type":"text","text":"There are few major changes in the SDK’s API. In this article we will cover all of them."}],"url":"\/documentation\/human\/how_to_upgrade_from_v3","role":"article","title":"How to upgrade from v3","kind":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"kind":"symbol","title":"setAdditionalData(parameters:forAppId:)","url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","navigatorTitle":[{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdditionalData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","type":"topic","abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setUserId(userId:forAppId:)":{"type":"topic","role":"symbol","title":"setUserId(userId:forAppId:)","kind":"symbol","url":"\/documentation\/human\/hsaccountdefender\/setuserid(userid:forappid:)","abstract":[{"type":"text","text":"Calling this method with non-"},{"code":"null","type":"codeVoice"},{"text":" ","type":"text"},{"code":"userId","type":"codeVoice"},{"text":" will start the Account Defender feature.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setUserId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"setUserIdWithUserId:forAppId:error:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setUserId(userId:forAppId:)"},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HSAccountDefender","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HSAccountDefender","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"HSAccountDefender"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setUserId(userId:forAppId:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"HSAccountDefender","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/fragments"},{"op":"replace","value":"HSAccountDefender","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSAccountDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSAccountDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle"},{"op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments"},{"op":"replace","value":"setUserIdWithUserId:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setUserId(userId:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserIdWithUserId:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setUserId(userId:forAppId:)\/fragments"}]}]}