{"sections":[],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"]}],"metadata":{"roleHeading":"Class","title":"HSAutomaticInterceptorPolicy","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"symbolKind":"class","role":"symbol","modules":[{"name":"HUMAN"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/set(interceptedDomains:forAppId:)"]},{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionDelegate","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionQueueDelegate","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"},"abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"references":{"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptAndRetryRequest":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptandretryrequest","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true},{"type":"text","text":". When the challenge is solved, the SDK will send the original request one more time. Your request’s handler should receive the response from your server without knowing that the request was blocked and sent again. You should note that when the challenge is cancelled or when the second request is also blocked, then the behavior will be the same as the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true},{"type":"text","text":". In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptAndRetryRequest","kind":"identifier"}],"title":"HSAutomaticInterceptorType.interceptAndRetryRequest","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/init","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/init","title":"init","type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionDelegate":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionDelegate","role":"symbol","navigatorTitle":[{"text":"urlSessionDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"},{"text":"?","kind":"text"}],"title":"urlSessionDelegate","abstract":[{"text":"The ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" (the SDK will be the delegate). The SDK implements ","type":"text"},{"code":"willPerformHTTPRedirection","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"needNewBodyStream","type":"codeVoice"},{"text":" function in the ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":". However, if your ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":" implements other functions, like ","type":"text"},{"code":"didReceiveChallenge","type":"codeVoice"},{"text":", then you should provide your own delegate.","type":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessiondelegate","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/copy(with:)":{"title":"copy(with:)","kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/copy(with:)","role":"symbol","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/copy(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionConfiguration":{"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionConfiguration"},{"type":"text","text":" that should be used by the SDK. Default is "},{"type":"codeVoice","code":"URLSessionConfiguration.default"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"}],"title":"urlSessionConfiguration","navigatorTitle":[{"text":"urlSessionConfiguration","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptorType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType","text":"HSAutomaticInterceptorType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"interceptorType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","kind":"symbol","title":"interceptorType","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionQueueDelegate":{"role":"symbol","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionqueuedelegate","navigatorTitle":[{"kind":"identifier","text":"urlSessionQueueDelegate"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionQueueDelegate","title":"urlSessionQueueDelegate","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OperationQueue"},{"type":"text","text":" that should be used by the SDK."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionQueueDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue"},{"kind":"text","text":"?"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptWithDelayedResponse":{"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","title":"HSAutomaticInterceptorType.interceptWithDelayedResponse","abstract":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept"},{"type":"text","text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/set(interceptedDomains:forAppId:)":{"role":"symbol","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/set(intercepteddomains:forappid:)","navigatorTitle":[{"text":"setWithInterceptedDomains:forAppId:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/set(interceptedDomains:forAppId:)","kind":"symbol","title":"set(interceptedDomains:forAppId:)","abstract":[{"text":"Use this function to register domains which your app interact with. The SDK (when the ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/urlRequestInterceptionType","type":"codeVoice"},{"text":" is set to any value rather than ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/none","type":"codeVoice"},{"text":") intercepts URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. If you are using more than one AppID setting the domains is required. For example: “example.com”.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"interceptedDomains"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","title":"HSAutomaticInterceptorPolicy","abstract":[{"text":"The policy that define the behaviour of the Automatic Interceptor.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject","title":"NSObject"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionRequestTimeout":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"timeoutInterval","type":"codeVoice"},{"text":" that you would like to set for the URLRequest when using ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true,"type":"reference"},{"text":"  or ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"In those cases you would need to set the timeout of the request to 0 in order to enable the request to return only after the challenge is completed when blocked, without getting a time out error,","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"urlSessionRequestTimeout","type":"codeVoice"},{"text":" will allow you to set the required timeout for the actual request, the default will be set to 60 as the default timeout for URLRequest.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionRequestTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","role":"symbol","title":"urlSessionRequestTimeout","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionrequesttimeout","navigatorTitle":[{"kind":"identifier","text":"urlSessionRequestTimeout"}]},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HSAutomaticInterceptorPolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/init","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/set(interceptedDomains:forAppId:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionDelegate","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionQueueDelegate","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout"],"generated":true,"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"],"kind":"relationships","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/title","value":"HSAutomaticInterceptorTypeInterceptAndRetryRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionDelegate\/title","value":"urlSessionDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionDelegate\/fragments","value":[{"kind":"identifier","text":"urlSessionDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1copy(with:)\/title","value":"copyWithZone:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1copy(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/title","value":"urlSessionConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/fragments","value":[{"text":"urlSessionConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title","value":"interceptorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","value":[{"kind":"identifier","text":"interceptorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionQueueDelegate\/title","value":"urlSessionQueueDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionQueueDelegate\/fragments","value":[{"text":"urlSessionQueueDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/title","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/fragments","value":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1set(interceptedDomains:forAppId:)\/title","value":"setWithInterceptedDomains:forAppId:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1set(interceptedDomains:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithInterceptedDomains:forAppId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title","value":"HSAutomaticInterceptorPolicy","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/title","value":"urlSessionRequestTimeout","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/fragments","value":[{"kind":"identifier","text":"urlSessionRequestTimeout"}],"op":"replace"}]}]}