{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"externalID":"c:@M@HUMAN@E@HSAutomaticInterceptorType","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"symbolKind":"enum","title":"HSAutomaticInterceptorType","roleHeading":"Enumeration"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype"]}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/RawRepresentable-Implementations"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptWithDelayedResponse":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptWithDelayedResponse"}],"title":"HSAutomaticInterceptorType.interceptWithDelayedResponse","abstract":[{"type":"text","text":"Same as "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept"},{"type":"text","text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse"},"doc://com.perimeterx.mobile-sdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptAndRetryRequest":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptandretryrequest","abstract":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true},{"text":". When the challenge is solved, the SDK will send the original request one more time. Your request’s handler should receive the response from your server without knowing that the request was blocked and sent again. You should note that when the challenge is cancelled or when the second request is also blocked, then the behavior will be the same as the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true},{"text":". In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled.","type":"text"}],"role":"symbol","title":"HSAutomaticInterceptorType.interceptAndRetryRequest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptAndRetryRequest"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"url":"\/documentation\/human\/hsautomaticinterceptortype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","navigatorTitle":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"role":"symbol","type":"topic","title":"HSAutomaticInterceptorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/rawrepresentable-implementations"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","title":"HSAutomaticInterceptorType.none","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/none","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/init(rawvalue:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/init(rawValue:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/Equatable-Implementations":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/Equatable-Implementations","type":"topic","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"title":"HSAutomaticInterceptorType.intercept","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HSAutomaticInterceptorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/title","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/title","value":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","value":"HSAutomaticInterceptorTypeIntercept"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","value":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}]}]}]}