{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefender"}],"symbolKind":"class","externalID":"c:@M@HUMAN@objc(cs)HSBotDefender","title":"HSBotDefender","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"HUMAN"}]},"sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/delegate"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/canHandleResponse(response:data:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/challengeReferenceId()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)"],"title":"Instance Methods","generated":true}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefender"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefender"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/setCustomParameters(parameters:forAppId:)":{"kind":"symbol","title":"setCustomParameters(parameters:forAppId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomParameters"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefender\/setcustomparameters(parameters:forappid:)","abstract":[{"text":"Set custom parameters for given AppID.","type":"text"}],"navigatorTitle":[{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"kind":"symbol","type":"topic","title":"handleResponse(response:data:callback:)","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":"?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","kind":"typeIdentifier","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/unknown":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"title":"HSBotDefenderErrorType.unknown","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","navigatorTitle":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefendererrortype\/unknown","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/canHandleResponse(response:data:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"canHandleResponseWithResponse:data:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canHandleResponse"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/human\/hsbotdefender\/canhandleresponse(response:data:)","role":"symbol","abstract":[{"type":"text","text":"This function checks if the SDK can handle the URL request’s response and presents the block screen."}],"title":"canHandleResponse(response:data:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/canHandleResponse(response:data:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/errorType(error:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)","title":"errorType(error:)","url":"\/documentation\/human\/hsbotdefender\/errortype(error:)","abstract":[{"text":"Returns the relevant ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"},{"type":"text","text":" of the given error. If the error is not related, this function will return "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","isActive":true},{"text":".","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"text":"HSBotDefenderErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"errorTypeWithError:"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"type":"topic","kind":"symbol","title":"HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/headersForURLRequest(forAppId:)":{"role":"symbol","title":"headersForURLRequest(forAppId:)","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"headersForURLRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Returns HTTP headers that should be added to the URL request."}],"url":"\/documentation\/human\/hsbotdefender\/headersforurlrequest(forappid:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"headersForURLRequestForAppId:"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"HSBotDefenderDelegate","preciseIdentifier":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/human\/hsbotdefender\/delegate","role":"symbol","title":"delegate"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/challengeReferenceId()":{"abstract":[{"text":"Returns the challenge’s Reference ID. This value will appear in the challenge screen.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeReferenceId"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/challengeReferenceId()","url":"\/documentation\/human\/hsbotdefender\/challengereferenceid()","title":"challengeReferenceId()","kind":"symbol","navigatorTitle":[{"text":"challengeReferenceId","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"type":"topic","url":"\/documentation\/human\/hsbotdefender","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefender"}],"role":"symbol","title":"HSBotDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSBotDefender"}]},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"role":"symbol","title":"HSBotDefenderErrorType","url":"\/documentation\/human\/hsbotdefendererrortype","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"HSBotDefender","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"HSBotDefender"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/delegate"],"generated":true,"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/canHandleResponse(response:data:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/challengeReferenceId()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/errorType(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSBotDefender"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/title","value":"setCustomParametersWithParameters:forAppId:error:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title","value":"handleResponseWithResponse:data:callback:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}]},{"value":"HSBotDefenderErrorTypeUnknown","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderErrorTypeUnknown"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1canHandleResponse(response:data:)\/title","op":"replace","value":"canHandleResponseWithResponse:data:"},{"value":[{"text":"- ","kind":"text"},{"text":"canHandleResponseWithResponse:data:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1canHandleResponse(response:data:)\/fragments","op":"replace"},{"value":"errorTypeWithError:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorTypeWithError:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1errorType(error:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/title","value":"headersForURLRequestForAppId:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1challengeReferenceId()\/title","value":"challengeReferenceId"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1challengeReferenceId()\/fragments","value":[{"kind":"text","text":"- "},{"text":"challengeReferenceId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","value":"HSBotDefender","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"kind":"identifier","text":"HSBotDefender"}],"op":"replace"},{"value":[{"kind":"identifier","text":"HSBotDefender"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle","op":"replace"},{"value":"HSBotDefenderErrorType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"op":"replace"}]}]}