{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefendererrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefendererrortype"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}],"modules":[{"name":"HUMAN"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HSBotDefenderErrorType","title":"HSBotDefenderErrorType","role":"symbol","symbolKind":"enum"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"title":"Conforms To"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/requestWasBlocked":{"url":"\/documentation\/human\/hsbotdefendererrortype\/requestwasblocked","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestWasBlocked","kind":"identifier"}],"navigatorTitle":[{"text":"HSBotDefenderErrorTypeRequestWasBlocked","kind":"identifier"}],"title":"HSBotDefenderErrorType.requestWasBlocked","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/requestWasBlocked","abstract":[]},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable"},"doc://com.perimeterx.mobile-sdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","title":"Swift.RawRepresentable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/challengeWasCancelled":{"url":"\/documentation\/human\/hsbotdefendererrortype\/challengewascancelled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeWasCancelled","kind":"identifier"}],"navigatorTitle":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}],"title":"HSBotDefenderErrorType.challengeWasCancelled","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasCancelled","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/RawRepresentable-Implementations":{"url":"\/documentation\/human\/hsbotdefendererrortype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/RawRepresentable-Implementations","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/challengeWasSolved":{"title":"HSBotDefenderErrorType.challengeWasSolved","role":"symbol","type":"topic","url":"\/documentation\/human\/hsbotdefendererrortype\/challengewassolved","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeWasSolved","kind":"identifier"}],"navigatorTitle":[{"text":"HSBotDefenderErrorTypeChallengeWasSolved","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasSolved"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/init(rawValue:)":{"url":"\/documentation\/human\/hsbotdefendererrortype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/init(rawValue:)","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/unknown":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown","type":"topic","title":"HSBotDefenderErrorType.unknown","url":"\/documentation\/human\/hsbotdefendererrortype\/unknown"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"url":"\/documentation\/human\/hsbotdefendererrortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","kind":"symbol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"title":"HSBotDefenderErrorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/Equatable-Implementations":{"url":"\/documentation\/human\/hsbotdefendererrortype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/Equatable-Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"HSBotDefenderErrorType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/unknown"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1requestWasBlocked\/title","op":"replace","value":"HSBotDefenderErrorTypeRequestWasBlocked"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1requestWasBlocked\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorTypeRequestWasBlocked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasCancelled\/title","op":"replace","value":"HSBotDefenderErrorTypeChallengeWasCancelled"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasCancelled\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasSolved\/title","op":"replace","value":"HSBotDefenderErrorTypeChallengeWasSolved"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasSolved\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorTypeChallengeWasSolved","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/title","op":"replace","value":"HSBotDefenderErrorTypeUnknown"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1unknown\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorTypeUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","op":"replace","value":"HSBotDefenderErrorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]}]}]}