{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"metadata":{"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"title":"HSBotDefenderChallengeResult","symbolKind":"enum","externalID":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","modules":[{"name":"HUMAN"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/solved"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"role":"symbol","abstract":[],"type":"topic","title":"HSBotDefenderChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","url":"\/documentation\/human\/hsbotdefenderchallengeresult","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/cancelled":{"role":"symbol","title":"HSBotDefenderChallengeResult.cancelled","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/cancelled","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResultCancelled"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/Equatable-Implementations","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/equatable-implementations","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/RawRepresentable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/human\/hsbotdefenderchallengeresult\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/RawRepresentable-Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/init(rawValue:)":{"role":"symbol","abstract":[],"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/solved":{"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/solved","kind":"symbol","title":"HSBotDefenderChallengeResult.solved","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/solved","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solved","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HSBotDefenderChallengeResult","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/solved"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HSBotDefenderChallengeResult","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title"},{"value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments"},{"value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle"},{"value":"HSBotDefenderChallengeResultCancelled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1cancelled\/title"},{"value":[{"kind":"identifier","text":"HSBotDefenderChallengeResultCancelled"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1cancelled\/fragments"},{"value":"HSBotDefenderChallengeResultSolved","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1solved\/title"},{"value":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1solved\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}