{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRenderFailed(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRendered(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderDidUpdateHeaders(headers:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderRequestBlocked(url:appId:)"],"anchor":"Instance-Methods"}],"metadata":{"externalID":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate","role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderDelegate"}],"navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"HSBotDefenderDelegate"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"abstract":[{"type":"text","text":"There are few major changes in the SDK’s API. In this article we will cover all of them."}],"url":"\/documentation\/human\/how_to_upgrade_from_v3","role":"article","title":"How to upgrade from v3","kind":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeCancelled(forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeCancelled(forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengecancelled(forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeCancelled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"botDefenderChallengeCancelledForAppId:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Called when the challenge was cancelled.","type":"text"}],"title":"botDefenderChallengeCancelled(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeRendered(forAppId:)":{"kind":"symbol","title":"botDefenderChallengeRendered(forAppId:)","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerendered(forappid:)","navigatorTitle":[{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeRendered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRendered(forAppId:)","type":"topic","abstract":[{"type":"text","text":"Called when the challenge was render successfully."}]},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeRenderFailed(forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRenderFailed(forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerenderfailed(forappid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"botDefenderChallengeRenderFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"botDefenderChallengeRenderFailedForAppId:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Called when the challenge was failed to render."}],"title":"botDefenderChallengeRenderFailed(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/headersForURLRequest(forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefender\/headersforurlrequest(forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headersForURLRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Returns HTTP headers that should be added to the URL request."}],"title":"headersForURLRequest(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderDidUpdateHeaders(headers:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderDidUpdateHeaders(headers:forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderdidupdateheaders(headers:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderDidUpdateHeaders","kind":"identifier"},{"text":"(","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)"},{"text":" function for every URL request.","type":"text"}],"title":"botDefenderDidUpdateHeaders(headers:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderRequestBlocked(url:appId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderRequestBlocked(url:appId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderrequestblocked(url:appid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"botDefenderRequestBlocked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"botDefenderRequestBlockedWithUrl:appId:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Called when a request was blocked."}],"title":"botDefenderRequestBlocked(url:appId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeSolved(forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeSolved(forAppId:)","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengesolved(forappid:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"botDefenderChallengeSolved"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"botDefenderChallengeSolvedForAppId:"}],"type":"topic","abstract":[{"type":"text","text":"Called when the challenge was solved."}],"title":"botDefenderChallengeSolved(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","role":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"type":"topic","abstract":[],"title":"HSBotDefenderDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HSBotDefenderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRenderFailed(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRendered(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderDidUpdateHeaders(headers:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderRequestBlocked(url:appId:)"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeCancelled(forAppId:)\/title","value":"botDefenderChallengeCancelledForAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeCancelled(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderChallengeCancelledForAppId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRendered(forAppId:)\/title","value":"botDefenderChallengeRenderedForAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRendered(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderChallengeRenderedForAppId:"}]},{"value":"botDefenderChallengeRenderFailedForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRenderFailed(forAppId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"botDefenderChallengeRenderFailedForAppId:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRenderFailed(forAppId:)\/fragments"},{"value":"headersForURLRequestForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderDidUpdateHeaders(headers:forAppId:)\/title","value":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderDidUpdateHeaders(headers:forAppId:)\/fragments"},{"value":"botDefenderRequestBlockedWithUrl:appId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderRequestBlocked(url:appId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"botDefenderRequestBlockedWithUrl:appId:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderRequestBlocked(url:appId:)\/fragments"},{"value":"botDefenderChallengeSolvedForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeSolved(forAppId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeSolved(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderChallengeSolvedForAppId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title","value":"HSBotDefenderDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}