{"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK’s detection."}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowDeviceMotionDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/copy(with:)"],"generated":true,"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/human\/hsdetectionpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsdetectionpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"HSDetectionPolicy","modules":[{"name":"HUMAN"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSDetectionPolicy"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSDetectionPolicy"}],"externalID":"c:@M@HUMAN@objc(cs)HSDetectionPolicy"},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/allowTouchDetection":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowTouchDetection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"allowTouchDetection","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection","type":"topic","abstract":[{"text":"Allow the SDK to intercept touches on the screen. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"title":"allowTouchDetection","kind":"symbol","url":"\/documentation\/human\/hsdetectionpolicy\/allowtouchdetection","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"url":"\/documentation\/human\/hsdetectionpolicy","type":"topic","role":"symbol","navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","kind":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK’s detection."}],"title":"HSDetectionPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/allowDeviceMotionDetection":{"kind":"symbol","type":"topic","url":"\/documentation\/human\/hsdetectionpolicy\/allowdevicemotiondetection","title":"allowDeviceMotionDetection","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Allow the SDK to collect device motion data.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowDeviceMotionDetection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/copy(with:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/copy(with:)","url":"\/documentation\/human\/hsdetectionpolicy\/copy(with:)","title":"copy(with:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSZone","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/init","title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/human\/hsdetectionpolicy\/init"},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HSDetectionPolicy","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"HSDetectionPolicy"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowDeviceMotionDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"allowTouchDetection","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/title"},{"op":"replace","value":[{"text":"allowTouchDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/fragments"},{"op":"replace","value":"HSDetectionPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSDetectionPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments"},{"op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle"},{"op":"replace","value":"allowDeviceMotionDetection","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowDeviceMotionDetection\/title"},{"op":"replace","value":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowDeviceMotionDetection\/fragments"},{"op":"replace","value":"copyWithZone:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1copy(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1copy(with:)\/fragments"}]}]}