{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/bypassMonitorHeaderKey","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled"]},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/copy(with:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsdoctorapppolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsdoctorapppolicy"]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"role":"symbol","roleHeading":"Class","title":"HSDoctorAppPolicy","externalID":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}],"modules":[{"name":"HUMAN"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"The policy that define the behaviour of the Doctor App.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/enabled":{"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled","kind":"symbol","role":"symbol","title":"enabled","url":"\/documentation\/human\/hsdoctorapppolicy\/enabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Set this property to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable the "},{"code":"Doctor App","type":"codeVoice"},{"type":"text","text":" - a tool to verify the integration of the SDK in your app. Make sure to set this property to "},{"type":"codeVoice","code":"false"},{"text":" before deploying you app to production. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/copy(with:)":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/copy(with:)","kind":"symbol","role":"symbol","title":"copy(with:)","url":"\/documentation\/human\/hsdoctorapppolicy\/copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"text":"Any","kind":"keyword"}],"type":"topic","abstract":[]},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/init":{"url":"\/documentation\/human\/hsdoctorapppolicy\/init","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/init","title":"init","role":"symbol"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy/bypassMonitorHeaderKey":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/bypassMonitorHeaderKey","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bypassMonitorHeaderKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bypassMonitorHeaderKey"}],"title":"bypassMonitorHeaderKey","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsdoctorapppolicy\/bypassmonitorheaderkey","abstract":[{"type":"text","text":"This value represent the bypass monitor header key that will be sent when the Doctor App is enabled. It should be use when the Enforcer is configured to "},{"code":"monitor mode","type":"codeVoice"},{"type":"text","text":". This value should be configured in the Enforcer as well. As a result, URL requests will be blocked despite the "},{"type":"codeVoice","code":"monitor mode"},{"type":"text","text":"."}]},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSDoctorAppPolicy"}],"navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"title":"HSDoctorAppPolicy","type":"topic","url":"\/documentation\/human\/hsdoctorapppolicy","kind":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the Doctor App."}]},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"HSDoctorAppPolicy"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/bypassMonitorHeaderKey","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/enabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy\/init"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"HSDoctorAppPolicy","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/title","value":"enabled"},{"op":"replace","value":[{"text":"enabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1enabled\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"value":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1copy(with:)\/fragments","op":"replace"},{"value":"bypassMonitorHeaderKey","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1bypassMonitorHeaderKey\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy~1bypassMonitorHeaderKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"bypassMonitorHeaderKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title","value":"HSDoctorAppPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments","value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace"}]}]}