{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSError"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/hserror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hserror"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","symbolKind":"class","title":"HSError","externalID":"c:@M@HUMAN@objc(cs)HSError","navigatorTitle":[{"kind":"identifier","text":"HSError"}],"role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSError"}]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSError"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCoding","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSSecureCoding","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/s5ErrorP","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/s8SendableP","doc:\/\/com.perimeterx.mobile-sdk\/s16SendableMetatypeP"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.perimeterx.mobile-sdk/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s5ErrorP","title":"Swift.Error"},"doc://com.perimeterx.mobile-sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSSecureCoding":{"title":"Foundation.NSSecureCoding","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSSecureCoding"},"doc://com.perimeterx.mobile-sdk/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSError":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSError","title":"NSError"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s8SendableP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError":{"url":"\/documentation\/human\/hserror","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","title":"HSError","role":"symbol","navigatorTitle":[{"text":"HSError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSError","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError/initWithDomain:code:userInfo:":{"url":"\/documentation\/human\/hserror\/initwithdomain:code:userinfo:","title":"initWithDomain:code:userInfo:","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithDomain:code:userInfo:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithDomain:code:userInfo:"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError/initWithCoder:":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithCoder:","url":"\/documentation\/human\/hserror\/initwithcoder:","title":"initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCoding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"HSError","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"HSError"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"HSError","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"add","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithCoder:","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError\/initWithDomain:code:userInfo:"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSError"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSError","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"HSError","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/title"},{"value":[{"text":"HSError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/fragments"},{"value":[{"kind":"identifier","text":"HSError"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/navigatorTitle"}]}]}