{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/allowJavaScriptEvaluation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/supportExternalWebViews"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"],"generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hshybridapppolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hshybridapppolicy"]}],"kind":"symbol","metadata":{"roleHeading":"Class","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HSHybridAppPolicy","kind":"identifier"}],"title":"HSHybridAppPolicy","symbolKind":"class","externalID":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To"}],"abstract":[{"text":"The policy that define the behaviour of the Hybrid App support.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"}]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"abstract":[{"type":"text","text":"The policy that define the behaviour of the Hybrid App support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSHybridAppPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","kind":"symbol","title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","role":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"title":"automaticSetup","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup","kind":"symbol","abstract":[{"text":"When this property is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the SDK detects all "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)"},{"text":" function. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticSetup"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","kind":"symbol","abstract":[{"text":"Setup the web view to be synced with SDK. Do not set a ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"type":"text","text":" to the web view after calling this function."},{"type":"text","text":" "},{"text":"If you wish to set a web view client, call this function again with the new ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"type":"text","text":". You should not call this method when the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","type":"reference","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupWebView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigationDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationDelegate","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"text":"?)","kind":"text"}],"title":"setupWebView(webView:navigationDelegate:)"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/human\/hshybridapppolicy\/init","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/init","type":"topic","abstract":[],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/supportExternalWebViews":{"navigatorTitle":[{"text":"supportExternalWebViews","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportExternalWebViews"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"supportExternalWebViews","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/supportExternalWebViews","url":"\/documentation\/human\/hshybridapppolicy\/supportexternalwebviews","abstract":[{"text":"Set this property to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" to support external web views, which are web views created outside the native side of the app but are still based on "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" (for example, "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview"},{"type":"text","text":"). Default is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/allowJavaScriptEvaluation":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowJavaScriptEvaluation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"allowJavaScriptEvaluation","role":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/allowjavascriptevaluation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/allowJavaScriptEvaluation","type":"topic","abstract":[{"type":"text","text":"Allow the SDK to evaluate JavaScript code in your web views (for hybrid app support). You should disable JavaScript code when using ApplePay in your web view. When you disable JavaScript evaluation, the SDK could store cookies instead (depending on the run time environment). Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}]},"https://github.com/react-native-webview/react-native-webview":{"url":"https:\/\/github.com\/react-native-webview\/react-native-webview","title":"react-native-webview","titleInlineContent":[{"text":"react-native-webview","type":"text"}],"type":"link","identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/copy(with:)":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"title":"copy(with:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/copy(with:)","url":"\/documentation\/human\/hshybridapppolicy\/copy(with:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/set(webRootDomains:forAppId:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/human\/hshybridapppolicy\/set(webrootdomains:forappid:)","abstract":[{"text":"The SDK is setting cookies in your web views in order to sync between the native and the web sessions. For that, the SDK has to know you website’s root domain for the HTTP cookie (e.g “.example.com”). Those domains can be set in the HUMAN’s Portal, however, it recommended to set them directly in the SDK’s policy.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webRootDomains"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"set(webRootDomains:forAppId:)","navigatorTitle":[{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"HSHybridAppPolicy","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/allowJavaScriptEvaluation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/supportExternalWebViews"],"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/init","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/set(webRootDomains:forAppId:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"HSHybridAppPolicy","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title","op":"replace","value":"HSHybridAppPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title","op":"replace","value":"automaticSetup"},{"value":[{"kind":"identifier","text":"automaticSetup"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title","op":"replace","value":"setupWebViewWithWebView:navigationDelegate:"},{"value":[{"kind":"text","text":"+ "},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1supportExternalWebViews\/title","value":"supportExternalWebViews"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1supportExternalWebViews\/fragments","value":[{"kind":"identifier","text":"supportExternalWebViews"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1allowJavaScriptEvaluation\/title","op":"replace","value":"allowJavaScriptEvaluation"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1allowJavaScriptEvaluation\/fragments","value":[{"text":"allowJavaScriptEvaluation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1copy(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/title","value":"setWithWebRootDomains:forAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1set(webRootDomains:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithWebRootDomains:forAppId:"}]}]}]}