{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","interfaceLanguage":"swift"},"metadata":{"title":"HSPolicy","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/allowSharingPolicyWithHuman","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/automaticInterceptorPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/detectionPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/doctorAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/hybridAppPolicy"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/copy(with:)"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hspolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hspolicy"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/allowSharingPolicyWithHuman":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSharingPolicyWithHuman","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/human\/hspolicy\/allowsharingpolicywithhuman","title":"allowSharingPolicyWithHuman","abstract":[{"text":"Allow the SDK to share the policy with HUMAN. The policy does not contain PII.","type":"text"},{"text":" ","type":"text"},{"text":"Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/allowSharingPolicyWithHuman","navigatorTitle":[{"text":"allowSharingPolicyWithHuman","kind":"identifier"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/detectionPolicy":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSDetectionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDetectionPolicy"}],"type":"topic","navigatorTitle":[{"text":"detectionPolicy","kind":"identifier"}],"abstract":[{"text":"Configure the detection policy.","type":"text"}],"url":"\/documentation\/human\/hspolicy\/detectionpolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/detectionPolicy","title":"detectionPolicy","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/hybridAppPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/hybridAppPolicy","kind":"symbol","title":"hybridAppPolicy","navigatorTitle":[{"kind":"identifier","text":"hybridAppPolicy"}],"url":"\/documentation\/human\/hspolicy\/hybridapppolicy","role":"symbol","abstract":[{"text":"Configure the Hybrid App support policy.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybridAppPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSHybridAppPolicy","text":"HSHybridAppPolicy"}]},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/automaticInterceptorPolicy":{"kind":"symbol","abstract":[{"text":"Configure the Automatic Interceptor policy.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/automaticInterceptorPolicy","url":"\/documentation\/human\/hspolicy\/automaticinterceptorpolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticInterceptorPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy"}],"navigatorTitle":[{"text":"automaticInterceptorPolicy","kind":"identifier"}],"title":"automaticInterceptorPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/init":{"url":"\/documentation\/human\/hspolicy\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/init"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/copy(with:)":{"title":"copy(with:)","abstract":[],"kind":"symbol","url":"\/documentation\/human\/hspolicy\/copy(with:)","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy/doctorAppPolicy":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorAppPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSDoctorAppPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSDoctorAppPolicy"}],"url":"\/documentation\/human\/hspolicy\/doctorapppolicy","abstract":[{"type":"text","text":"Configure the Doctor App policy."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/doctorAppPolicy","title":"doctorAppPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"doctorAppPolicy"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"HSPolicy","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"HSPolicy"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"HSPolicy","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"HSPolicy","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/allowSharingPolicyWithHuman","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/automaticInterceptorPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/detectionPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/doctorAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/hybridAppPolicy"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"],"kind":"relationships","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1allowSharingPolicyWithHuman\/title","op":"replace","value":"allowSharingPolicyWithHuman"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1allowSharingPolicyWithHuman\/fragments","op":"replace","value":[{"text":"allowSharingPolicyWithHuman","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1detectionPolicy\/title","op":"replace","value":"detectionPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1detectionPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1hybridAppPolicy\/title","op":"replace","value":"hybridAppPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1hybridAppPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"hybridAppPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1automaticInterceptorPolicy\/title","op":"replace","value":"automaticInterceptorPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1automaticInterceptorPolicy\/fragments","op":"replace","value":[{"text":"automaticInterceptorPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1copy(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1doctorAppPolicy\/title","op":"replace","value":"doctorAppPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy~1doctorAppPolicy\/fragments","op":"replace","value":[{"text":"doctorAppPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","op":"replace","value":"HSPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HSPolicy"}]}]}]}