{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"languages":["swift"]}]}],"metadata":{"title":"HumanSecurity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}],"externalID":"c:@M@HUMAN@objc(cs)HumanSecurity","roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"HUMAN"}]},"topicSections":[{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/AD","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/BD"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/sdkVersion()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/vid(forAppId:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humansecurity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humansecurity"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","title":"start(appId:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/vid(forAppId:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vid","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"vid(forAppId:)","abstract":[{"text":"Get the VID for given AppID.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/vid(forAppId:)","role":"symbol","kind":"symbol","url":"\/documentation\/human\/humansecurity\/vid(forappid:)","navigatorTitle":[{"text":"vidForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","title":"setupWebView(webView:navigationDelegate:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupWebView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate","text":"WKNavigationDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Setup the web view to be synced with SDK. Do not set a ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":" to the web view after calling this function.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you wish to set a web view client, call this function again with the new "},{"type":"codeVoice","code":"WKNavigationDelegate"},{"type":"text","text":". You should not call this method when the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"abstract":[{"type":"text","text":"Human Security main class. You should interact with it in order to setup and start the SDK."}],"url":"\/documentation\/human\/humansecurity","title":"HumanSecurity","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}]},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"title":"automaticSetup","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup","type":"topic","kind":"symbol","abstract":[{"text":"When this property is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the SDK detects all ","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true},{"type":"text","text":" function. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"automaticSetup"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticSetup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/AD":{"abstract":[],"url":"\/documentation\/human\/humansecurity\/ad","title":"AD","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSAccountDefender","text":"HSAccountDefender"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/AD","navigatorTitle":[{"kind":"identifier","text":"AD"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/init":{"title":"init","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/init","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/init","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/sdkVersion()":{"url":"\/documentation\/human\/humansecurity\/sdkversion()","kind":"symbol","type":"topic","title":"sdkVersion()","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/sdkVersion()","abstract":[{"text":"Returns the SDK version.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}]},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/BD":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/BD","kind":"symbol","abstract":[],"title":"BD","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BD","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSBotDefender","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSBotDefender","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"BD","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/bd"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"title":"start(appIds:policy:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"HumanSecurity","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/AD","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/BD"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/sdkVersion()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/vid(forAppId:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurity"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","value":"startWithAppId:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1vid(forAppId:)\/title","value":"vidForAppId:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1vid(forAppId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"vidForAppId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title","value":"setupWebViewWithWebView:navigationDelegate:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","value":"HumanSecurity","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle","value":[{"text":"HumanSecurity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title","value":"automaticSetup","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments","value":[{"text":"automaticSetup","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1AD\/title","value":"AD","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1AD\/fragments","value":[{"kind":"identifier","text":"AD"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1sdkVersion()\/title","value":"sdkVersion","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1sdkVersion()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sdkVersion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1BD\/title","value":"BD","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1BD\/fragments","value":[{"text":"BD","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","value":"startWithAppIds:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}