{"sections":[],"metadata":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","roleHeading":"Protocol","modules":[{"name":"HUMAN"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HumanDelegate"}],"externalID":"c:@M@HUMAN@objc(pl)HumanDelegate","symbolKind":"protocol","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humandelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humandelegate"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Human protocol"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidFailRenderChallenge(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRenderChallenge(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRequestBlocked(url:appId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanHeadersWereUpdated(headers:forAppId:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidChallengeSolved(forAppId:)":{"title":"humanDidChallengeSolved(forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeSolved(forAppId:)","navigatorTitle":[{"text":"humanDidChallengeSolvedForAppId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when the challenge was solved."}],"url":"\/documentation\/human\/humandelegate\/humandidchallengesolved(forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"humanDidChallengeSolved"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","required":true},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate":{"navigatorTitle":[{"text":"HumanDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanDelegate","kind":"identifier"}],"title":"HumanDelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate","abstract":[{"text":"Human protocol","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidFailRenderChallenge(forAppId:)":{"url":"\/documentation\/human\/humandelegate\/humandidfailrenderchallenge(forappid:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanDidFailRenderChallenge"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidFailRenderChallenge(forAppId:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the challenge was failed to render."}],"title":"humanDidFailRenderChallenge(forAppId:)","navigatorTitle":[{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"NSObject"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidChallengeCancelled(forAppId:)":{"navigatorTitle":[{"text":"humanDidChallengeCancelledForAppId:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"humanDidChallengeCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"humanDidChallengeCancelled(forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeCancelled(forAppId:)","abstract":[{"text":"Called when the challenge was cancelled.","type":"text"}],"type":"topic","url":"\/documentation\/human\/humandelegate\/humandidchallengecancelled(forappid:)","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidRequestBlocked(url:appId:)":{"title":"humanDidRequestBlocked(url:appId:)","navigatorTitle":[{"kind":"identifier","text":"humanDidRequestBlockedWithUrl:appId:"}],"url":"\/documentation\/human\/humandelegate\/humandidrequestblocked(url:appid:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"humanDidRequestBlocked","kind":"identifier"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","required":true,"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRequestBlocked(url:appId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanHeadersWereUpdated(headers:forAppId:)":{"navigatorTitle":[{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"abstract":[{"text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the ","type":"text"},{"code":"Human\/headersForURLRequest(forAppId:)","type":"codeVoice"},{"type":"text","text":" function for every URL request."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanHeadersWereUpdated(headers:forAppId:)","title":"humanHeadersWereUpdated(headers:forAppId:)","type":"topic","url":"\/documentation\/human\/humandelegate\/humanheaderswereupdated(headers:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"humanHeadersWereUpdated","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanDelegate/humanDidRenderChallenge(forAppId:)":{"abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"url":"\/documentation\/human\/humandelegate\/humandidrenderchallenge(forappid:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"humanDidRenderChallenge","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRenderChallenge(forAppId:)","title":"humanDidRenderChallenge(forAppId:)","required":true,"role":"symbol","navigatorTitle":[{"text":"humanDidRenderChallengeForAppId:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"HumanDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HumanDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"HumanDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidFailRenderChallenge(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRenderChallenge(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanDidRequestBlocked(url:appId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanDelegate\/humanHeadersWereUpdated(headers:forAppId:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeSolved(forAppId:)\/title","value":"humanDidChallengeSolvedForAppId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeSolved(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"humanDidChallengeSolvedForAppId:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/title","value":"HumanDelegate"},{"op":"replace","value":[{"text":"HumanDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidFailRenderChallenge(forAppId:)\/title","value":"humanDidFailRenderChallengeForAppId:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidFailRenderChallenge(forAppId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"humanDidFailRenderChallengeForAppId:","kind":"identifier"}]},{"value":"humanDidChallengeCancelledForAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeCancelled(forAppId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidChallengeCancelled(forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"humanDidChallengeCancelledForAppId:"}]},{"value":"humanDidRequestBlockedWithUrl:appId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRequestBlocked(url:appId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRequestBlocked(url:appId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"humanDidRequestBlockedWithUrl:appId:"}],"op":"replace"},{"value":"humanHeadersWereUpdatedWithHeaders:forAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanHeadersWereUpdated(headers:forAppId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanHeadersWereUpdated(headers:forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"humanHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRenderChallenge(forAppId:)\/title","value":"humanDidRenderChallengeForAppId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanDelegate~1humanDidRenderChallenge(forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"humanDidRenderChallengeForAppId:","kind":"identifier"}]}]}]}