{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HumanErrorCode"}]}]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/tokenWasNotGenerated"]},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"HumanErrorCode","kind":"identifier"}],"modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@E@HumanErrorCode","symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HumanErrorCode","kind":"identifier"}],"title":"HumanErrorCode","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/init(rawValue:)":{"abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/init(rawValue:)","kind":"symbol","url":"\/documentation\/human\/humanerrorcode\/init(rawvalue:)","title":"init(rawValue:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/httpBodyInputStreamReadFailed":{"title":"HumanErrorCode.httpBodyInputStreamReadFailed","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/httpBodyInputStreamReadFailed","abstract":[{"type":"text","text":"Failed to read body from input stream of the request."}],"url":"\/documentation\/human\/humanerrorcode\/httpbodyinputstreamreadfailed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/startNotCalledOnMainThread":{"navigatorTitle":[{"text":"HumanErrorCodeStartNotCalledOnMainThread","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)"},{"text":" functions were called not on the main thread.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startNotCalledOnMainThread","url":"\/documentation\/human\/humanerrorcode\/startnotcalledonmainthread","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startNotCalledOnMainThread"}],"title":"HumanErrorCode.startNotCalledOnMainThread","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/challengeSolved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","kind":"symbol","abstract":[{"type":"text","text":"Challenge was solved by the user."}],"title":"HumanErrorCode.challengeSolved","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeChallengeSolved"}],"url":"\/documentation\/human\/humanerrorcode\/challengesolved","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"challengeSolved","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable"},"doc://com.perimeterx.mobile-sdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","title":"Swift.RawRepresentable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/tokenWasNotGenerated":{"url":"\/documentation\/human\/humanerrorcode\/tokenwasnotgenerated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenWasNotGenerated"}],"abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"type":"topic","title":"HumanErrorCode.tokenWasNotGenerated","kind":"symbol","navigatorTitle":[{"text":"HumanErrorCodeTokenWasNotGenerated","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/tokenWasNotGenerated","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/human\/humanerrorcode\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/RawRepresentable-Implementations","kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:delegate:policy:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appIds:delegate:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/startWasNotCalled":{"navigatorTitle":[{"text":"HumanErrorCodeStartWasNotCalled","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The SDK failed to perform the operation. Make sure to call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)"},{"text":" function.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startWasNotCalled","url":"\/documentation\/human\/humanerrorcode\/startwasnotcalled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startWasNotCalled","kind":"identifier"}],"title":"HumanErrorCode.startWasNotCalled","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/invalidAppId":{"navigatorTitle":[{"text":"HumanErrorCodeInvalidAppId","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","isActive":true},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","isActive":true},{"text":" functions were called with invalid AppID.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/invalidAppId","url":"\/documentation\/human\/humanerrorcode\/invalidappid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidAppId","kind":"identifier"}],"title":"HumanErrorCode.invalidAppId","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/challengeCancelled":{"title":"HumanErrorCode.challengeCancelled","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeCancelled","role":"symbol","url":"\/documentation\/human\/humanerrorcode\/challengecancelled","kind":"symbol","type":"topic","navigatorTitle":[{"text":"HumanErrorCodeChallengeCancelled","kind":"identifier"}],"abstract":[{"type":"text","text":"Challenge was cancelled."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"challengeCancelled","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/human\/humanerrorcode\/equatable-implementations","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/Equatable-Implementations","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/internalError":{"navigatorTitle":[{"text":"HumanErrorCodeInternalError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Internal error in the SDK."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/internalError","url":"\/documentation\/human\/humanerrorcode\/internalerror","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"title":"HumanErrorCode.internalError","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:delegate:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"start(appId:delegate:policy:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/missingAppId":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"missingAppId","kind":"identifier"}],"title":"HumanErrorCode.missingAppId","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/missingAppId","abstract":[{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","type":"reference"},{"type":"text","text":" or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)"},{"type":"text","text":" functions were called without any AppID."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeMissingAppId"}],"url":"\/documentation\/human\/humanerrorcode\/missingappid"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/requestWasBlocked":{"navigatorTitle":[{"text":"HumanErrorCodeRequestWasBlocked","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestWasBlocked"}],"title":"HumanErrorCode.requestWasBlocked","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/requestWasBlocked","abstract":[{"text":"URL request was blocked by Human.","type":"text"}],"type":"topic","url":"\/documentation\/human\/humanerrorcode\/requestwasblocked","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/startCalledMoreThanOnce":{"navigatorTitle":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"kind":"symbol","abstract":[{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","type":"reference"},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","isActive":true},{"type":"text","text":" functions were called more than once."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startCalledMoreThanOnce","url":"\/documentation\/human\/humanerrorcode\/startcalledmorethanonce","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startCalledMoreThanOnce","kind":"identifier"}],"title":"HumanErrorCode.startCalledMoreThanOnce","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"HumanErrorCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HumanErrorCode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"HumanErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/tokenWasNotGenerated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1httpBodyInputStreamReadFailed\/title","value":"HumanErrorCodeHttpBodyInputStreamReadFailed"},{"value":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1httpBodyInputStreamReadFailed\/fragments","op":"replace"},{"op":"replace","value":"HumanErrorCode","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments","value":[{"kind":"identifier","text":"HumanErrorCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startNotCalledOnMainThread\/title","value":"HumanErrorCodeStartNotCalledOnMainThread"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startNotCalledOnMainThread\/fragments","value":[{"kind":"identifier","text":"HumanErrorCodeStartNotCalledOnMainThread"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeSolved\/title","value":"HumanErrorCodeChallengeSolved","op":"replace"},{"value":[{"text":"HumanErrorCodeChallengeSolved","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeSolved\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1tokenWasNotGenerated\/title","op":"replace","value":"HumanErrorCodeTokenWasNotGenerated"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1tokenWasNotGenerated\/fragments","value":[{"text":"HumanErrorCodeTokenWasNotGenerated","kind":"identifier"}]},{"value":"startWithAppIds:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startWasNotCalled\/title","value":"HumanErrorCodeStartWasNotCalled"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startWasNotCalled\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeStartWasNotCalled"}]},{"op":"replace","value":"HumanErrorCodeInvalidAppId","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1invalidAppId\/title"},{"op":"replace","value":[{"text":"HumanErrorCodeInvalidAppId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1invalidAppId\/fragments"},{"value":"HumanErrorCodeChallengeCancelled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeCancelled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"HumanErrorCodeChallengeCancelled"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeCancelled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1internalError\/title","value":"HumanErrorCodeInternalError"},{"op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeInternalError"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1internalError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/title","value":"startWithAppId:delegate:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1missingAppId\/title","value":"HumanErrorCodeMissingAppId","op":"replace"},{"op":"replace","value":[{"text":"HumanErrorCodeMissingAppId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1missingAppId\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1requestWasBlocked\/title","value":"HumanErrorCodeRequestWasBlocked","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeRequestWasBlocked"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1requestWasBlocked\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startCalledMoreThanOnce\/title","op":"replace","value":"HumanErrorCodeStartCalledMoreThanOnce"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startCalledMoreThanOnce\/fragments","value":[{"kind":"identifier","text":"HumanErrorCodeStartCalledMoreThanOnce"}],"op":"replace"}]}]}