{"metadata":{"modules":[{"name":"HUMAN"}],"title":"HumanSecurityErrorType","symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HumanSecurityErrorType","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"roleHeading":"Enumeration"},"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/automaticInterceptorIsNotConfiguredCorrectly","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/tokenWasNotGenerated"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"sections":[],"variants":[{"paths":["\/documentation\/human\/humansecurityerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humansecurityerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"start(appId:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/startNotCalledOnMainThread":{"url":"\/documentation\/human\/humansecurityerrortype\/startnotcalledonmainthread","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startNotCalledOnMainThread","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startNotCalledOnMainThread","kind":"identifier"}],"navigatorTitle":[{"text":"HumanSecurityErrorTypeStartNotCalledOnMainThread","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","isActive":true,"type":"reference"},{"text":" functions were called not on the main thread.","type":"text"}],"role":"symbol","title":"HumanSecurityErrorType.startNotCalledOnMainThread","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/httpBodyInputStreamReadFailed":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/httpBodyInputStreamReadFailed","title":"HumanSecurityErrorType.httpBodyInputStreamReadFailed","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed"}],"type":"topic","abstract":[{"text":"Failed to read body from input stream of the request.","type":"text"}],"role":"symbol","url":"\/documentation\/human\/humansecurityerrortype\/httpbodyinputstreamreadfailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpBodyInputStreamReadFailed"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/startCalledMoreThanOnce":{"title":"HumanSecurityErrorType.startCalledMoreThanOnce","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" or ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},{"text":" functions were called more than once.","type":"text"}],"type":"topic","url":"\/documentation\/human\/humansecurityerrortype\/startcalledmorethanonce","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCalledMoreThanOnce","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startCalledMoreThanOnce","kind":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorTypeStartCalledMoreThanOnce","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/internalError":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeInternalError"}],"url":"\/documentation\/human\/humansecurityerrortype\/internalerror","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/internalError","title":"HumanSecurityErrorType.internalError","abstract":[{"type":"text","text":"Internal error in the SDK."}]},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/RawRepresentable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/human\/humansecurityerrortype\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/RawRepresentable-Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"start(appIds:policy:)","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"kind":"article","url":"\/documentation\/human\/humansecurityerrortype\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/Equatable-Implementations","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/tokenWasNotGenerated":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/tokenWasNotGenerated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenWasNotGenerated","kind":"identifier"}],"navigatorTitle":[{"text":"HumanSecurityErrorTypeTokenWasNotGenerated","kind":"identifier"}],"url":"\/documentation\/human\/humansecurityerrortype\/tokenwasnotgenerated","abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"role":"symbol","title":"HumanSecurityErrorType.tokenWasNotGenerated"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/human\/humansecurityerrortype\/init(rawvalue:)","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"url":"\/documentation\/human\/humansecurityerrortype","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"kind":"symbol","title":"HumanSecurityErrorType","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorType"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/missingAppId":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingAppId","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","isActive":true,"type":"reference"},{"text":" functions were called without any AppID.","type":"text"}],"url":"\/documentation\/human\/humansecurityerrortype\/missingappid","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/missingAppId","kind":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorTypeMissingAppId","kind":"identifier"}],"title":"HumanSecurityErrorType.missingAppId"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/invalidAppId":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}],"kind":"symbol","abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"reference","isActive":true},{"type":"text","text":" or "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference","isActive":true},{"type":"text","text":" functions were called with invalid AppID."}],"url":"\/documentation\/human\/humansecurityerrortype\/invalidappid","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/invalidAppId","title":"HumanSecurityErrorType.invalidAppId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanSecurityErrorTypeInvalidAppId"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/automaticInterceptorIsNotConfiguredCorrectly":{"url":"\/documentation\/human\/humansecurityerrortype\/automaticinterceptorisnotconfiguredcorrectly","role":"symbol","title":"HumanSecurityErrorType.automaticInterceptorIsNotConfiguredCorrectly","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorIsNotConfiguredCorrectly"}],"abstract":[{"type":"text","text":"The Automatic Interceptor is not configured correctly."}],"navigatorTitle":[{"text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/automaticInterceptorIsNotConfiguredCorrectly"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType/startWasNotCalled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startWasNotCalled","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startWasNotCalled","url":"\/documentation\/human\/humansecurityerrortype\/startwasnotcalled","role":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorTypeStartWasNotCalled","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK failed to perform the operation. Make sure to call the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true},{"type":"text","text":" function."}],"title":"HumanSecurityErrorType.startWasNotCalled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HumanSecurityErrorType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/automaticInterceptorIsNotConfiguredCorrectly","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType\/tokenWasNotGenerated"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanSecurityErrorType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"startWithAppId:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments"},{"op":"replace","value":"HumanSecurityErrorTypeStartNotCalledOnMainThread","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startNotCalledOnMainThread\/title"},{"op":"replace","value":[{"text":"HumanSecurityErrorTypeStartNotCalledOnMainThread","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startNotCalledOnMainThread\/fragments"},{"op":"replace","value":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1httpBodyInputStreamReadFailed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeHttpBodyInputStreamReadFailed"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1httpBodyInputStreamReadFailed\/fragments"},{"op":"replace","value":"HumanSecurityErrorTypeStartCalledMoreThanOnce","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startCalledMoreThanOnce\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeStartCalledMoreThanOnce"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startCalledMoreThanOnce\/fragments"},{"op":"replace","value":"HumanSecurityErrorTypeInternalError","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1internalError\/title"},{"op":"replace","value":[{"text":"HumanSecurityErrorTypeInternalError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1internalError\/fragments"},{"op":"replace","value":"startWithAppIds:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1tokenWasNotGenerated\/title","value":"HumanSecurityErrorTypeTokenWasNotGenerated","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1tokenWasNotGenerated\/fragments","value":[{"text":"HumanSecurityErrorTypeTokenWasNotGenerated","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title","value":"HumanSecurityErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle","value":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1missingAppId\/title","value":"HumanSecurityErrorTypeMissingAppId","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1missingAppId\/fragments","value":[{"text":"HumanSecurityErrorTypeMissingAppId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1invalidAppId\/title","value":"HumanSecurityErrorTypeInvalidAppId","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1invalidAppId\/fragments","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeInvalidAppId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1automaticInterceptorIsNotConfiguredCorrectly\/title","value":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1automaticInterceptorIsNotConfiguredCorrectly\/fragments","value":[{"kind":"identifier","text":"HumanSecurityErrorTypeAutomaticInterceptorIsNotConfiguredCorrectly"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startWasNotCalled\/title","value":"HumanSecurityErrorTypeStartWasNotCalled","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType~1startWasNotCalled\/fragments","value":[{"text":"HumanSecurityErrorTypeStartWasNotCalled","kind":"identifier"}],"op":"replace"}]}]}