{"metadata":{"title":"HumanChallengeResult","externalID":"c:@M@HUMAN@E@HumanChallengeResult","roleHeading":"Enumeration","modules":[{"name":"HUMAN"}],"navigatorTitle":[{"text":"HumanChallengeResult","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanChallengeResult","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanChallengeResult"}],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/solved"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Challenge result."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanchallengeresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanchallengeresult"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/solved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/solved","role":"symbol","title":"HumanChallengeResult.solved","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solved","kind":"identifier"}],"navigatorTitle":[{"text":"HumanChallengeResultSolved","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/human\/humanchallengeresult\/solved","abstract":[{"type":"text","text":"Challenge was solved."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/human\/humanchallengeresult\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","kind":"symbol","url":"\/documentation\/human\/humanchallengeresult\/init(rawvalue:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/human\/humanchallengeresult\/cancelled","abstract":[{"text":"Challenge was cancelled.","type":"text"}],"navigatorTitle":[{"text":"HumanChallengeResultCancelled","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/cancelled","type":"topic","title":"HumanChallengeResult.cancelled"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/Equatable-Implementations","url":"\/documentation\/human\/humanchallengeresult\/equatable-implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"Equatable Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanChallengeResult":{"url":"\/documentation\/human\/humanchallengeresult","type":"topic","abstract":[{"type":"text","text":"Challenge result."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HumanChallengeResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HumanChallengeResult"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult","title":"HumanChallengeResult","role":"symbol"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","title":"Swift.RawRepresentable"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"HumanChallengeResult"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HumanChallengeResult","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"HumanChallengeResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanChallengeResult\/solved"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanChallengeResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"value":"HumanChallengeResultSolved","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1solved\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1solved\/fragments","value":[{"kind":"identifier","text":"HumanChallengeResultSolved"}]},{"value":"HumanChallengeResultCancelled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1cancelled\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult~1cancelled\/fragments","op":"replace","value":[{"text":"HumanChallengeResultCancelled","kind":"identifier"}]},{"value":"HumanChallengeResult","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HumanChallengeResult"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanChallengeResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}