{"metadata":{"role":"article","title":"Hybrid App Integration","modules":[{"name":"HUMAN"}],"roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"variants":[{"paths":["\/documentation\/human\/hybrid_app_integration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hybrid_app_integration"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"What is an Hybrid App","anchor":"What-is-an-Hybrid-App"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An Hybrid App uses both native URL requests and web views to communicate with your server. In the context of  HUMAN, it’s important to make sure both native requests and web views are synced together to make sure end users will get the expected behavior from your app."}]},{"type":"heading","level":2,"text":"How do I know if my app is an Hybrid App","anchor":"How-do-I-know-if-my-app-is-an-Hybrid-App"},{"type":"paragraph","inlineContent":[{"text":"Your app is considered to be an Hybrid App if it has ","type":"text"},{"type":"strong","inlineContent":[{"text":"ALL","type":"text"}]},{"text":" of the following:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"A web view component (","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"text":" on iOS or ","type":"text"},{"code":"WebView","type":"codeVoice"},{"text":" on Android) that loads ","type":"text"},{"inlineContent":[{"type":"text","text":"your website"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Your website","type":"text"}],"type":"strong"},{"type":"text","text":" is protected by HUMAN (Bot Defender or Account Defender)."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On iOS, if your app uses "},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/safariservices\/sfsafariviewcontroller","type":"reference"},{"type":"text","text":", please let us know and we will guide you for a specific integration."}]},{"type":"heading","level":2,"text":"How to enable an Hybrid App support in my app","anchor":"How-to-enable-an-Hybrid-App-support-in-my-app"},{"type":"heading","level":3,"text":"Integrate the SDK (native)","anchor":"Integrate-the-SDK-native"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should integrate the SDK to your native app. You may choose one of the following ways:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","overridingTitle":"Easiest Implementation","isActive":true,"overridingTitleInlineContent":[{"text":"Easiest Implementation","type":"text"}],"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","isActive":true,"overridingTitleInlineContent":[{"text":"Basic Implementation","type":"text"}],"type":"reference","overridingTitle":"Basic Implementation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","isActive":true,"overridingTitle":"Advanced Functionality","type":"reference","overridingTitleInlineContent":[{"text":"Advanced Functionality","type":"text"}]}]}]}]},{"type":"heading","level":3,"text":"Enable Hybrid App support","anchor":"Enable-Hybrid-App-support"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When starting the SDK you should declare your website root domain in the policy. This should be the domain which the SDK will set cookies."}]},{"type":"paragraph","inlineContent":[{"text":"The SDK enables Hybrid App support ONLY for those domains. The SDK checks if the website’s domain ends with one of the domains that were set. For example: If you set ","type":"text"},{"type":"codeVoice","code":"example.com"},{"text":", the SDK will also support ","type":"text"},{"type":"codeVoice","code":"www.example.com"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"api.example.com"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should send the "},{"type":"codeVoice","code":"WebView"},{"type":"text","text":" instance to the SDK via the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)"},{"type":"text","text":" function in iOS and "},{"type":"codeVoice","code":"HumanSecurity\/setupWebView(webView:webViewClient:)"},{"type":"text","text":" function in Android. This function sets the "},{"type":"codeVoice","code":"WebView"},{"type":"text","text":"‘s "},{"type":"codeVoice","code":"navigationDelegate"},{"type":"text","text":" (iOS) and "},{"type":"codeVoice","code":"webViewClient"},{"type":"text","text":" (Android) with the SDK’s object. "},{"type":"strong","inlineContent":[{"text":"You should not set those properties after calling the ","type":"text"},{"code":"setupWebView","type":"codeVoice"},{"text":" function","type":"text"}]},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On iOS, you can ask the SDK to detect "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":"s and setup them automatically without calling the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true},{"type":"text","text":" function for each instance. You can enable this feature by setting the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","isActive":true},{"type":"text","text":" to be "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"heading","level":4,"text":"Android","anchor":"Android"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"type":"codeListing","code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.policy.HSPolicy","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        startHumanSDK()","    }","","    private fun startHumanSDK() {","        try {","            val policy = HSPolicy()","            \/\/ Configure the policy...","","            val webRootDomains = setOf(\".example.com\")","            policy.hybridAppPolicy.setWebRootDomains(webRootDomains, \"<APP_ID>\")","","            HumanSecurity.start(this, \"<APP_ID>\", policy)","        }","        catch (exception: Exception) {","            println(\"Exception: ${exception.message}\")","        }","    }","}"],"syntax":"kotlin"},{"type":"codeListing","code":["import androidx.appcompat.app.AppCompatActivity","import android.os.Bundle","import android.webkit.WebView","import com.humansecurity.mobile_sdk.HumanSecurity","","class MainActivity: AppCompatActivity() {","","    override fun onCreate(savedInstanceState: Bundle?) {","        super.onCreate(savedInstanceState)","        setContentView(R.layout.activity_main)","","        val webView = findViewById<WebView>(R.id.web_view)","        val webViewClient = MyWebViewClient()","        HumanSecurity.setupWebView(webView, webViewClient)","","        \/\/ Load your website in the web view...","    }","}"],"syntax":"kotlin"},{"type":"paragraph","inlineContent":[{"text":"Java:","type":"text"}]},{"type":"codeListing","code":["import android.app.Application;","import android.util.Log;","import java.util.HashSet;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.policy.HSPolicy;","","public class MainApplication extends Application {","","    @Override","    public void onCreate() {","        super.onCreate();","        startHumanSDK();","    }","","    void startHumanSDK() {","        try {","            HSPolicy policy = new HSPolicy();","            \/\/ Configure the policy...","","            HashSet<String> domains = new HashSet<>();","            domains.add(\".example.com\");","            policy.getHybridAppPolicy().setWebRootDomains(domains, \"<APP_ID>\");","","            HumanSecurity.INSTANCE.start(this, \"<APP_ID>\", policy);","        }","        catch (Exception exception) {","            Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","        }","    }","}"],"syntax":"java"},{"type":"codeListing","code":["import androidx.appcompat.app.AppCompatActivity;","import android.os.Bundle;","import android.webkit.WebView;","import android.webkit.WebViewClient;","import com.humansecurity.mobile_sdk.HumanSecurity;","","public class MainActivity extends AppCompatActivity {","","    @Override","    protected void onCreate(Bundle savedInstanceState) {","        super.onCreate(savedInstanceState);","        setContentView(R.layout.activity_main);","","        WebView webView = findViewById(R.id.web_view);","        MyWebViewClient webViewClient = new MyWebViewClient();","        HumanSecurity.INSTANCE.setupWebView(webView, webViewClient);","","        \/\/ Load your website in the web view...","    }","}"],"syntax":"java"},{"type":"heading","level":4,"text":"iOS","anchor":"iOS"},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"type":"codeListing","code":["import UIKit","import HUMAN","","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        startHumanSDK()","        return true","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            \/\/ Configure the policy...","","            policy.hybridAppPolicy.set(webRootDomains: [\".example.com\"], forAppId: \"<APP_ID>\")","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C:"}]},{"type":"codeListing","code":["@import HUMAN;","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","    [self startHumanSDK];","    return YES;","}","","- (void)startHumanSDK {","    HSPolicy *policy = [[HSPolicy alloc] init];","    \/\/ Configure the policy...","","    [policy.hybridAppPolicy setWithWebRootDomains:[NSSet setWithObject:@\".example.com\"] forAppId:@\"<APP_ID>\"];","","    NSError *error = nil;","    [HumanSecurity startWithAppId:@\"<APP_ID>\" policy:policy error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"],"syntax":"objc"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"We add our website’s domain to the policy’s web root domain list."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We start the SDK.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"[Android only] We call the "},{"code":"HumanSecurity\/setupWebView(webView:webViewClient:)","type":"codeVoice"},{"type":"text","text":" function with the following parameters:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"code":"webView","type":"codeVoice"},{"type":"text","text":" - the web view we want to setup."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"webViewClient","type":"codeVoice"},{"text":" (optional) - the web view client that we want to set in the web view.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"The SDK creates it own web view client and set it in web view. The SDK will pass all events to your web view client. ","type":"text"},{"inlineContent":[{"text":"DO NOT set the web view client directly","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The SDK enables JavaScript by setting "},{"type":"codeVoice","code":"webView.settings.javaScriptEnabled"},{"type":"text","text":" to "},{"type":"codeVoice","code":"true"},{"type":"text","text":". "},{"type":"strong","inlineContent":[{"type":"text","text":"DO NOT change this setting"}]},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"[iOS only] We call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true,"type":"reference"},{"text":" function with the following parameters:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"webView"},{"text":" - the web view we want to setup.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"navigationDelegate"},{"type":"text","text":" (optional) - the navigation delegate that we want to set in the web view."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"text":"The SDK creates its own web navigation delegate and set it in web view. The SDK will pass all events to your navigation delegate. ","type":"text"},{"inlineContent":[{"text":"DO NOT set the navigation delegate directly","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","level":3,"text":"Apple Pay on the Web","anchor":"Apple-Pay-on-the-Web"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your website uses "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/apple_pay_on_the_web","isActive":true},{"type":"text","text":" you should disable JavaScript evaluation by the SDK. In order to protect the security of Apple Pay transactions in "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":", Apple Pay cannot be used alongside of script injection APIs (relevant for iOS 13-15). You can do this by setting the SDK’s policy. However, if your app is targeting "},{"type":"strong","inlineContent":[{"text":"only","type":"text"}]},{"type":"text","text":" iOS 16 or above, you don’t have to disable JavaScript evaluation by the SDK."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","code":["policy.hybridAppPolicy.allowJavaScriptEvaluation = false"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Objective-C:","type":"text"}]},{"type":"codeListing","code":["policy.hybridAppPolicy.allowJavaScriptEvaluation = NO;"],"syntax":"objc"},{"type":"heading","level":3,"text":"External web views","anchor":"External-web-views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your app uses web views that created outside the native side of the app but are still based on Apple’s "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" or Android’s "},{"type":"codeVoice","code":"WebView"},{"type":"text","text":" (for example, "},{"identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview","type":"reference","isActive":true},{"type":"text","text":"), then you should enable support for them in the SDK’s policy:"}]},{"type":"heading","level":4,"text":"Android","anchor":"Android"},{"type":"paragraph","inlineContent":[{"text":"Kotlin:","type":"text"}]},{"type":"codeListing","code":["policy.hybridAppPolicy.supportExternalWebViews = true"],"syntax":"kotlin"},{"type":"paragraph","inlineContent":[{"text":"Java:","type":"text"}]},{"type":"codeListing","code":["policy.getHybridAppPolicy().setSupportExternalWebViews(true);"],"syntax":"java"},{"type":"heading","level":4,"text":"iOS","anchor":"iOS"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","code":["policy.hybridAppPolicy.supportExternalWebViews = true"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Objective-C:","type":"text"}]},{"type":"codeListing","code":["policy.hybridAppPolicy.supportExternalWebViews = YES;"],"syntax":"objc"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","type":"topic","role":"article","kind":"article","title":"Native - Basic Implementation","url":"\/documentation\/human\/native_basic_implementation"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy/automaticSetup":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticSetup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup","url":"\/documentation\/human\/hshybridapppolicy\/automaticsetup","navigatorTitle":[{"text":"automaticSetup","kind":"identifier"}],"type":"topic","title":"automaticSetup","kind":"symbol","role":"symbol","abstract":[{"text":"When this property is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", the SDK detects all ","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"text":" instances and sets them up for Hybrid App support automatically. As a result, you don’t need to call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","isActive":true,"type":"reference"},{"text":" function. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/setupWebView(webView:navigationDelegate:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupWebView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"navigationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationDelegate","preciseIdentifier":"c:objc(pl)WKNavigationDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Setup the web view to be synced with SDK. Do not set a ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":" to the web view after calling this function.","type":"text"},{"text":" ","type":"text"},{"text":"If you wish to set a web view client, call this function again with the new ","type":"text"},{"code":"WKNavigationDelegate","type":"codeVoice"},{"text":". You should not call this method when the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy\/automaticSetup"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/human\/humansecurity\/setupwebview(webview:navigationdelegate:)","title":"setupWebView(webView:navigationDelegate:)","navigatorTitle":[{"kind":"identifier","text":"setupWebViewWithWebView:navigationDelegate:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/setupWebView(webView:navigationDelegate:)","kind":"symbol","role":"symbol"},"https://github.com/react-native-webview/react-native-webview":{"identifier":"https:\/\/github.com\/react-native-webview\/react-native-webview","type":"link","title":"react-native-webview","titleInlineContent":[{"text":"react-native-webview","type":"text"}],"url":"https:\/\/github.com\/react-native-webview\/react-native-webview"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Advanced_Functionality":{"kind":"article","type":"topic","role":"article","title":"Native - Advanced Functionality","url":"\/documentation\/human\/native_advanced_functionality","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"abstract":[],"url":"\/documentation\/human\/native_easiest_implementation","kind":"article","title":"Native - Easiest Implementation","role":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation"},"https://developer.apple.com/documentation/apple_pay_on_the_web":{"identifier":"https:\/\/developer.apple.com\/documentation\/apple_pay_on_the_web","type":"link","title":"Apple Pay on the Web","titleInlineContent":[{"type":"text","text":"Apple Pay on the Web"}],"url":"https:\/\/developer.apple.com\/documentation\/apple_pay_on_the_web"},"https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller":{"identifier":"https:\/\/developer.apple.com\/documentation\/safariservices\/sfsafariviewcontroller","type":"link","title":"SFSafariViewController","titleInlineContent":[{"code":"SFSafariViewController","type":"codeVoice"}],"url":"https:\/\/developer.apple.com\/documentation\/safariservices\/sfsafariviewcontroller"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/title","op":"replace","value":"automaticSetup"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy~1automaticSetup\/fragments","op":"replace","value":[{"text":"automaticSetup","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/title","op":"replace","value":"setupWebViewWithWebView:navigationDelegate:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1setupWebView(webView:navigationDelegate:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupWebViewWithWebView:navigationDelegate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}