{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Introduction","level":2,"text":"Introduction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The HUMAN Security SDK works by constantly profiling and evaluating device behavior to ensure that the connections to your mobile APIs and services are genuine."}]},{"type":"paragraph","inlineContent":[{"text":"This process is complex and detailed yet only requires initialization of the SDK to manage a set of secure HTTP headers which are added to all HTTP and HTTPS requests made by the mobile application to the origin server. These HTTP headers are refreshed on a regular basis by the SDK as it is profiling the end-user’s mobile device.","type":"text"}]},{"type":"heading","anchor":"Products","level":2,"text":"Products"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK has support for the following products:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Bot Defender","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Account Defender"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","anchor":"Supported-environments","level":2,"text":"Supported environments"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK supports the following environments:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Apple"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"iOS 11 and higher"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"iPadOS 13 and higher"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"visionOS 1 and higher"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"App based on Swift 5.5 and higher"}]}]},{"content":[{"inlineContent":[{"text":"App based on Objective-C","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Android","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Android 5.0 (API level 21) and higher","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"App based on Kotlin 1.6.0 and higher","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"App based on Java"}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"React Native"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Flutter"}]}]},{"content":[{"inlineContent":[{"text":"Ionic","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"gRPC"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Expo","type":"text"}]}]}],"type":"unorderedList"},{"type":"heading","anchor":"SDK-v41","level":2,"text":"SDK v4.1"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The latest SDK v4.1 is built in the following environment:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Android:"}]},{"type":"codeListing","syntax":null,"code":["minSdkVersion 21","targetSdkVersion 35","","jvmTarget = '1.8'","","org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0","org.jetbrains.kotlin:kotlin-stdlib:2.1.0","org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1","org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1","","Minimum Kotlin version: 1.8.20"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple:"}]},{"type":"codeListing","syntax":null,"code":["Swift 5.9.2","iOS 18.2","iPadOS 18.2","visionOS 2.2","Minimum deployments: iOS 12"]},{"type":"heading","level":2,"text":"SDK v4.0","anchor":"SDK-v40"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SDK v4.0 is built in the following environment:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Android:"}]},{"type":"codeListing","syntax":null,"code":["minSdkVersion 21","targetSdkVersion 34","","jvmTarget = '1.8'","","org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0","org.jetbrains.kotlin:kotlin-stdlib:2.0.0","org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1","org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1","","Minimum Kotlin version: 1.8.20"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple:"}]},{"type":"codeListing","syntax":null,"code":["Swift 5.9.2","iOS 17.4","iPadOS 17.4","visionOS 1.2","Minimum deployments: iOS 12"]},{"anchor":"Demo-app","level":2,"text":"Demo app","type":"heading"},{"inlineContent":[{"type":"text","text":"For hands on experience with the SDK, you can follow this "},{"identifier":"https:\/\/github.com\/PerimeterX\/px-mobile-sdk-demo-app","type":"reference","isActive":true},{"type":"text","text":" and download our demo app."}],"type":"paragraph"},{"anchor":"Software-documentation","level":2,"text":"Software documentation","type":"heading"},{"inlineContent":[{"type":"text","text":"The software documentation provides elaborated information on every class, function and member in the SDK. Please choose the relevant SDK version:"}],"type":"paragraph"},{"rows":[[[{"inlineContent":[{"text":"Android","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Apple","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.0\/index.html","isActive":true}],"type":"paragraph"}],[{"inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.0","isActive":true}],"type":"paragraph"}]],[[{"inlineContent":[{"isActive":true,"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.1\/index.html","type":"reference"}],"type":"paragraph"}],[{"inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.1","isActive":true}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.0\/index.html","isActive":true}],"type":"paragraph"}],[{"inlineContent":[{"isActive":true,"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.0","type":"reference"}],"type":"paragraph"}]],[[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.1\/index.html"}],"type":"paragraph"}],[{"inlineContent":[{"isActive":true,"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.1","type":"reference"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.2\/index.html","isActive":true}],"type":"paragraph"}],[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.2"}],"type":"paragraph"}]],[[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.3\/index.html"}],"type":"paragraph"}],[{"inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.2.0","isActive":true}],"type":"paragraph"}]],[[{"inlineContent":[{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.4\/index.html","type":"reference","isActive":true}],"type":"paragraph"}],[{"inlineContent":[],"type":"paragraph"}]],[[{"inlineContent":[{"type":"reference","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.5\/index.html","isActive":true}],"type":"paragraph"}],[{"inlineContent":[],"type":"paragraph"}]],[[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.6\/index.html"}],"type":"paragraph"}],[{"inlineContent":[],"type":"paragraph"}]],[[{"inlineContent":[{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.7\/index.html","isActive":true,"type":"reference"}],"type":"paragraph"}],[{"inlineContent":[],"type":"paragraph"}]]],"header":"row","type":"table"},{"inlineContent":[{"type":"text","text":"Note: For Apple’s platform, follow those steps:."}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Download the source code (zip file)."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unzip the file."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Open the ","type":"text"},{"type":"codeVoice","code":"HUMAN.doccarchive"},{"text":" file with Xcode.","type":"text"}]}]}],"type":"orderedList"},{"anchor":"What-the-SDK-is-doing","level":2,"text":"What the SDK is doing?","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK adds support to our products in your app."}],"type":"paragraph"},{"anchor":"Bot-Defender","level":3,"text":"Bot Defender","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK has 2 objectives to achieve in order to support Bot Defender:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Provide HTTP Headers to your app’s URL requests.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Handle blocked requests and present a challenge to the user."}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Account-Defender","level":3,"text":"Account Defender","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK has 2 objectives to achieve in order to support Account Defender:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Notify HUMAN’s’ backend when a user is logged into the app."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Notify HUMAN’s’ backend on outgoing URL requests from the app.","type":"text"}]}]}],"type":"unorderedList"},{"anchor":"Prerequisites","level":2,"text":"Prerequisites","type":"heading"},{"inlineContent":[{"type":"text","text":"The following are required to install the SDK:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Administrative access to the HUMAN Portal to:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Retrieve the HUMAN application ID (AppID).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Set the token expiration and validity."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An active HUMAN Enforcer."}]}]}],"type":"unorderedList"},{"anchor":"Adding-the-SDK-to-your-project","level":2,"text":"Adding the SDK to your project","type":"heading"},{"anchor":"You-can-add-the-SDK-to-your-project-with-the-following-ways","level":3,"text":"You can add the SDK to your project with the following ways:","type":"heading"},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Android"}],"type":"strong"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Add permissions"}],"type":"strong"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the following permissions to your "},{"type":"codeVoice","code":"AndroidManifest.xml"},{"type":"text","text":" file:"}]},{"type":"codeListing","syntax":"xml","code":["<uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\" \/>","<uses-permission android:name=\"android.permission.INTERNET\" \/>"]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Add the library to your dependencies list"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the SDK repository to the repositories section in your project’s "},{"type":"codeVoice","code":"build.gradle"},{"type":"text","text":" and "},{"type":"codeVoice","code":"settings.gradle"},{"type":"text","text":":"}]},{"type":"paragraph","inlineContent":[{"text":"Groovy:","type":"text"}]},{"type":"codeListing","code":["buildscript {","    repositories {","        google()","        mavenCentral()","        maven { url 'https:\/\/jfrog.humansecurity.com\/artifactory\/human-android-sdk\/' }","    }"],"syntax":"groovy"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"type":"codeListing","code":["buildscript {","    repositories {","        google()","        mavenCentral()","        maven { url = uri(\"https:\/\/jfrog.humansecurity.com\/artifactory\/human-android-sdk\/\") }","    }"],"syntax":"kotlin"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the SDK dependency to the dependencies section in your app’s "},{"code":"build.gradle","type":"codeVoice"},{"type":"text","text":":"}]},{"type":"paragraph","inlineContent":[{"text":"Groovy:","type":"text"}]},{"type":"codeListing","code":["dependencies {","    implementation 'com.humansecurity:sdk:4.1.7'","}"],"syntax":"groovy"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"type":"codeListing","code":["dependencies {","    implementation(\"com.humansecurity:sdk:4.1.7\")","}"],"syntax":"kotlin"},{"type":"paragraph","inlineContent":[{"text":"Alternatively, you can add the SDK’s AAR file manually to you project (instead of using the above method):","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Download the AAR file from this "},{"identifier":"https:\/\/jfrog.humansecurity.com\/ui\/native\/human-android-sdk\/com\/humansecurity\/sdk\/4.1.7","isActive":true,"type":"reference"},{"type":"text","text":" or use the following command line:"}]},{"type":"codeListing","syntax":null,"code":["curl -LO https:\/\/jfrog.humansecurity.com\/artifactory\/human-android-sdk\/com\/humansecurity\/sdk\/msdk\/4.1.7\/msdk-4.1.7.aar"]}]},{"content":[{"inlineContent":[{"type":"text","text":"Put the "},{"type":"codeVoice","code":"HUMAN-release.aar"},{"type":"text","text":" in the libs folder of your project."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Add the local AAR dependency to your app’s "},{"type":"codeVoice","code":"build.gradle"},{"type":"text","text":":"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Groovy:"}],"type":"paragraph"},{"code":["dependencies {","    implementation files('libs\/HUMAN-release.aar')","}"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"Kotlin:","type":"text"}],"type":"paragraph"},{"code":["dependencies {","    implementation(files(\"libs\/HUMAN-release.aar\"))","}"],"type":"codeListing","syntax":null}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add the SDK’s dependencies (below) to the dependencies section in your app’s ","type":"text"},{"type":"codeVoice","code":"build.gradle"},{"text":". You may choose a range of version fo each dependency according to its note.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"SDK v4.1:","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"text":"Groovy:","type":"text"}]},{"syntax":"groovy","code":["implementation 'androidx.core:core-ktx:1.15.0' \/\/ any version (select 1.10.1 if your app has 'targetSdkVersion 33')","implementation 'androidx.lifecycle:lifecycle-process:2.8.7' \/\/ min v2.6.0 (select 2.6.2 if your app has 'targetSdkVersion 33')","implementation 'androidx.datastore:datastore-preferences:1.1.1' \/\/ any version (select 1.0.0 if your app targets API 33)","implementation 'com.google.android.material:material:1.12.0' \/\/ min v1.6.0 (select 1.9.0 if your app has 'targetSdkVersion 33')","implementation 'com.fasterxml.uuid:java-uuid-generator:4.3.0' \/\/ min v3.0.0","implementation 'io.ktor:ktor-client-okhttp:3.0.3' \/\/ min v3.0.0"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"syntax":"kotlin","code":["implementation(\"androidx.core:core-ktx:1.15.0\") \/\/ any version (select 1.10.1 if your app has 'targetSdkVersion 33')","implementation(\"androidx.lifecycle:lifecycle-process:2.8.7\") \/\/ min v2.6.0 (select 2.6.2 if your app has 'targetSdkVersion 33')","implementation(\"androidx.datastore:datastore-preferences:1.1.1\") \/\/ any version (select 1.0.0 if your app targets API 33)","implementation(\"com.google.android.material:material:1.12.0\") \/\/ min v1.6.0 (select 1.9.0 if your app has 'targetSdkVersion 33')","implementation(\"com.fasterxml.uuid:java-uuid-generator:4.3.0\") \/\/ min v3.0.0","implementation(\"io.ktor:ktor-client-okhttp:3.0.3\") \/\/ min v3.0.0"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"SDK v4.0:","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Groovy:"}]},{"syntax":"groovy","code":["implementation 'androidx.core:core-ktx:1.13.1' \/\/ any version (select 1.10.1 if your app has 'targetSdkVersion 33')","implementation 'androidx.lifecycle:lifecycle-process:2.8.2' \/\/ min v2.6.0 (select 2.6.2 if your app has 'targetSdkVersion 33')","implementation 'androidx.datastore:datastore-preferences:1.1.1' \/\/ any version (select 1.0.0 if your app targets API 33)","implementation 'com.google.android.material:material:1.12.0' \/\/ min v1.6.0 (select 1.9.0 if your app has 'targetSdkVersion 33')","implementation 'com.fasterxml.uuid:java-uuid-generator:4.3.0' \/\/ min v3.0.0","implementation 'io.ktor:ktor-client-okhttp:2.3.11' \/\/ min v2.2.1"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"syntax":"kotlin","code":["implementation(\"androidx.core:core-ktx:1.13.1\") \/\/ any version (select 1.10.1 if your app has 'targetSdkVersion 33')","implementation(\"androidx.lifecycle:lifecycle-process:2.8.2\") \/\/ min v2.6.0 (select 2.6.2 if your app has 'targetSdkVersion 33')","implementation(\"androidx.datastore:datastore-preferences:1.1.1\") \/\/ any version (select 1.0.0 if your app targets API 33)","implementation(\"com.google.android.material:material:1.12.0\") \/\/ min v1.6.0 (select 1.9.0 if your app has 'targetSdkVersion 33')","implementation(\"com.fasterxml.uuid:java-uuid-generator:4.3.0\") \/\/ min v3.0.0","implementation(\"io.ktor:ktor-client-okhttp:2.3.11\") \/\/ min v2.2.1"],"type":"codeListing"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Issue with R8"}]}]},{"type":"paragraph","inlineContent":[{"text":"R8 is a tool that is used to shrink, secure, and optimize Android applications.","type":"text"},{"text":" ","type":"text"},{"text":"When using this tool it could sometimes cause an issue with ","type":"text"},{"code":"ktor","type":"codeVoice"},{"text":" library which is included in the SDK.","type":"text"},{"text":" ","type":"text"},{"text":"To prevent this issue, we recommend adding the following rule in your ","type":"text"},{"code":"proguard","type":"codeVoice"},{"text":" file:","type":"text"}]},{"type":"codeListing","code":["-keepclassmembers class kotlinx.** {","    volatile <fields>;","}"],"syntax":null}]}],"type":"orderedList"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Apple","type":"text"}]}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Swift Package Manager"}],"type":"strong"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the package from the following repository: "},{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"CocoaPods"}],"type":"strong"}],"type":"paragraph"},{"inlineContent":[{"text":"Add the ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/cocoapods.org\/pods\/HUMAN"},{"text":" to your Podfile:","type":"text"}],"type":"paragraph"},{"syntax":null,"type":"codeListing","code":["platform :ios, '12.0'","use_frameworks!","","target '<Your App Name>' do","    pod 'HUMAN', '4.2.0'","end"]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Add the "},{"type":"codeVoice","code":"xcframework"},{"type":"text","text":" file manually"}],"type":"strong"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Open the SDK "},{"type":"reference","isActive":true,"overridingTitle":"repository","overridingTitleInlineContent":[{"type":"text","text":"repository"}],"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Download the content of the repository."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Unzip the file and copy the "},{"type":"codeVoice","code":"HUMAN.xcframework"},{"type":"text","text":" file to your project."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, add the "},{"type":"codeVoice","code":"xcframework"},{"type":"text","text":" to the “Frameworks, Libraries, and Embedded Content” section of your target."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"ios-manual"}]}]}],"type":"orderedList"}]}],"type":"unorderedList"}]}],"type":"unorderedList"},{"anchor":"Next-steps","level":2,"text":"Next steps","type":"heading"},{"inlineContent":[{"type":"text","text":"Choose relevant articles according to your environment and requirements:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Native"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","type":"reference","overridingTitle":"Easiest implementation","overridingTitleInlineContent":[{"type":"text","text":"Easiest implementation"}],"isActive":true},{"text":" (RECOMMENDED)","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The faster way to integrate the SDK - minimum integration points."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK intercepts your URL requests.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle blocked requests."}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"NOT","type":"text"}]},{"type":"text","text":" recommended if you want to retry your requests after the challenge was solved."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"NOT","type":"text"}],"type":"strong"},{"text":" recommended if you use advanced features in ","type":"text"},{"type":"codeVoice","code":"URLSession"},{"text":" (authentication challenge handling, caching, etc.)","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"overridingTitle":"Basic implementation","isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","overridingTitleInlineContent":[{"type":"text","text":"Basic implementation"}]}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Few points of integration."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle blocked requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Get notified when a challenge was solved\/cancelled.","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Great for analytics, logs, etc."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"NOT"}]},{"type":"text","text":" recommended if you want to retry your requests after the challenge was solved."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"NOT","type":"text"}],"type":"strong"},{"type":"text","text":" recommended to use as a trigger for sending the URL request again."}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK "},{"type":"strong","inlineContent":[{"type":"text","text":"does not"}]},{"type":"text","text":" intercept your URL requests."}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"Advanced functionality"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","overridingTitle":"Advanced functionality"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle blocked requests "},{"type":"strong","inlineContent":[{"text":"with the challenge result","type":"text"}]},{"type":"text","text":" (solved\/cancelled)."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Great for analytics, logs, etc."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Great for sending the URL request again.","type":"text"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Option to retry the blocked request automatically after the challenge was solved."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK intercepts your URL requests."}]}]},{"content":[{"inlineContent":[{"text":"Recommended if you want to retry your requests after the challenge was solved.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"NOT","type":"text"}],"type":"strong"},{"type":"text","text":" recommended if you use advanced features in "},{"code":"URLSession","type":"codeVoice"},{"type":"text","text":" (authentication challenge handling, caching, etc.)"}]}]}]}]},{"content":[{"inlineContent":[{"text":"visionOS:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"overridingTitleInlineContent":[{"text":"Challenge presentation via window","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","type":"reference","isActive":true,"overridingTitle":"Challenge presentation via window"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","isActive":true,"overridingTitle":"Challenge presentation via sheet","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Challenge presentation via sheet"}]}]}]}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"text":"Hybrid App","type":"text"}],"overridingTitle":"Hybrid App","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Additional integration that required for an app that uses a web view to communicate with your server."}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitle":"React Native","type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","overridingTitleInlineContent":[{"type":"text","text":"React Native"}]}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Flutter"}],"overridingTitle":"Flutter","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"overridingTitle":"Ionic","type":"reference","overridingTitleInlineContent":[{"text":"Ionic","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","isActive":true,"overridingTitle":"gRPC","overridingTitleInlineContent":[{"type":"text","text":"gRPC"}],"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Expo","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Multiple-App-IDs","level":2,"text":"Multiple App IDs","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK supports multiple App IDs which relevant when your app communicates with multiple servers that are protected by HUMAN and have different App IDs."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"In order to support multiple App IDs, you should:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Call the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference"},{"text":" function and provide all of your App IDs.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Pass the relevant App ID to each function that has the "},{"code":"appId","type":"codeVoice"},{"type":"text","text":" in its parameters. For single AppID apps, the value may be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"orderedList"},{"anchor":"How-to-verify-the-SDK-integration-in-your-app","level":2,"text":"How to verify the SDK integration in your app","type":"heading"},{"inlineContent":[{"text":"Use our ","type":"text"},{"overridingTitle":"integration verification tool","isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App","overridingTitleInlineContent":[{"text":"integration verification tool","type":"text"}]},{"text":" in order to verify the SDK integration in your app.","type":"text"}],"type":"paragraph"},{"anchor":"How-to-test-the-SDK-in-your-app","level":2,"text":"How to test the SDK in your app","type":"heading"},{"inlineContent":[{"type":"text","text":"Read the "},{"overridingTitleInlineContent":[{"text":"test the SDK in your app","type":"text"}],"type":"reference","overridingTitle":"test the SDK in your app","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App"},{"type":"text","text":" article in order to learn how to test SDK integration in your app."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","metadata":{"modules":[{"name":"HUMAN"}],"role":"article","roleHeading":"Article","title":"Integration Guide"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/integration_guide"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/integration_guide"]}],"sections":[],"references":{"ios-manual":{"variants":[{"url":"\/images\/com.perimeterx.mobile-sdk\/ios-manual.png","traits":["1x","light"]}],"identifier":"ios-manual","type":"image","alt":null},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/React_Native_Integration":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","role":"article","title":"React Native Integration","kind":"article","url":"\/documentation\/human\/react_native_integration"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.1.1":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.1","titleInlineContent":[{"type":"text","text":"4.1.1"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.1","title":"4.1.1","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.0/index.html":{"type":"link","titleInlineContent":[{"text":"4.1.0","type":"text"}],"title":"4.1.0","url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.0\/index.html","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.0\/index.html"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.0.1/index.html":{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.1\/index.html","titleInlineContent":[{"type":"text","text":"4.0.1"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.1\/index.html","title":"4.0.1","type":"link"},"https://cocoapods.org/pods/HUMAN":{"type":"link","titleInlineContent":[{"text":"HUMAN pod","type":"text"}],"title":"HUMAN pod","url":"https:\/\/cocoapods.org\/pods\/HUMAN","identifier":"https:\/\/cocoapods.org\/pods\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_Verify_the_SDK_Integration_in_Your_App":{"type":"topic","url":"\/documentation\/human\/how_to_verify_the_sdk_integration_in_your_app","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App","abstract":[],"title":"How to Verify the SDK Integration in Your App","role":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_Test-the_SDK-in_Your_App":{"type":"topic","kind":"article","role":"article","url":"\/documentation\/human\/how_to_test-the_sdk-in_your_app","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App","title":"How to Test the SDK in Your App","abstract":[{"text":"Testing the SDK integration in your app is essential to ensure the best experience for your users.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Flutter_Integration":{"title":"Flutter Integration","url":"\/documentation\/human\/flutter_integration","kind":"article","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","type":"topic","role":"article"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.6/index.html":{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.6\/index.html","title":"4.1.6","titleInlineContent":[{"text":"4.1.6","type":"text"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.6\/index.html","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk","title":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk","titleInlineContent":[{"text":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.2.0":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.2.0","title":"4.2.0","titleInlineContent":[{"text":"4.2.0","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.2.0","type":"link"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Advanced_Functionality":{"abstract":[],"role":"article","title":"Native - Advanced Functionality","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","kind":"article","type":"topic","url":"\/documentation\/human\/native_advanced_functionality"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Hybrid_App_Integration":{"title":"Hybrid App Integration","kind":"article","url":"\/documentation\/human\/hybrid_app_integration","abstract":[],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration","role":"article"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.3/index.html":{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.3\/index.html","title":"4.1.3","titleInlineContent":[{"text":"4.1.3","type":"text"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.3\/index.html","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.1.0":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.0","title":"4.1.0","titleInlineContent":[{"text":"4.1.0","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.0","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.0.0/index.html":{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.0\/index.html","title":"4.0.0","titleInlineContent":[{"text":"4.0.0","type":"text"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.0.0\/index.html","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.0.0":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.0","title":"4.0.0","titleInlineContent":[{"text":"4.0.0","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.0","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.0.1":{"identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.1","title":"4.0.1","titleInlineContent":[{"text":"4.0.1","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.0.1","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.1/index.html":{"identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.1\/index.html","title":"4.1.1","titleInlineContent":[{"text":"4.1.1","type":"text"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.1\/index.html","type":"link"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"kind":"article","title":"Native - Basic Implementation","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","url":"\/documentation\/human\/native_basic_implementation","abstract":[],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"title":"Native - Easiest Implementation","kind":"article","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","url":"\/documentation\/human\/native_easiest_implementation","abstract":[],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_sheet":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","role":"article","abstract":[],"url":"\/documentation\/human\/visionos_integration_sheet","title":"visionOS Integration (sheet)","kind":"article","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"title":"start(appIds:policy:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/gRPC_Integration":{"title":"gRPC Integration","kind":"article","url":"\/documentation\/human\/grpc_integration","abstract":[],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","role":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","role":"article","abstract":[],"url":"\/documentation\/human\/visionos_integration_window","title":"visionOS Integration (window)","kind":"article","type":"topic"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.2/index.html":{"titleInlineContent":[{"type":"text","text":"4.1.2"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.2\/index.html","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.2\/index.html","title":"4.1.2","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.5/index.html":{"titleInlineContent":[{"text":"4.1.5","type":"text"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.5\/index.html","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.5\/index.html","title":"4.1.5","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.4/index.html":{"titleInlineContent":[{"type":"text","text":"4.1.4"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.4\/index.html","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.4\/index.html","title":"4.1.4","type":"link"},"https://jfrog.humansecurity.com/ui/native/human-android-sdk/com/humansecurity/sdk/4.1.7":{"titleInlineContent":[{"text":"link","type":"text"}],"url":"https:\/\/jfrog.humansecurity.com\/ui\/native\/human-android-sdk\/com\/humansecurity\/sdk\/4.1.7","identifier":"https:\/\/jfrog.humansecurity.com\/ui\/native\/human-android-sdk\/com\/humansecurity\/sdk\/4.1.7","title":"link","type":"link"},"https://github.com/PerimeterX/px-mobile-sdk-demo-app":{"titleInlineContent":[{"type":"text","text":"link"}],"url":"https:\/\/github.com\/PerimeterX\/px-mobile-sdk-demo-app","identifier":"https:\/\/github.com\/PerimeterX\/px-mobile-sdk-demo-app","title":"link","type":"link"},"https://github.com/PerimeterX/human-security-ios-sdk/releases/tag/4.1.2":{"titleInlineContent":[{"text":"4.1.2","type":"text"}],"url":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.2","identifier":"https:\/\/github.com\/PerimeterX\/human-security-ios-sdk\/releases\/tag\/4.1.2","title":"4.1.2","type":"link"},"https://mobile-docs.perimeterx.com/human-android-sdk/v4.1.7/index.html":{"titleInlineContent":[{"type":"text","text":"4.1.7"}],"url":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.7\/index.html","identifier":"https:\/\/mobile-docs.perimeterx.com\/human-android-sdk\/v4.1.7\/index.html","title":"4.1.7","type":"link"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Ionic_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","role":"article","url":"\/documentation\/human\/ionic_integration","abstract":[],"title":"Ionic Integration","kind":"article","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"startWithAppIds:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}