{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"article","modules":[{"name":"HUMAN"}],"title":"Ionic Integration","roleHeading":"Article"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/ionic_integration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/ionic_integration"]}],"kind":"article","sections":[],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Intro","type":"heading","anchor":"Intro"},{"inlineContent":[{"type":"text","text":"The SDK can be integrated into a "},{"identifier":"https:\/\/ionicframework.com\/","type":"reference","isActive":true},{"type":"text","text":" project."}],"type":"paragraph"},{"anchor":"How-to-start-the-SDK","type":"heading","text":"How to start the SDK","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"Application","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"onCreate","type":"codeVoice"},{"type":"text","text":" function on Android."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"AppDelegate","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"didFinishLaunchingWithOptions","type":"codeVoice"},{"type":"text","text":" function on iOS."}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should start the SDK on the "},{"type":"strong","inlineContent":[{"text":"main thread","type":"text"}]},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"Create a ","type":"text"},{"type":"codeVoice","code":"HumanManager"},{"text":" object that will handle calls from Ionic side.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"anchor":"Android","level":3,"type":"heading","text":"Android"},{"type":"paragraph","inlineContent":[{"text":"Java \/ MainApplication.java:","type":"text"}]},{"type":"codeListing","syntax":"java","code":["import android.app.Application;","","public class MainApplication extends Application {","","    @Override","    public void onCreate() {","        super.onCreate();","        HumanManager.startHumanSDK(this);","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Java \/ HumanManager.kt:"}]},{"syntax":"java","code":["import android.app.Application;","import com.getcapacitor.JSObject;","import com.getcapacitor.Plugin;","import com.getcapacitor.PluginCall;","import com.getcapacitor.PluginMethod;","import com.getcapacitor.annotation.CapacitorPlugin;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.policy.HSPolicy;","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType;","import com.humansecurity.mobile_sdk.main.HSBotDefenderChallengeResult","import java.util.HashMap;","import android.util.Log;","","@CapacitorPlugin(name = \"Human\")","public class HumanManager extends Plugin {","","    String strSolved = \"solved\";","    String strCancelled = \"cancelled\";","    String strFalse = \"false\";","    String strValue = \"value\";","","    static void startHumanSDK(Application application) {","        HSPolicy policy = new HSPolicy();","        policy.getAutomaticInterceptorPolicy().setInterceptorType(HSAutomaticInterceptorType.NONE);","        try {","            HumanSecurity.INSTANCE.start(application, \"<APP_ID>\", policy);","        }","        catch (Exception exception) {","            Log.e(\"HumanManager\",\"Exception: \" + exception.getMessage());","        }","    }","","    @PluginMethod()","    public void getHttpHeaders(PluginCall call) {","        HashMap headers = HumanSecurity.INSTANCE.getBD().headersForURLRequest(\"<APP_ID>\");","        JSObject ret = new JSObject();","        for (Object key : headers.keySet()) {","            ret.put((String)key, headers.get(key));","        }","        call.resolve(ret);","    }","","    @PluginMethod()","    public void handleResponse(PluginCall call) {","        String response = call.getString(strValue);","        JSObject ret = new JSObject();","        boolean handled = HumanSecurity.INSTANCE.getBD().handleResponse(response, null, result -> {","            ret.put(strValue, result == HSBotDefenderChallengeResult.SOLVED ? strSolved : strCancelled);","            call.resolve(ret);","            return null;","        });","        if (!handled) {","            ret.put(strValue, strFalse);","            call.resolve(ret);","        }","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Java \/ MainActivity.java:"}],"type":"paragraph"},{"type":"codeListing","code":["import android.os.Bundle;","import com.getcapacitor.BridgeActivity;","","public class MainActivity extends BridgeActivity {","","    @Override","    protected void onCreate(Bundle savedInstanceState) {","        registerPlugin(HumanManager.class);","        super.onCreate(savedInstanceState);","    }","}"],"syntax":"java"},{"type":"heading","anchor":"iOS","text":"iOS","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift \/ AppDelegate.swift:"}]},{"type":"codeListing","code":["import UIKit","import Capacitor","","@UIApplicationMain","class AppDelegate: UIResponder, UIApplicationDelegate {","","    var window: UIWindow?","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        HumanManagerPlugin.shared.start()","        return true","    }","","    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {","        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)","    }","","    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {","        return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Swift \/ HumanManager.swift:","type":"text"}]},{"type":"codeListing","code":["import Foundation","import Capacitor","import HUMAN","","@objc(HumanManagerPlugin)","class HumanManagerPlugin: CAPPlugin {","    ","    let strSolved = \"solved\"","    let strCancelled = \"cancelled\"","    let strFalse = \"false\"","    let strValue = \"value\"","    ","    static let shared = HumanManagerPlugin()","    ","    func start() {","        do {","            let policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = .none","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","    ","    @objc func getHttpHeaders(_ call: CAPPluginCall) {","        call.resolve(HumanSecurity.BD.headersForURLRequest(forAppId: \"<APP_ID>\"))","    }","    ","    @objc func handleResponse(_ call: CAPPluginCall) {","        let response = call.getString(strValue) ?? \"\"","        let data = response.data(using: .utf8)","        let httpURLResponse = HTTPURLResponse(url: URL(string: \"https:\/\/example.com\")!, statusCode: 403, httpVersion: nil, headerFields: nil)","        let handled = HumanSecurity.BD.handleResponse(response: httpURLResponse!, data: data!) { challengeResult in","            call.resolve([self.strValue: challengeResult == .solved ? self.strSolved : self.strCancelled])","        }","        if !handled {","            call.resolve([strValue: strFalse])","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C \/ HumanManagerPlugin.m:"}]},{"type":"codeListing","code":["#import <Foundation\/Foundation.h>","#import <Capacitor\/Capacitor.h>","","CAP_PLUGIN(HumanManagerPlugin, \"HUMAN\",","    CAP_PLUGIN_METHOD(getHttpHeaders, CAPPluginReturnPromise);","    CAP_PLUGIN_METHOD(handleResponse, CAPPluginReturnPromise);",")"],"syntax":"objc"},{"type":"paragraph","inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We start the SDK as soon as possible and on the main thread."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"We create a "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"reference","isActive":true},{"type":"text","text":" instance. This object is used to configure the SDK’s behavior. Here, we set the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","isActive":true,"type":"reference"},{"type":"text","text":" property to "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true,"type":"reference"},{"type":"text","text":". This means that the "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Automatic Interception"}]},{"type":"text","text":" feature of the SDK is disabled. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. However, this feature is not supported in Ionic."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"reference","isActive":true},{"type":"text","text":" function of the SDK. We provide the following parameters:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"Application","type":"codeVoice"},{"text":" instance (Android only).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Your AppID.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The policy object that we configured."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We send the response from the Ionic to the native side.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"We call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","type":"reference","isActive":true},{"text":" function. This function will present a challenge to the user when the provided response is a blocked response.","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Note: If your app communicates with several servers that have different AppID, you can call the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},{"type":"text","text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK."}],"type":"paragraph"},{"level":2,"type":"heading","text":"How to add HTTP headers and handle block response","anchor":"How-to-add-HTTP-headers-and-handle-block-response"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In your Javascript code, you should do the following:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Export the ","type":"text"},{"code":"HumanManager","type":"codeVoice"},{"text":" plugin.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add The SDK’s HTTP headers to your URL requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a request is blocked, send the block response to the SDK."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Handle the challenge’s result."}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Javascript:"}]},{"syntax":"javascript","type":"codeListing","code":["import { registerPlugin } from '@capacitor\/core';","","export interface HumanPlugin {","    getHttpHeaders():Promise<{ value: string }>;","    handleResponse(value : any):Promise<{ value: string }>;","}","","const Human = registerPlugin<HumanPlugin>('HUMAN');","","const sendUrlRequest = async () => {","    const result = await Human.getHttpHeaders()","    const json = JSON.parse(JSON.stringify(result))","    const map = new Map(Object.entries(json))","","    var xhr = new XMLHttpRequest()","    xhr.addEventListener('load', async () => {","        const challengeResult = await Human.handleResponse({ \"value\": xhr.responseText })","        const challengeResultJson = JSON.parse(JSON.stringify(challengeResult))","        const challengeResultMap = new Map(Object.entries(challengeResultJson))","        console.log(\"challenge result = \", challengeResultMap.get(\"value\"))","    })","    xhr.open('GET', 'https:\/\/example.com')","    for (const [key, value] of map) {","        xhr.setRequestHeader(key, value as string)","    }","    xhr.send()","};"]},{"level":2,"anchor":"Understanding-the-block-response","text":"Understanding the block response","type":"heading"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"The HUMAN’s Enforcer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:","type":"text"}],"type":"paragraph"},{"syntax":"json","type":"codeListing","code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON contains metadata for the SDK.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Your app should pass the whole JSON to the SDK via the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)"},{"text":" function. Otherwise, the SDK won’t present a challenge to the user.","type":"text"}]}]}]}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"startWithAppId:policy:error:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"title":"start(appIds:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype","title":"interceptorType","navigatorTitle":[{"kind":"identifier","text":"interceptorType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptorType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType","kind":"typeIdentifier","text":"HSAutomaticInterceptorType"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/none","title":"HSAutomaticInterceptorType.none","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"role":"symbol","type":"topic","url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","title":"handleResponse(response:data:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"This function handles the URL request’s response and presents the block screen, if necessary.","type":"text"}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"kind":"symbol"},"https://ionicframework.com/":{"type":"link","identifier":"https:\/\/ionicframework.com\/","titleInlineContent":[{"text":"Ionic","type":"text"}],"title":"Ionic","url":"https:\/\/ionicframework.com\/"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","title":"HSPolicy","type":"topic","role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","op":"replace","value":"startWithAppId:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","op":"replace","value":"startWithAppIds:policy:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title","value":"interceptorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","value":[{"kind":"identifier","text":"interceptorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"value":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments"},{"value":"handleResponseWithResponse:data:callback:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}