{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"primaryContentSections":[{"content":[{"level":2,"text":"Introduction","anchor":"Introduction","type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"In this article we will learn how integrate the SDK to your native iOS\/Android app."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Highlights:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle blocked requests "},{"inlineContent":[{"text":"with the challenge result","type":"text"}],"type":"strong"},{"type":"text","text":" (solved\/cancelled)."}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Great for analytics, logs, etc."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Great for sending the URL request again."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"Option to retry the blocked request automatically after the challenge was solved."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK intercepts your URL requests.","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Note that the Android implementation requires that your app use ","type":"text"},{"identifier":"https:\/\/square.github.io\/okhttp\/","isActive":true,"type":"reference"},{"text":" which supports ","type":"text"},{"identifier":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/","isActive":true,"type":"reference"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Note that the iOS implementation requires that your app use ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","isActive":true,"type":"reference"},{"text":" or any 3rd party library that based on it","type":"text"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We will cover the following topics:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"#how-to-start-the-sdk","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"#bot-defender-integration","isActive":true,"type":"reference"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to add the SDK’s HTTP headers to your URL requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to present a challenge to the user."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to handle the challenge’s result."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to set custom parameters (optional)."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"identifier":"#account-defender-integration","isActive":true,"type":"reference"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to enable it."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"How to notify HUMAN’s backend on outgoing URL requests from the app."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"How to set additional data (optional)."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"type":"unorderedList"},{"anchor":"How-to-start-the-SDK","text":"How to start the SDK","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason is that when your app will send an URL request to your server before the SDK was started, then the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"Application","type":"codeVoice"},{"text":"’s ","type":"text"},{"code":"onCreate","type":"codeVoice"},{"text":" function on Android.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"AppDelegate","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"didFinishLaunchingWithOptions","type":"codeVoice"},{"type":"text","text":" function on iOS."}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"text":"You should start the SDK on the ","type":"text"},{"inlineContent":[{"type":"text","text":"main thread"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK is intercepting URL requests from your app. Your app should tell the SDK which domains are intercepted. Not specifying domains means that ALL domains will be intercepted. The SDK checks if the URL’s domain ends with one of the domains that were set. For example: If you set ","type":"text"},{"code":"example.com","type":"codeVoice"},{"text":" the SDK will also intercept calls to ","type":"text"},{"code":"www.example.com","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"api.example.com","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"level":3,"text":"Android","anchor":"Android","type":"heading"},{"inlineContent":[{"text":"Kotlin:","type":"text"}],"type":"paragraph"},{"code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.policy.HSPolicy","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        startHumanSDK()","    }","","    private fun startHumanSDK() {","        try {","            val policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorType.INTERCEPT_WITH_DELAYED_RESPONSE \/\/ or INTERCEPT_AND_RETRY_REQUEST","            policy.automaticInterceptorPolicy.setInterceptedDomains(setOf(\"example.com\"), \"<APP_ID>\")","","            HumanSecurity.start(this, \"<APP_ID>\", policy)","        }","        catch (exception: Exception) {","            println(\"Exception: ${exception.message}\")","        }","    }","}"],"type":"codeListing","syntax":"kotlin"},{"inlineContent":[{"text":"Java:","type":"text"}],"type":"paragraph"},{"code":["import android.app.Application;","import android.util.Log;","import java.util.HashSet;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.policy.HSPolicy;","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType;","","public class MainApplication extends Application {","","    @Override","    public void onCreate() {","        super.onCreate();","        startHumanSDK();","    }","","    void startHumanSDK() {","        try {","            HSPolicy policy = new HSPolicy();","            policy.getAutomaticInterceptorPolicy().setInterceptorType(HSAutomaticInterceptorType.INTERCEPT_WITH_DELAYED_RESPONSE); \/\/ or INTERCEPT_AND_RETRY_REQUEST","","            HashSet<String> domains = new HashSet<>();","            domains.add(\"example.com\");","            policy.getAutomaticInterceptorPolicy().setInterceptedDomains(domains, \"<APP_ID>\");","","            HumanSecurity.INSTANCE.start(this, \"<APP_ID>\", policy);","        }","        catch (Exception exception) {","            Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","        }","    }","}"],"type":"codeListing","syntax":"java"},{"level":3,"text":"iOS","anchor":"iOS","type":"heading"},{"inlineContent":[{"text":"Swift:","type":"text"}],"type":"paragraph"},{"code":["import UIKit","import HUMAN","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        startHumanSDK()","        return true","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = .interceptWithDelayedResponse \/\/ or interceptAndRetryRequest","            policy.automaticInterceptorPolicy.set(interceptedDomains: [\"example.com\"], forAppId: \"<APP_ID>\")","            HSAutomaticInterceptorPolicy.urlSessionRequestTimeout = 10 \/\/ Set the timeout you would like for your requests.","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"code":["@import HUMAN;","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","    [self startHumanSDK];","    return YES;","}","","- (void)startHumanSDK {","    HSPolicy *policy = [[HSPolicy alloc] init];","    policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorTypeInterceptWithDelayedResponse; \/\/ or HSAutomaticInterceptorTypeInterceptAndRetryRequest","    [policy.automaticInterceptorPolicy setWithInterceptedDomains:[NSSet setWithObject:@\"example.com\"] forAppId:@\"<APP_ID>\"];","    HSAutomaticInterceptorPolicy.urlSessionRequestTimeout = 10; \/\/ Set the timeout you would like for your requests.","","    NSError *error = nil;","    [HumanSecurity startWithAppId:@\"<APP_ID>\" policy:policy error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}","","@end"],"type":"codeListing","syntax":"objc"},{"inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"We start the SDK as soon as possible and on the main thread.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We create a ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","type":"reference","isActive":true},{"text":" instance. This object is used to configure the SDK’s behavior. Here, we set the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","isActive":true,"type":"reference"},{"text":" property to ","type":"text"},{"code":"interceptWithDelayedResponse","type":"codeVoice"},{"type":"text","text":" (or "},{"type":"codeVoice","code":"interceptAndRetryRequest"},{"type":"text","text":"). This will turn on the "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Automatic Interception"}]},{"type":"text","text":" feature of the SDK. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. We also set our server’s domain. This will tell the SDK to intercept URL requests only for this domain."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true,"type":"reference"},{"text":" function of the SDK. We provide the following parameters:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Application"},{"type":"text","text":" instance (Android only)."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Your AppID."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The policy object that we configured.","type":"text"}]}]}]}]}],"type":"orderedList"},{"inlineContent":[{"type":"text","text":"Note: In iOS, The Automatic Interception uses the "},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"text":" to send your URL request. However, if your app uses a custom configuration, you should set your configuration in the policy - ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Note: If your app communicates with several servers that have different AppID, you can call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference","isActive":true},{"text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK.","type":"text"}],"type":"paragraph"},{"text":"Bot Defender integration","type":"heading","anchor":"Bot-Defender-integration","level":2},{"level":3,"text":"How to add the SDK’s HTTP headers to your URL requests and handle the blocked request","anchor":"How-to-add-the-SDKs-HTTP-headers-to-your-URL-requests-and-handle-the-blocked-request","type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The SDK adds its HTTP headers to your URL requests automatically. There is no need to manually add those headers."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK handles the blocked request and presents a challenge to the user automatically.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The SDK provides a custom error response directly to your request handler. "},{"type":"strong","inlineContent":[{"type":"text","text":"This error is provided after the challenge is solved or cancelled"}]},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"You should disable your URL request’s timeout. This is necessary because the HTTP client could trigger a timeout error before the user solved the challenge."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"In iOS you will need to set the request timeout to 0, you can set the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout","isActive":true,"type":"reference"},{"type":"text","text":" to the timeout you would like the SDK to set for your request."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"In Android set call\/request timeout to 0 (witch is also the default value), you can set the connectTimeout and the read\/write timeout or socketTimeout in the different okHttp libraries.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"type":"heading","level":4,"anchor":"Android","text":"Android"},{"inlineContent":[{"type":"text","text":"Kotlin (OkHttp):"}],"type":"paragraph"},{"type":"codeListing","syntax":"kotlin","code":["import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.HSBotDefenderErrorType","import com.humansecurity.mobile_sdk.main.HSInterceptor","import okhttp3.OkHttpClient","import okhttp3.Request","import java.util.concurrent.TimeUnit","","class MyHttpClient {","","    private val okHttpClient: OkHttpClient = OkHttpClient.Builder()","        .callTimeout(0, TimeUnit.SECONDS)  ","        .addInterceptor(HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","        .build()","","    fun sendRequest(url: String) {","        try {","            val request: Request = Request.Builder().url(url).build()","            okHttpClient.newCall(request).execute().use { response ->","                if (!response.isSuccessful) {","                    response.body?.string()?.let { responseBody ->","                        when (HumanSecurity.BD.errorType(responseBody)) {","                            HSBotDefenderErrorType.CHALLENGE_WAS_SOLVED -> {","                                println(\"Challenge was solved\")","                            }","                            HSBotDefenderErrorType.CHALLENGE_WAS_CANCELLED -> {","                                println(\"Challenge was cancelled\")","                            }","                            else -> {","                                println(\"Unknown error\")","                            }","                        }","                    }","                }","            }","        } catch (exception: Exception) {","            println(\"Request was failed. Exception: $exception\")","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin (ktor):"}]},{"type":"codeListing","syntax":"kotlin","code":["import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.HSBotDefenderErrorType","import com.humansecurity.mobile_sdk.main.HSInterceptor","import io.ktor.client.*","import io.ktor.client.call.body","import io.ktor.client.engine.okhttp.*","import io.ktor.client.plugins.HttpTimeout","import io.ktor.client.request.*","import io.ktor.client.statement.*","","class MyHttpClient {","","    private val httpClient: HttpClient = HttpClient(OkHttp) {","        install(HttpTimeout) {","            requestTimeoutMillis = HttpTimeout.INFINITE_TIMEOUT_MS  ","        }","        engine {","            addInterceptor(HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","        }","    }","","    suspend fun sendRequest(url: String) {","        try {","            val response: HttpResponse = httpClient.request(url) {}","            val responseBody = response.body<String>()","            when (HumanSecurity.BD.errorType(responseBody)) {","                HSBotDefenderErrorType.CHALLENGE_WAS_SOLVED -> {","                    println(\"Challenge was solved\")","                }","                HSBotDefenderErrorType.CHALLENGE_WAS_CANCELLED -> {","                    println(\"Challenge was cancelled\")","                }","                else -> {","                    println(\"Unknown error\")","                }","            }","        } catch (exception: Exception) {","            println(\"Request was failed. Exception: $exception\")","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Java:","type":"text"}]},{"type":"codeListing","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.HSInterceptor;","import android.util.Log;","import okhttp3.OkHttpClient;","import okhttp3.Request;","import okhttp3.Response;","import okhttp3.ResponseBody;","import java.util.concurrent.TimeUnit;","","public class MyHttpClient {","","    private final OkHttpClient httpClient = new OkHttpClient.Builder()","            .callTimeout(0, TimeUnit.SECONDS) ","            .addInterceptor(new HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","            .build();","","    void sendRequest(String url) {","        Runnable r = () -> {","            try {","                Request request = new Request.Builder().url(url).build();","                Response response = httpClient.newCall(request).execute();","                ResponseBody responseBody = response.body();","                String responseString = null;","                if (responseBody != null) {","                    responseString = responseBody.string();","                    response.close();","                }","                if (!response.isSuccessful() && responseString != null) {","                    switch (HumanSecurity.INSTANCE.getBD().errorType(responseString)) {","                        case CHALLENGE_WAS_SOLVED:","                            Log.i(\"MyHttpClient\", \"Challenge was solved\");","                            break;","                        case CHALLENGE_WAS_CANCELLED:","                            Log.i(\"MyHttpClient\", \"Challenge was cancelled\");","                            break;","                    }","                }","            }","            catch (Exception exception) {","                Log.i(\"MyHttpClient\", \"Request was failed. Exception: \" + exception);","            }","        };","        new Thread(r).start();","    }","}"],"syntax":"java"},{"level":4,"text":"iOS","anchor":"iOS","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Using "},{"type":"reference","overridingTitleInlineContent":[{"code":"URLSession","type":"codeVoice"}],"overridingTitle":"URLSession","identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","isActive":true},{"text":":","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"code":["import HUMAN","","class MyHttpClient {","","    func sendUrlRequest(url: URL) {","        var request = URLRequest(url: url)","        request.timeoutInterval = 0","        ","        \/\/ Config your request...","","        let dataTask = URLSession.shared.dataTask(with: request) { data, response, error in","            if let error {","                let errorType = HumanSecurity.BD.errorType(error: error)","                switch errorType {","                case .challengeWasSolved:","                    print(\"Challenge was solved\")","                case .challengeWasCancelled:","                    print(\"Challenge was cancelled\")","                default:","                    print(\"Unknown error\")","                    break","                }","            }","        }","        dataTask.resume()","    }","}",""],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Objective-C:"}],"type":"paragraph"},{"type":"codeListing","code":["@import HUMAN;","","@implementation MyHttpClient","","- (void)sendUrlRequest:(NSURL *)url {","    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];","    request.timeoutInterval = 0;","","    \/\/ Config your request...","","    NSURLSessionDataTask *dataTask = [NSURLSession.sharedSession dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {","        if (error != nil) {","            HSBotDefenderErrorType errorType  = [HumanSecurity.BD errorTypeWithError:error];","            switch (errorType) {","                case HSBotDefenderErrorTypeChallengeWasSolved:","                    NSLog(@\"Challenge was solved\");","                case HSBotDefenderErrorTypeChallengeWasCancelled:","                    NSLog(@\"Challenge was cancelled\");","                default:","                    NSLog(@\"Unknown error\");","                    break;","            }","        }","    }];","    [dataTask resume];","}","","@end"],"syntax":"objc"},{"inlineContent":[{"text":"Using ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Alamofire\/Alamofire"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"type":"codeListing","code":["import Alamofire","import HUMAN","","class MyHttpClient {","","    func sendUrlRequest(url: URL) {","        AF.request(url) { $0.timeoutInterval = 0 }.response { response in","            if let error = response.error?.underlyingError {","                let errorType = HumanSecurity.BD.errorType(error: error)","                switch errorType {","                case .challengeWasSolved:","                    print(\"Challenge was solved\")","                case .challengeWasCancelled:","                    print(\"Challenge was cancelled\")","                default:","                    print(\"Unknown error\")","                    break","                }","            }","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"We configure the URL request (iOS) to be with infinite timeout. In android we leave the defualt call \/ request time and can configure connect \/ socket timeout.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"[Android only] We configure the HTTP client to have the ","type":"text"},{"type":"codeVoice","code":"HSInterceptor"},{"text":". ","type":"text"},{"inlineContent":[{"type":"text","text":"This interceptor must be the last interceptor in the list"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"We send the URL request."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"We check with the SDK if the error that was received is a “challenge solved error” or a “challenge cancelled error”."}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"text":"You should note that when the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","isActive":true},{"type":"text","text":", the SDK will send the blocked request again after the challenge was solved (before your handler will be called). "},{"inlineContent":[{"text":"However, the second request could be blocked as well and in this case the SDK won’t send the request again","type":"text"}],"type":"strong"},{"type":"text","text":". Your code should handle the challenge result appropriately."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Android, there are few cases which the challenge will be cancelled:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user press on the device’s physical back button."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Other activity in your app is starting (which caused the challenge activity to be paused).","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"After the challenge is cancelled, the user will have to perform the action again. Then, a new challenge will appear. On both iOS and Android, your app should handle the “challenge was cancelled” result.","type":"text"}]},{"type":"heading","level":3,"anchor":"What-should-I-do-when-a-request-is-blocked","text":"What should I do when a request is blocked"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Handle it as a failure."}],"type":"paragraph"},{"inlineContent":[{"text":"Your app should handle the blocked request as a failure. When the challenge was solved, you may send the request again. If the request was triggered by a user’s action, you should make it clear that the user may try again the same action.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","level":3,"text":"How to set custom parameters (optional)","anchor":"How-to-set-custom-parameters-optional"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can set custom parameters in order to configure HUMNAN’s backend with additional parameters."}]},{"inlineContent":[{"text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android), with the key “","type":"text"},{"code":"custom_param[x]","type":"codeVoice"},{"text":"” where ","type":"text"},{"type":"codeVoice","code":"[x]"},{"text":" is a number between ","type":"text"},{"type":"codeVoice","code":"1-10"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You should call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","type":"reference","isActive":true},{"text":" only after the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"reference","isActive":true},{"text":" function was already called.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"text":"Android","level":4,"anchor":"Android","type":"heading"},{"inlineContent":[{"text":"Kotlin:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"kotlin","code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun setCustomParametersForBotDefender() {","    try {","        val customParameters = HashMap<String, String>()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        HumanSecurity.BD.setCustomParameters(customParameters, \"<APP_ID>\")","    }","    catch (exception: Exception) {","        println(\"Exception: ${exception.message}\")","    }","}"]},{"inlineContent":[{"text":"Java:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"java","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import java.util.HashMap;","import android.util.Log;","","void setCustomParametersForBotDefender() {","    try {","        HashMap<String, String> customParameters = new HashMap<>();","        customParameters.put(\"custom_param1\", \"hello\");","        customParameters.put(\"custom_param2\", \"world\");","        HumanSecurity.INSTANCE.getBD().setCustomParameters(customParameters, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"]},{"text":"iOS","level":4,"anchor":"iOS","type":"heading"},{"inlineContent":[{"text":"Swift:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func setCustomParametersForBotDefender() {","    do {","        var customParameters = [String: String]()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        try HumanSecurity.BD.setCustomParameters(parameters: customParameters, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"objc","code":["@import HUMAN;","","- (void)setCustomParametersForBotDefender {","    NSMutableDictionary<NSString *, NSString *> *customParameters = [[NSMutableDictionary<NSString *, NSString *> alloc] init];","    customParameters[@\"custom_param1\"] = @\"hello\";","    customParameters[@\"custom_param2\"] = @\"world\";","    NSError *error = nil;","    [HumanSecurity.BD setCustomParametersWithParameters:customParameters forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"]},{"text":"Account Defender integration","level":2,"anchor":"Account-Defender-integration","type":"heading"},{"text":"How to enable Account Defender in your app?","level":3,"anchor":"How-to-enable-Account-Defender-in-your-app","type":"heading"},{"inlineContent":[{"text":"In order to enable Account Defender, you should set the ","type":"text"},{"code":"UserID","type":"codeVoice"},{"text":" of your current logged-in user in the SDK.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"text":"Android","type":"heading","level":4,"anchor":"Android"},{"inlineContent":[{"type":"text","text":"Kotlin:"}],"type":"paragraph"},{"syntax":"kotlin","type":"codeListing","code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun onUserLoggedIn(userID: String) {","    try {","        HumanSecurity.AD.setUserId(userID, \"<APP_ID>\")","    }","    catch (exception: Exception) {","        println(\"Exception: ${exception.message}\")","    }","}"]},{"inlineContent":[{"type":"text","text":"Java:"}],"type":"paragraph"},{"type":"codeListing","syntax":"java","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import android.util.Log;","","void onUserLoggedIn(String userID) {","    try {","        HumanSecurity.INSTANCE.getAD().setUserId(userID, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"]},{"type":"heading","level":4,"text":"iOS","anchor":"iOS"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"code":["import HUMAN","","func onUserLoggedIn(userID: String) {","    do {","        try HumanSecurity.AD.setUserId(userId: userID, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"code":["@import HUMAN;","","- (void)onUserLoggedIn:(NSString *)userID {","    NSError *error = nil;","    [HumanSecurity.AD setUserIdWithUserId:userID forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"],"syntax":"objc","type":"codeListing"},{"anchor":"How-to-notify-HUMANs-backend-on-outgoing-URL-requests-from-the-app","text":"How to notify HUMAN’s backend on outgoing URL requests from the app","level":3,"type":"heading"},{"inlineContent":[{"text":"In order to allow Account Defender protect the user’s account, your app has to provide the SDK with outgoing URL requests.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"While the SDK’s interceptor is enabled, the SDK is collecting your outgoing URL requests automatically. There is no need to manually call the SDK’s API.","type":"text"}],"type":"paragraph"},{"level":3,"text":"How to set additional data (optional)","anchor":"How-to-set-additional-data-optional","type":"heading"},{"inlineContent":[{"text":"You can set additional data in order to configure HUMNAN’s backend with additional parameters.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android).","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You should call the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","type":"reference"},{"text":" only after the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"reference"},{"text":" function was already called.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"level":4,"text":"Android","anchor":"Android","type":"heading"},{"inlineContent":[{"text":"Kotlin:","type":"text"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun setAdditionalDataForAccountDefender() {","    try {","        val additionalData = HashMap<String, String>()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        HumanSecurity.AD.setAdditionalData(additionalData, \"<APP_ID>\")","    }","    catch (exception: Exception) {","       println(\"Exception: ${exception.message}\")","    }","}"],"type":"codeListing","syntax":"kotlin"},{"inlineContent":[{"text":"Java:","type":"text"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import java.util.HashMap;","import android.util.Log;","","void setAdditionalDataForAccountDefender() {","    try {","        HashMap<String, String> additionalData = new HashMap<>();","        additionalData.put(\"my_key1\", \"hello\");","        additionalData.put(\"my_key2\", \"world\");","        HumanSecurity.INSTANCE.getAD().setAdditionalData(additionalData, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"],"type":"codeListing","syntax":"java"},{"level":4,"text":"iOS","anchor":"iOS","type":"heading"},{"inlineContent":[{"text":"Swift:","type":"text"}],"type":"paragraph"},{"code":["import HUMAN","","func setAdditionalDataForAccountDefender() {","    do {","        var additionalData = [String: String]()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        try HumanSecurity.AD.setAdditionalData(parameters: additionalData, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"code":["@import HUMAN;","","- (void)setAdditionalDataForAccountDefender {","    NSMutableDictionary<NSString *, NSString *> *additionalData = [[NSMutableDictionary<NSString *, NSString *> alloc] init];","    additionalData[@\"my_key1\"] = @\"hello\";","    additionalData[@\"my_key2\"] = @\"world\";","    NSError *error = nil;","    [HumanSecurity.AD setAdditionalDataWithParameters:additionalData forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"],"type":"codeListing","syntax":"objc"}],"kind":"content"}],"sections":[],"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"Article","role":"article","title":"Native - Advanced Functionality"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","variants":[{"paths":["\/documentation\/human\/native_advanced_functionality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/native_advanced_functionality"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"https://square.github.io/okhttp/":{"title":"OkHttp","titleInlineContent":[{"type":"text","text":"OkHttp"}],"url":"https:\/\/square.github.io\/okhttp\/","type":"link","identifier":"https:\/\/square.github.io\/okhttp\/"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"title":"HSAutomaticInterceptorType.intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}]},"https://github.com/Alamofire/Alamofire":{"title":"Alamofire","titleInlineContent":[{"type":"codeVoice","code":"Alamofire"}],"url":"https:\/\/github.com\/Alamofire\/Alamofire","type":"link","identifier":"https:\/\/github.com\/Alamofire\/Alamofire"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptWithDelayedResponse":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"abstract":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","isActive":true,"type":"reference"},{"text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}],"title":"HSAutomaticInterceptorType.interceptWithDelayedResponse","url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse","kind":"symbol","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionRequestTimeout":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionrequesttimeout","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"title":"urlSessionRequestTimeout","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeoutInterval"},{"type":"text","text":" that you would like to set for the URLRequest when using "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","type":"reference","isActive":true},{"type":"text","text":"  or "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","type":"reference","isActive":true},{"type":"text","text":" "},{"text":"In those cases you would need to set the timeout of the request to 0 in order to enable the request to return only after the challenge is completed when blocked, without getting a time out error,","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"urlSessionRequestTimeout","type":"codeVoice"},{"text":" will allow you to set the required timeout for the actual request, the default will be set to 60 as the default timeout for URLRequest.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"urlSessionRequestTimeout","kind":"identifier"}]},"#account-defender-integration":{"url":"#account-defender-integration","titleInlineContent":[{"text":"Account Defender integration","type":"text"}],"type":"link","title":"Account Defender integration","identifier":"#account-defender-integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"title":"start(appId:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","role":"symbol","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)"},"#bot-defender-integration":{"url":"#bot-defender-integration","title":"Bot Defender integration","identifier":"#bot-defender-integration","titleInlineContent":[{"text":"Bot Defender integration","type":"text"}],"type":"link"},"https://developer.apple.com/documentation/foundation/urlsession":{"url":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","title":"URLSession","identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","titleInlineContent":[{"code":"URLSession","type":"codeVoice"}],"type":"link"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/setCustomParameters(parameters:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomParameters"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Set custom parameters for given AppID.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"title":"setCustomParameters(parameters:forAppId:)","url":"\/documentation\/human\/hsbotdefender\/setcustomparameters(parameters:forappid:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","title":"start(appIds:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"},"https://square.github.io/okhttp/features/interceptors/":{"url":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/","titleInlineContent":[{"text":"Interceptors","type":"text"}],"type":"link","title":"Interceptors","identifier":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"abstract":[{"text":"Set additional data that support Account Defender for given AppID.","type":"text"}],"title":"setAdditionalData(parameters:forAppId:)","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdditionalData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptAndRetryRequest":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptandretryrequest","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptAndRetryRequest"}],"title":"HSAutomaticInterceptorType.interceptAndRetryRequest","abstract":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","type":"reference","isActive":true},{"type":"text","text":". When the challenge is solved, the SDK will send the original request one more time. Your request’s handler should receive the response from your server without knowing that the request was blocked and sent again. You should note that when the challenge is cancelled or when the second request is also blocked, then the behavior will be the same as the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","type":"reference","isActive":true},{"type":"text","text":". In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","url":"\/documentation\/human\/hsautomaticinterceptortype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"title":"HSAutomaticInterceptorType","kind":"symbol","abstract":[{"text":"The Automatic Interceptor type.","type":"text"}],"navigatorTitle":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},"#how-to-start-the-sdk":{"url":"#how-to-start-the-sdk","title":"How to start the SDK","identifier":"#how-to-start-the-sdk","titleInlineContent":[{"text":"How to start the SDK","type":"text"}],"type":"link"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionConfiguration":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"urlSessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"}],"title":"urlSessionConfiguration","abstract":[{"text":"The ","type":"text"},{"code":"URLSessionConfiguration","type":"codeVoice"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlSessionConfiguration"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"title":"HSPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/human\/hspolicy","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","value":"HSAutomaticInterceptorTypeIntercept"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","value":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/title","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/fragments","value":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/title","value":"urlSessionRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/fragments","value":[{"text":"urlSessionRequestTimeout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","value":"startWithAppId:policy:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/title","value":"setCustomParametersWithParameters:forAppId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","value":"startWithAppIds:policy:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:policy:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title","value":"setAdditionalDataWithParameters:forAppId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/title","value":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/fragments","value":[{"text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/title","value":"urlSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/fragments","value":[{"text":"urlSessionConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"text":"HSPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","value":[{"text":"HSPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}