{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/native_easiest_implementation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/native_easiest_implementation"]}],"metadata":{"modules":[{"name":"HUMAN"}],"role":"article","roleHeading":"Article","title":"Native - Easiest Implementation"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation"},"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Introduction","anchor":"Introduction"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In this article we will learn how to integrate the SDK to your native iOS\/Android app."}]}]},{"content":[{"inlineContent":[{"text":"Highlights:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The faster way to integrate the SDK - minimum integration points.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK intercpts your URL requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Handle blocked requests.","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Note that the Android implementation requires that your app use "},{"identifier":"https:\/\/square.github.io\/okhttp\/","type":"reference","isActive":true},{"type":"text","text":" which supports "},{"type":"reference","identifier":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/","isActive":true}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note that the iOS implementation requires that your app use "},{"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","isActive":true,"type":"reference"},{"type":"text","text":" or any 3rd party library that based on it"}]},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We will cover the following topics:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#how-to-start-the-sdk","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"#bot-defender-integration","type":"reference","isActive":true}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"How to add the SDK’s HTTP headers to your URL requests."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to handle the blocked request."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How to present a challenge to the user.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"How to set custom parameters (optional).","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#account-defender-integration","isActive":true}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"How to enable it.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to notify HUMAN’s backend on outgoing URL requests from the app."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"How to set additional data (optional)."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}]},{"level":2,"text":"Important notice about iOS","type":"heading","anchor":"Important-notice-about-iOS"},{"type":"paragraph","inlineContent":[{"text":"The SDK uses a custom URL protocol in order to manipulate your URL requests. The SDK creates a new ","type":"text"},{"code":"URLSession","type":"codeVoice"},{"text":" object to load your URL requests. As a result, there are few limitations that you should be aware of before the integration:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"if your implement the "},{"code":"urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping @Sendable (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)","type":"codeVoice"},{"type":"text","text":" in your "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":", then this function "},{"type":"strong","inlineContent":[{"text":"will not be called","type":"text"}]},{"type":"text","text":" and the default OS logic will apply in your URL request."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The SDK’s "},{"type":"codeVoice","code":"URLSession"},{"text":" object is configured with ","type":"text"},{"type":"codeVoice","code":"URLSessionConfiguration.default"},{"text":". Any custom configuration on your side ","type":"text"},{"type":"strong","inlineContent":[{"text":"will not apply","type":"text"}]},{"text":"’","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK does not support caching in your URL requests."}]}]}]},{"type":"heading","anchor":"How-to-start-the-SDK","level":2,"text":"How to start the SDK"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason is that when your app will send an URL request to your server before the SDK was started, then the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user.","type":"text"},{"text":" ","type":"text"},{"text":"The best place to start the SDK is in the:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"code":"Application","type":"codeVoice"},{"text":"’s ","type":"text"},{"code":"onCreate","type":"codeVoice"},{"text":" function on Android.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"AppDelegate"},{"text":"’s ","type":"text"},{"code":"didFinishLaunchingWithOptions","type":"codeVoice"},{"type":"text","text":" function on iOS."}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should start the SDK on the "},{"type":"strong","inlineContent":[{"type":"text","text":"main thread"}]},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"The SDK is intercepting URL requests from your app. Your app should tell the SDK which domains are intercepted. Not specifying domains means that ALL domains will be intercepted. The SDK checks if the URL’s domain ends with one of the domains that were set. For example: If you set ","type":"text"},{"code":"example.com","type":"codeVoice"},{"text":" the SDK will also intercept calls to ","type":"text"},{"type":"codeVoice","code":"www.example.com"},{"text":" and ","type":"text"},{"code":"api.example.com","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"heading","text":"Android","anchor":"Android","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Kotlin:"}]},{"syntax":"kotlin","type":"codeListing","code":["import android.app.Application","import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.policy.HSPolicy","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType","","class MainApplication: Application() {","","    override fun onCreate() {","        super.onCreate()","        startHumanSDK()","    }","","    private fun startHumanSDK() {","        try {","            val policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorType.INTERCEPT","            policy.automaticInterceptorPolicy.setInterceptedDomains(setOf(\"example.com\"), \"<APP_ID>\")","","            HumanSecurity.start(this, \"<APP_ID>\", policy)","        }","        catch (exception: Exception) {","            println(\"Exception: ${exception.message}\")","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Java:"}]},{"syntax":"java","type":"codeListing","code":["import android.app.Application;","import android.util.Log;","import java.util.HashSet;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.policy.HSPolicy;","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType;","","public class MainApplication extends Application {","","    @Override","    public void onCreate() {","        super.onCreate();","        startHumanSDK();","    }","","    void startHumanSDK() {","        try {","            HSPolicy policy = new HSPolicy();","            policy.getAutomaticInterceptorPolicy().setInterceptorType(HSAutomaticInterceptorType.INTERCEPT);","","            HashSet<String> domains = new HashSet<>();","            domains.add(\"example.com\");","            policy.getAutomaticInterceptorPolicy().setInterceptedDomains(domains, \"<APP_ID>\");","","            HumanSecurity.INSTANCE.start(this, \"<APP_ID>\", policy);","        }","        catch (Exception exception) {","            Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","        }","    }","}"]},{"level":3,"type":"heading","text":"iOS","anchor":"iOS"},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["import UIKit","import HUMAN","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","        startHumanSDK()","        return true","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            policy.automaticInterceptorPolicy.interceptorType = .intercept","            policy.automaticInterceptorPolicy.set(interceptedDomains: [\"example.com\"], forAppId: \"<APP_ID>\")","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C:"}]},{"syntax":"objc","type":"codeListing","code":["@import HUMAN;","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","    [self startHumanSDK];","    return YES;","}","","- (void)startHumanSDK {","    HSPolicy *policy = [[HSPolicy alloc] init];","    policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorTypeIntercept;","    [policy.automaticInterceptorPolicy setWithInterceptedDomains:[NSSet setWithObject:@\"example.com\"] forAppId:@\"<APP_ID>\"];","","    NSError *error = nil;","    [HumanSecurity startWithAppId:@\"<APP_ID>\" policy:policy error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}","","@end"]},{"type":"paragraph","inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"We about to start the SDK as soon as possible and on the main thread.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We create a ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","isActive":true,"type":"reference"},{"text":" instance. This object is used to configure the SDK’s behavior. Here, we set the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","isActive":true,"type":"reference"},{"text":" property to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","isActive":true},{"type":"text","text":". This will turn on the "},{"inlineContent":[{"text":"Automatic Interception","type":"text"}],"type":"emphasis"},{"text":" feature of the SDK. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. We also set our server’s domain. This will tell the SDK to intercept URL requests only for this domain.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"We call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"type":"text","text":" function of the SDK. We provide the following parameters:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"Application","type":"codeVoice"},{"type":"text","text":" instance (Android only)."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your AppID."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The policy object that we configured."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: In iOS, The Automatic Interception uses the "},{"type":"codeVoice","code":"URLSessionConfiguration.default"},{"type":"text","text":" to send your URL request. However, if your app uses a custom configuration, you should set your configuration in the policy - "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Note: If your app communicates with several servers that have different AppID, you can call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","isActive":true,"type":"reference"},{"text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK.","type":"text"}]},{"type":"heading","anchor":"Bot-Defender-integration","text":"Bot Defender integration","level":2},{"type":"heading","anchor":"How-to-add-the-SDKs-HTTP-headers-to-your-URL-requests-and-handle-the-blocked-request","text":"How to add the SDK’s HTTP headers to your URL requests and handle the blocked request","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The SDK adds its HTTP headers to you URL requests automaticlly. There is no need to manually add those headers."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK handles the blocked request and present a challenge to the user automatically.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK provides a custom error response directly to your request handler.","type":"text"}]}]}]},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"level":4,"anchor":"Android","text":"Android","type":"heading"},{"inlineContent":[{"type":"text","text":"Kotlin (OkHttp):"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.HSBotDefenderErrorType","import com.humansecurity.mobile_sdk.main.HSInterceptor","import okhttp3.OkHttpClient","import okhttp3.Request","","class MyHttpClient {","","    private val okHttpClient: OkHttpClient = OkHttpClient.Builder()","        .addInterceptor(HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","        .build()","","    fun sendRequest(url: String) {","        try {","            val request: Request = Request.Builder().url(url).build()","            okHttpClient.newCall(request).execute().use { response ->","                if (!response.isSuccessful) {","                    response.body?.string()?.let { responseBody ->","                        when (HumanSecurity.BD.errorType(responseBody)) {","                            HSBotDefenderErrorType.REQUEST_WAS_BLOCKED -> {","                                println(\"Request was blocked\")","                            }","                            else -> {","                                println(\"Unknown error\")","                            }","                        }","                    }","                }","            }","        }","        catch (exception: Exception) {","            println(\"Request was failed. Exception: $exception\")","        }","    }","}"],"syntax":"kotlin","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Kotlin (ktor):"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity","import com.humansecurity.mobile_sdk.main.HSBotDefenderErrorType","import com.humansecurity.mobile_sdk.main.HSInterceptor","import io.ktor.client.*","import io.ktor.client.call.body","import io.ktor.client.engine.okhttp.*","import io.ktor.client.request.*","import io.ktor.client.statement.*","","class MyHttpClient {","","    private val httpClient: HttpClient = HttpClient(OkHttp) {","        engine {","            addInterceptor(HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","        }","    }","","    suspend fun sendRequest(url: String) {","        try {","            val response: HttpResponse = httpClient.request(url) {}","            val responseBody = response.body<String>()","            when (HumanSecurity.BD.errorType(responseBody)) {","                HSBotDefenderErrorType.REQUEST_WAS_BLOCKED -> {","                    println(\"Request was blocked\")","                }","                else -> {","                    println(\"Unknown error\")","                }","            }","        } catch (exception: Exception) {","            println(\"Request was failed. exception: $exception\")","        }","    }","}"],"syntax":"kotlin","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Java:"}]},{"type":"codeListing","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.HSInterceptor;","import android.util.Log;","import okhttp3.OkHttpClient;","import okhttp3.Request;","import okhttp3.Response;","import okhttp3.ResponseBody;","","public class MyHttpClient {","","    private final OkHttpClient httpClient = new OkHttpClient.Builder()","            .addInterceptor(new HSInterceptor()) \/\/ SHOULD BE THE LAST INTERCEPTOR","            .build();","","    void sendRequest(String url) {","        Runnable r = () -> {","            try {","                Request request = new Request.Builder().url(url).build();","                Response response = httpClient.newCall(request).execute();","                ResponseBody responseBody = response.body();","                String responseString = null;","                if (responseBody != null) {","                    responseString = responseBody.string();","                    response.close();","                }","                if (!response.isSuccessful() && responseString != null) {","                    switch (HumanSecurity.INSTANCE.getBD().errorType(responseString)) {","                        case REQUEST_WAS_BLOCKED:","                            Log.i(\"MyInterceptor\", \"Request was blocked\");","                            break;","                    }","                }","            }","            catch (Exception exception) {","                Log.i(\"MyHttpClient\", \"Request was failed. Exception: \" + exception);","            }","        };","        new Thread(r).start();","    }","}"],"syntax":"java"},{"level":4,"anchor":"iOS","text":"iOS","type":"heading"},{"inlineContent":[{"text":"Using ","type":"text"},{"isActive":true,"overridingTitle":"URLSession","overridingTitleInlineContent":[{"code":"URLSession","type":"codeVoice"}],"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import HUMAN","","class MyHttpClient {","","    func sendUrlRequest(url: URL) {","        var request = URLRequest(url: url)","        ","        \/\/ Config your request...","","        let dataTask = URLSession.shared.dataTask(with: request) { data, response, error in","            if let error {","                let errorType = HumanSecurity.BD.errorType(error: error)","                switch errorType {","                case .requestWasBlocked:","                    print(\"Request was blocked\")","                default:","                    break","                }","            }","        }","        dataTask.resume()","    }","}"]},{"inlineContent":[{"text":"Objective-C:","type":"text"}],"type":"paragraph"},{"syntax":"objc","code":["@import HUMAN;","","@implementation MyHttpClient","","- (void)sendUrlRequest:(NSURL *)url {","    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];","    ","    \/\/ Config your request...","","    NSURLSessionDataTask *dataTask = [NSURLSession.sharedSession dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {","        if (error != nil) {","            HSBotDefenderErrorType errorType  = [HumanSecurity.BD errorTypeWithError:error];","            switch (errorType) {","                case HSBotDefenderErrorTypeRequestWasBlocked:","                    NSLog(@\"Request was blocked\");","                    break;","                default:","                    break;","            }","        }","    }];","    [dataTask resume];","}","","@end"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Using "},{"type":"reference","identifier":"https:\/\/github.com\/Alamofire\/Alamofire","isActive":true},{"type":"text","text":":"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"syntax":"swift","code":["import Alamofire","import HUMAN","","class MyHttpClient {","","    func sendUrlRequest(url: URL) {","        AF.request(url).response { response in","            if let error = response.error?.underlyingError {","                let errorType = HumanSecurity.BD.errorType(error: error)","                switch errorType {","                case .requestWasBlocked:","                    print(\"Request was blocked\")","                default:","                    break","                }","            }","        }","    }","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"[Android only] We configure the HTTP client to have the ","type":"text"},{"type":"codeVoice","code":"HSInterceptor"},{"type":"text","text":". "},{"type":"strong","inlineContent":[{"type":"text","text":"This interceptor must be the last interceptor in the list"}]},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We send the URL request."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We check with the SDK if the error that was received is a “blocked request error”."}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Please note that while your request handler is called, the SDK is presenting a challenge to the user.","type":"text"}]},{"type":"heading","level":3,"anchor":"What-should-I-do-when-a-request-is-blocked","text":"What should I do when a request is blocked"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Handle it as a failure."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Your app should handle the blocked request as a failure. However, you should consider that your app’s UI will be shown again after the challenge was solved\/cancelled by the user. If the request was triggered by a user’s action, you should make it clear that the user may try again the same action."}]}]}]},{"text":"How to set custom parameters (optional)","level":3,"anchor":"How-to-set-custom-parameters-optional","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You can set custom parameters in order to configure HUMNAN’s backend with additional parameters.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android), with the key “"},{"type":"codeVoice","code":"custom_param[x]"},{"type":"text","text":"” where "},{"type":"codeVoice","code":"[x]"},{"type":"text","text":" is a number between "},{"code":"1-10","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","isActive":true,"type":"reference"},{"text":" only after the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true},{"type":"text","text":" function was already called."}]},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"type":"heading","text":"Android","anchor":"Android","level":4},{"inlineContent":[{"type":"text","text":"Kotlin:"}],"type":"paragraph"},{"syntax":"kotlin","code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun setCustomParametersForBotDefender() {","    try {","        val customParameters = HashMap<String, String>()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        HumanSecurity.BD.setCustomParameters(customParameters, \"<APP_ID>\")","    }","    catch (exception: Exception) {","        println(\"Exception: ${exception.message}\")","    }","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Java:"}]},{"syntax":"java","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import java.util.HashMap;","import android.util.Log;","","void setCustomParametersForBotDefender() {","    try {","        HashMap<String, String> customParameters = new HashMap<>();","        customParameters.put(\"custom_param1\", \"hello\");","        customParameters.put(\"custom_param2\", \"world\");","        HumanSecurity.INSTANCE.getBD().setCustomParameters(customParameters, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"],"type":"codeListing"},{"text":"iOS","anchor":"iOS","type":"heading","level":4},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"code":["import HUMAN","","func setCustomParametersForBotDefender() {","    do {","        var customParameters = [String: String]()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        try HumanSecurity.BD.setCustomParameters(parameters: customParameters, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Objective-C:","type":"text"}]},{"type":"codeListing","syntax":"objc","code":["@import HUMAN;","","- (void)setCustomParametersForBotDefender {","    NSMutableDictionary<NSString *, NSString *> *customParameters = [[NSMutableDictionary<NSString *, NSString *> alloc] init];","    customParameters[@\"custom_param1\"] = @\"hello\";","    customParameters[@\"custom_param2\"] = @\"world\";","    NSError* error = nil;","    [HumanSecurity.BD setCustomParametersWithParameters:customParameters forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"]},{"type":"heading","level":2,"anchor":"Account-Defender-integration","text":"Account Defender integration"},{"level":3,"type":"heading","text":"How to enable Account Defender in your app?","anchor":"How-to-enable-Account-Defender-in-your-app"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to enable Account Defender, you should set the "},{"code":"UserID","type":"codeVoice"},{"text":" of your current logged-in user in the SDK.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"anchor":"Android","text":"Android","type":"heading","level":4},{"inlineContent":[{"text":"Kotlin:","type":"text"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun onUserLoggedIn(userID: String) {","    try {","        HumanSecurity.AD.setUserId(userID, \"<APP_ID>\")","    }","    catch (exception: Exception) {","        println(\"Exception: ${exception.message}\")","    }","}"],"syntax":"kotlin","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Java:"}],"type":"paragraph"},{"code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import android.util.Log;","","void onUserLoggedIn(String userID) {","    try {","        HumanSecurity.INSTANCE.getAD().setUserId(userID, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"],"syntax":"java","type":"codeListing"},{"type":"heading","text":"iOS","anchor":"iOS","level":4},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func onUserLoggedIn(userID: String) {","    do {","        try HumanSecurity.AD.setUserId(userId: userID, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C:"}]},{"type":"codeListing","syntax":"objc","code":["@import HUMAN;","","- (void)onUserLoggedIn:(NSString *)userID {","    NSError* error = nil;","    [HumanSecurity.AD setUserIdWithUserId:userID forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"]},{"type":"heading","level":3,"anchor":"How-to-notify-HUMANs-backend-on-outgoing-URL-requests-from-the-app","text":"How to notify HUMAN’s backend on outgoing URL requests from the app"},{"type":"paragraph","inlineContent":[{"text":"In order to allow Account Defender protect the user’s account, your app has to provide the SDK with outgoing URL requests.","type":"text"}]},{"inlineContent":[{"type":"text","text":"While the SDK’s interceptor is enabled, the SDK is collecting your outgoing URL requests automatically. There is no need to manually call the SDK’s API."}],"type":"paragraph"},{"anchor":"How-to-set-additional-data-optional","type":"heading","level":3,"text":"How to set additional data (optional)"},{"inlineContent":[{"type":"text","text":"You can set additional data in order to configure HUMNAN’s backend with additional parameters."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android)."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You should call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)"},{"type":"text","text":" only after the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"type":"text","text":" function was already called."}],"type":"paragraph"},{"inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}],"type":"paragraph"},{"anchor":"Android","type":"heading","level":4,"text":"Android"},{"inlineContent":[{"type":"text","text":"Kotlin:"}],"type":"paragraph"},{"syntax":"kotlin","type":"codeListing","code":["import com.humansecurity.mobile_sdk.HumanSecurity","","fun setAdditionalDataForAccountDefender() {","    try {","        val additionalData = HashMap<String, String>()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        HumanSecurity.AD.setAdditionalData(additionalData, \"<APP_ID>\")","    }","    catch (exception: Exception) {","       println(\"Exception: ${exception.message}\")","    }","}"]},{"inlineContent":[{"text":"Java:","type":"text"}],"type":"paragraph"},{"syntax":"java","type":"codeListing","code":["import com.humansecurity.mobile_sdk.HumanSecurity;","import java.util.HashMap;","import android.util.Log;","","void setAdditionalDataForAccountDefender() {","    try {","        HashMap<String, String> additionalData = new HashMap<>();","        additionalData.put(\"my_key1\", \"hello\");","        additionalData.put(\"my_key2\", \"world\");","        HumanSecurity.INSTANCE.getAD().setAdditionalData(additionalData, \"<APP_ID>\");","    }","    catch(Exception exception) {","        Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","    }","}"]},{"anchor":"iOS","type":"heading","level":4,"text":"iOS"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import HUMAN","","func setAdditionalDataForAccountDefender() {","    do {","        var additionalData = [String: String]()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        try HumanSecurity.AD.setAdditionalData(parameters: additionalData, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]},{"inlineContent":[{"type":"text","text":"Objective-C:"}],"type":"paragraph"},{"syntax":"objc","type":"codeListing","code":["@import HUMAN;","","- (void)setAdditionalDataForAccountDefender {","    NSMutableDictionary<NSString *, NSString *> *additionalData = [[NSMutableDictionary<NSString *, NSString *> alloc] init];","    additionalData[@\"my_key1\"] = @\"hello\";","    additionalData[@\"my_key2\"] = @\"world\";","    NSError* error = nil;","    [HumanSecurity.AD setAdditionalDataWithParameters:additionalData forAppId:@\"<APP_ID>\" error:&error];","    if (error != nil) {","        NSLog(@\"Error: %@\", error);","    }","}"]}],"kind":"content"}],"sections":[],"kind":"article","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}],"url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","title":"setAdditionalData(parameters:forAppId:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdditionalData"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"title":"start(appIds:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"startWithAppId:policy:error:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype","title":"interceptorType","navigatorTitle":[{"kind":"identifier","text":"interceptorType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptorType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType","kind":"typeIdentifier","text":"HSAutomaticInterceptorType"}],"type":"topic"},"#bot-defender-integration":{"url":"#bot-defender-integration","type":"link","title":"Bot Defender integration","titleInlineContent":[{"text":"Bot Defender integration","type":"text"}],"identifier":"#bot-defender-integration"},"https://square.github.io/okhttp/":{"url":"https:\/\/square.github.io\/okhttp\/","type":"link","title":"OkHttp","titleInlineContent":[{"text":"OkHttp","type":"text"}],"identifier":"https:\/\/square.github.io\/okhttp\/"},"#how-to-start-the-sdk":{"identifier":"#how-to-start-the-sdk","title":"How to start the SDK","titleInlineContent":[{"text":"How to start the SDK","type":"text"}],"type":"link","url":"#how-to-start-the-sdk"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionConfiguration":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URLSessionConfiguration"},{"type":"text","text":" that should be used by the SDK. Default is "},{"type":"codeVoice","code":"URLSessionConfiguration.default"},{"type":"text","text":"."}],"type":"topic","title":"urlSessionConfiguration","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration","role":"symbol","navigatorTitle":[{"text":"urlSessionConfiguration","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/setCustomParameters(parameters:forAppId:)":{"role":"symbol","type":"topic","url":"\/documentation\/human\/hsbotdefender\/setcustomparameters(parameters:forappid:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","title":"setCustomParameters(parameters:forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Set custom parameters for given AppID.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"kind":"symbol"},"https://developer.apple.com/documentation/foundation/urlsession":{"identifier":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession","title":"URLSession","titleInlineContent":[{"type":"codeVoice","code":"URLSession"}],"type":"link","url":"https:\/\/developer.apple.com\/documentation\/foundation\/urlsession"},"https://github.com/Alamofire/Alamofire":{"url":"https:\/\/github.com\/Alamofire\/Alamofire","type":"link","title":"Alamofire","titleInlineContent":[{"type":"codeVoice","code":"Alamofire"}],"identifier":"https:\/\/github.com\/Alamofire\/Alamofire"},"https://square.github.io/okhttp/features/interceptors/":{"identifier":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/","title":"Interceptors","titleInlineContent":[{"text":"Interceptors","type":"text"}],"type":"link","url":"https:\/\/square.github.io\/okhttp\/features\/interceptors\/"},"#account-defender-integration":{"identifier":"#account-defender-integration","title":"Account Defender integration","titleInlineContent":[{"type":"text","text":"Account Defender integration"}],"type":"link","url":"#account-defender-integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"title":"HSAutomaticInterceptorType.intercept","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"url":"\/documentation\/human\/hspolicy","title":"HSPolicy","type":"topic","role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"setAdditionalDataWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments","op":"replace"},{"value":"startWithAppIds:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","op":"replace"},{"value":"startWithAppId:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","op":"replace"},{"value":"interceptorType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"interceptorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","op":"replace"},{"value":"urlSessionConfiguration","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/title","op":"replace"},{"value":[{"text":"urlSessionConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/fragments","op":"replace"},{"value":"setCustomParametersWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/fragments","op":"replace"},{"value":"HSAutomaticInterceptorTypeIntercept","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","op":"replace"},{"value":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","op":"replace"},{"value":"HSPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","op":"replace"},{"value":[{"text":"HSPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"HSPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","op":"replace"}]}]}