{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Intro","type":"heading","level":2,"text":"Intro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK can be integrated into a "},{"type":"reference","identifier":"https:\/\/reactnative.dev\/","isActive":true},{"type":"text","text":" project."}]},{"anchor":"Integration-with-C++-iOS","type":"heading","level":3,"text":"Integration with C++ (iOS)"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your project is built with C++ ("},{"type":"codeVoice","code":"AppDelegate.mm"},{"type":"text","text":") then you should do the following:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Open Xcode Build Settings.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Targets -> Build Settings -> ","type":"text"},{"type":"codeVoice","code":"Apple Clang - Custom Compiler Flags"},{"text":" > ","type":"text"},{"type":"codeVoice","code":"Other C++"},{"text":" Flags","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Add the “","type":"text"},{"type":"codeVoice","code":"-fcxx-modules"},{"text":"” flag.","type":"text"}],"type":"paragraph"}]}]},{"anchor":"Add-the-Human-Module","type":"heading","level":2,"text":"Add the Human Module"},{"anchor":"Android","type":"heading","level":4,"text":"Android"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a "},{"identifier":"https:\/\/reactnative.dev\/docs\/native-modules-android","isActive":true,"type":"reference"},{"type":"text","text":" which called "},{"type":"codeVoice","code":"HumanModule"},{"type":"text","text":"."}]}]}]},{"inlineContent":[{"type":"text","text":"Java \/ HumanModule.java:"}],"type":"paragraph"},{"type":"codeListing","syntax":"java","code":["import androidx.annotation.NonNull;","import com.facebook.react.bridge.Promise;","import com.facebook.react.bridge.ReactApplicationContext;","import com.facebook.react.bridge.ReactContextBaseJavaModule;","import com.facebook.react.bridge.ReactMethod;","import com.facebook.react.modules.core.DeviceEventManagerModule;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.HSBotDefenderChallengeResult;","import org.json.JSONObject;","import java.util.HashMap;","import java.util.Objects;","","public class HumanModule extends ReactContextBaseJavaModule {","","    static HumanModule shared = null;","","    String strNewHeaders = \"HumanNewHeaders\";","    String strChallengeResult = \"HumanChallengeResult\";","    String strSolved = \"solved\";","    String strCancelled = \"cancelled\";","    String strFalse = \"false\";","","    HumanModule(ReactApplicationContext context) {","        super(context);","    }","","    @NonNull","    @Override","    public String getName() {","        return \"HumanModule\";","    }","","    public void handleUpdatedHeaders(HashMap<String, String> headers) {","        if (!this.getReactApplicationContext().hasCatalystInstance()) {","            return;","        }","        JSONObject json = new JSONObject(headers);","        this.getReactApplicationContext()","                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)","                .emit(strNewHeaders, json.toString());","    }","","    public void handleChallengeSolvedEvent() {","        if (!this.getReactApplicationContext().hasCatalystInstance()) {","            return;","        }","        this.getReactApplicationContext()","                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)","                .emit(strChallengeResult, strSolved);","    }","","    public void handleChallengeCancelledEvent() {","        if (!this.getReactApplicationContext().hasCatalystInstance()) {","            return;","        }","        this.getReactApplicationContext()","                .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)","                .emit(strChallengeResult, strCancelled);","    }","","    @ReactMethod","    public void getHTTPHeaders(Promise promise) {","        JSONObject json = new JSONObject(Objects.requireNonNull(HumanSecurity.INSTANCE.getBD().headersForURLRequest(null)));","        promise.resolve(json.toString());","    }","","    @ReactMethod","    public void handleResponse(String response, Integer code, String url, Promise promise) {","        boolean handled = HumanSecurity.INSTANCE.getBD().handleResponse(response, result -> {","            promise.resolve(result == HSBotDefenderChallengeResult.SOLVED ? strSolved : strCancelled);","            return null;","        });","        if (!handled) {","            promise.resolve(strFalse);","        }","    }","}"]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Add the ","type":"text"},{"code":"HumanModule","type":"codeVoice"},{"type":"text","text":" to the "},{"code":"HumanPackage","type":"codeVoice"},{"type":"text","text":" and set the "},{"type":"codeVoice","code":"shread"},{"type":"text","text":" property."}]}]}],"start":2},{"type":"paragraph","inlineContent":[{"text":"Java \/ HumanPackage.java:","type":"text"}]},{"type":"codeListing","syntax":"java","code":["import com.facebook.react.ReactPackage;","import com.facebook.react.bridge.NativeModule;","import com.facebook.react.bridge.ReactApplicationContext;","import com.facebook.react.uimanager.ViewManager;","import java.util.ArrayList;","import java.util.Collections;","import java.util.List;","","public class HumanPackage implements ReactPackage {","","    @Override","    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {","        return Collections.emptyList();","    }","","    @Override","    public List<NativeModule> createNativeModules(","            ReactApplicationContext reactContext) {","        List<NativeModule> modules = new ArrayList<>();","","        HumanModule module = new HumanModule(reactContext);","        HumanModule.shared = module;","        modules.add(module);","","        return modules;","    }","}"]},{"type":"heading","text":"iOS","anchor":"iOS","level":4},{"inlineContent":[{"text":"Create a ","type":"text"},{"identifier":"https:\/\/reactnative.dev\/docs\/native-modules-ios","isActive":true,"type":"reference"},{"text":" which called ","type":"text"},{"type":"codeVoice","code":"HumanModule"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"Objective-C \/ HumanModule.h:","type":"text"}],"type":"paragraph"},{"syntax":"objc","code":["#import <Foundation\/Foundation.h>","#import <React\/RCTBridgeModule.h>","#import <React\/RCTEventEmitter.h>","","NS_ASSUME_NONNULL_BEGIN","","@interface HumanModule : RCTEventEmitter <RCTBridgeModule>","","+ (HumanModule *)shared;","- (void)handleUpdatedHeaders:(NSDictionary<NSString *,NSString *> *)headers;","- (void)handleChallengeSolvedEvent;","- (void)handleChallengeCancelledEvent;","","@end","","NS_ASSUME_NONNULL_END"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C \/ HumanModule.m:"}]},{"syntax":"objc","code":["#import \"HumanModule.h\"","@import HUMAN;","","static NSString *strNewHeaders = @\"HumanNewHeaders\";","static NSString *strChallengeResult = @\"HumanChallengeResult\";","static NSString *strSolved = @\"solved\";","static NSString *strCancelled = @\"cancelled\";","static NSString *strFalse = @\"false\";","","@implementation HumanModule","","static HumanModule *shared = nil;","","+ (HumanModule *)shared {","  return shared;","}","","- (instancetype)init {","  self = [super init];","  shared = self;","  return self;","}","","- (NSArray<NSString *> *)supportedEvents {","  return @[strNewHeaders, strChallengeResult];","}","","- (void)handleUpdatedHeaders:(NSDictionary<NSString *,NSString *> *)headers {","  NSData *data = [NSJSONSerialization dataWithJSONObject:headers options:0 error:nil];","  NSString *json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];","  [self sendEventWithName:strNewHeaders body:json];","}","","- (void)handleChallengeSolvedEvent {","  [self sendEventWithName:strChallengeResult body:strSolved];","}","","- (void)handleChallengeCancelledEvent {","  [self sendEventWithName:strChallengeResult body:strCancelled];","}","","RCT_EXPORT_MODULE(HumanModule);","","RCT_REMAP_METHOD(getHTTPHeaders,","                 resolver:(RCTPromiseResolveBlock)resolve","                 rejecter:(RCTPromiseRejectBlock)reject) {","  NSDictionary<NSString *, NSString *> *humanHttpHeaders = [HumanSecurity.BD headersForURLRequestForAppId:nil];","  NSData *data = [NSJSONSerialization dataWithJSONObject:humanHttpHeaders options:0 error:nil];","  NSString *json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];","  resolve(@[json]);","}","","RCT_REMAP_METHOD(handleResponse,","                 response:(NSString *)response","                 code:(NSInteger)code","                 url:(NSString *)url","                 resolver:(RCTPromiseResolveBlock)resolve","                 rejecter:(RCTPromiseRejectBlock)reject) {","  NSData *data = [response dataUsingEncoding:NSUTF8StringEncoding];","  NSHTTPURLResponse *httpURLResponse = [[NSHTTPURLResponse alloc] initWithURL:[NSURL URLWithString:url] statusCode:code HTTPVersion:nil headerFields:nil];","  BOOL handled = [HumanSecurity.BD handleResponseWithResponse:httpURLResponse data:data callback:^(enum HSBotDefenderChallengeResult result) {","    resolve((result == HSBotDefenderChallengeResultSolved ? strSolved : strCancelled));","  }];","  if (!handled) {","    resolve(strFalse);","  }","}","","@end"],"type":"codeListing"},{"type":"heading","anchor":"How-to-start-the-SDK","text":"How to start the SDK","level":2},{"items":[{"content":[{"inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Application"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"onCreate"},{"type":"text","text":" function on Android."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"AppDelegate"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"didFinishLaunchingWithOptions"},{"type":"text","text":" function on iOS."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"You should start the SDK on the "},{"type":"strong","inlineContent":[{"type":"text","text":"main thread"}]},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Implement the ","type":"text"},{"type":"codeVoice","code":"HumanDelegate"},{"text":" in order to receive events from the SDK.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}]},{"type":"heading","level":3,"anchor":"Android","text":"Android"},{"type":"paragraph","inlineContent":[{"text":"Java:","type":"text"}]},{"type":"codeListing","syntax":"java","code":["import android.app.Application;","import android.content.Context;","import android.util.Log;","import java.lang.reflect.InvocationTargetException;","import java.util.HashMap;","import java.util.List;","import androidx.annotation.NonNull;","import androidx.annotation.Nullable;","import com.facebook.react.PackageList;","import com.facebook.react.ReactApplication;","import com.facebook.react.ReactInstanceManager;","import com.facebook.react.ReactNativeHost;","import com.facebook.react.ReactPackage;","import com.facebook.react.config.ReactFeatureFlags;","import com.facebook.soloader.SoLoader;","import com.human_demo.newarchitecture.MainApplicationReactNativeHost;","import com.humansecurity.mobile_sdk.HumanSecurity;","import com.humansecurity.mobile_sdk.main.HSBotDefenderDelegate;","import com.humansecurity.mobile_sdk.main.policy.HSAutomaticInterceptorType;","import com.humansecurity.mobile_sdk.main.policy.HSPolicy;","","public class MainApplication extends Application implements ReactApplication, HSBotDefenderDelegate {","","    private final ReactNativeHost mReactNativeHost =","            new ReactNativeHost(this) {","                @Override","                public boolean getUseDeveloperSupport() {","                    return BuildConfig.DEBUG;","                }","","                @Override","                protected List<ReactPackage> getPackages() {","                    List<ReactPackage> packages = new PackageList(this).getPackages();","                    packages.add(new HumanPackage());","                    return packages;","                }","","                @Override","                protected String getJSMainModuleName() {","                    return \"index\";","                }","            };","","    private final ReactNativeHost mNewArchitectureNativeHost =","            new MainApplicationReactNativeHost(this);","","    @Override","    public ReactNativeHost getReactNativeHost() {","        if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {","            return mNewArchitectureNativeHost;","        } else {","            return mReactNativeHost;","        }","    }","","    @Override","    public void onCreate() {","        super.onCreate();","        ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;","        SoLoader.init(this, false);","        initializeFlipper(this, getReactNativeHost().getReactInstanceManager());","","        startHumanSDK();","    }","","    private static void initializeFlipper(","            Context context, ReactInstanceManager reactInstanceManager) {","        if (BuildConfig.DEBUG) {","            try {","                Class<?> aClass = Class.forName(\"<package_name>.ReactNativeFlipper\");","                aClass","                        .getMethod(\"initializeFlipper\", Context.class, ReactInstanceManager.class)","                        .invoke(null, context, reactInstanceManager);","            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException |","                     InvocationTargetException e) {","                e.printStackTrace();","            }","        }","    }","","    private void startHumanSDK() {","        HSPolicy policy = new HSPolicy();","        policy.getAutomaticInterceptorPolicy().setInterceptorType(HSAutomaticInterceptorType.NONE);","        try {","            HumanSecurity.INSTANCE.start(this, \"<APP_ID>\", policy);","            HumanSecurity.INSTANCE.getBD().setDelegate(this);","        }","        catch (Exception exception) {","            Log.e(\"MainApplication\",\"Exception: \" + exception.getMessage());","        }","    }","","    @Override","    public void botDefenderDidUpdateHeaders(@NonNull HashMap<String, String> hashMap, @NonNull String s) {","        if (HumanModule.shared != null) {","            HumanModule.shared.handleUpdatedHeaders(hashMap);","        }","    }","","    @Override","    public void botDefenderRequestBlocked(@Nullable String s, @NonNull String s1) {","","    }","","    @Override","    public void botDefenderChallengeSolved(@NonNull String s) {","        HumanModule.shared.handleChallengeSolvedEvent();","    }","","    @Override","    public void botDefenderChallengeCancelled(@NonNull String s) {","        HumanModule.shared.handleChallengeCancelledEvent();","    }","","    @Override","    public void botDefenderChallengeRendered(@NonNull String s) {","","    }","","    @Override","    public void botDefenderChallengeRenderFailed(@NonNull String s) {","","    }","}"]},{"type":"heading","level":3,"anchor":"iOS","text":"iOS"},{"type":"paragraph","inlineContent":[{"text":"Objective-C \/ AppDelegate.h:","type":"text"}]},{"type":"codeListing","syntax":"objc","code":["#import <React\/RCTBridgeDelegate.h>","#import <UIKit\/UIKit.h>","@import HUMAN;","","@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, HSBotDefenderDelegate>","","@property (nonatomic, strong) UIWindow *window;","","@end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C \/ AppDelegate.m:"}]},{"syntax":"objc","code":["#import \"AppDelegate.h\"","#import \"HumanModule.h\"","#import <React\/RCTBridge.h>","#import <React\/RCTBundleURLProvider.h>","#import <React\/RCTRootView.h>","#import <React\/RCTAppSetupUtils.h>","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","    HSPolicy *policy = [[HSPolicy alloc] init];","    policy.automaticInterceptorPolicy.interceptorType = HSAutomaticInterceptorTypeNone;","  ","    NSError *error = nil;","    [HumanSecurity startWithAppId:@\"<APP_ID>\" policy:policy error:&error];","    HumanSecurity.BD.delegate = self;","    if (error != nil) {","        NSLog(@\"error: %@\", error);","    }","    ","    [[HumanModule shared] startObserving];","","    \/\/ Configure React Native...","","    return YES;","}","","\/\/ MARK: - HSBotDefenderDelegate","","- (void)botDefenderRequestBlockedWithUrl:(NSURL *)url appId:(NSString *)appId {","  ","}","","- (void)botDefenderChallengeSolvedForAppId:(NSString *)appId {","    [[HumanModule shared] handleChallengeSolvedEvent];","}","","- (void)botDefenderChallengeCancelledForAppId:(NSString *)appId {","    [[HumanModule shared] handleChallengeCancelledEvent];","}","","- (void)botDefenderDidUpdateHeadersWithHeaders:(NSDictionary<NSString *,NSString *> *)headers forAppId:(NSString *)appId {","    [[HumanModule shared] handleUpdatedHeaders:headers];","}","","- (void)botDefenderChallengeRenderedForAppId:(NSString *)appId{","  ","}","","- (void)botDefenderChallengeRenderFailedForAppId:(NSString *)appId {","  ","}","","@end"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Don’t forget to change the "},{"type":"codeVoice","code":"<APP_ID>"},{"type":"text","text":" to your own AppID."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"We start the SDK as soon as possible and on the main thread.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We create a ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","isActive":true,"type":"reference"},{"text":" instance. This object is used to configure the SDK’s behavior. Here, we set the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","isActive":true,"type":"reference"},{"text":" property to ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true,"type":"reference"},{"text":". This means that the ","type":"text"},{"inlineContent":[{"text":"Automatic Interception","type":"text"}],"type":"emphasis"},{"text":" feature of the SDK is disabled. In short, this feature allows the SDK to manipulate URL requests and handle their responses by itself. However, this feature is not supported in React Native.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"We call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"reference","isActive":true},{"type":"text","text":" function of the SDK. We provide the following parameters:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Application"},{"text":" instance (Android only).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Your AppID.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The policy object that we configured."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"On iOS, We call the "},{"type":"codeVoice","code":"startObserving"},{"type":"text","text":" function on the "},{"type":"codeVoice","code":"HumanModule"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"text":"Note: If your app communicates with several servers that have different AppID, you can call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference","isActive":true},{"text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK.","type":"text"}]},{"type":"heading","level":2,"anchor":"How-to-add-HTTP-headers-and-handle-block-response","text":"How to add HTTP headers and handle block response"},{"type":"paragraph","inlineContent":[{"text":"In your Javascript code, you should do the following:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Import the "},{"type":"codeVoice","code":"HumanModule"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a new native event emitters."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Add listener to the “New Headers” event."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Add listener to the “Challegne Result” event."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Add The SDK’s HTTP headers to your URL requests."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a request is blocked, send the block response to the SDK."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle the challenge’s result."}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"inlineContent":[{"type":"text","text":"Javascript:"}],"type":"paragraph"},{"syntax":"javascript","code":["\/* Import HumanModule *\/","import {NativeModules, NativeEventEmitter} from 'react-native';","import type {Message} from 'react-native\/Libraries\/LogBox\/Data\/parseLogBoxLog';","const {HumanModule} = NativeModules;","","\/* Create a new native event emitter *\/","const humanEventEmitter = new NativeEventEmitter(HumanModule);","","\/* Add listener to the \"New Headers\" event and store the SDK's HTTP headers in a variable *\/","var humanHttpHeaders = null;","const onNewHeaders = headers => {","    const obj = JSON.parse(headers);","    console.log(`got new http headers: ${JSON.stringify(obj)}`);","    humanHttpHeaders = obj;","};","const subscriptionHumanNewHeaders = humanEventEmitter.addListener('HumanNewHeaders', onNewHeaders);","","\/* Add listener to the \"Challenge Result\" event *\/","const onChallengeResult = result => {","  if (result === 'solved') {","    console.log('challenge solved');","  } else if (result === 'cancelled') {","    console.log('challenge cancelled');","  }","};","const subscriptionHumanChallengeResult = humanEventEmitter.addListener('HumanChallengeResult', onChallengeResult);","","\/* Get Human's HTTP headers *\/","const getHumanHeaders = async () => {","    if (humanHttpHeaders != null) {","        return humanHttpHeaders;","    }","    const headers = await HumanModule.getHTTPHeaders();","    const obj = JSON.parse(headers);","    console.log(`[HUMAN] got http headers: ${JSON.stringify(obj)}`);","    return obj;","  }","};","","\/* Send URL request *\/","async function sentRequest(url) {","    \/* Get Human's HTTP headers *\/","    const humanHeaders = await getHumanHeaders()","","    try {","        const response = await fetch(url, {","            method: 'GET',","            headers: humanHeaders,","        });","","        const json = await response.json();","","        \/* Send the response to the SDK *\/","        const result = await HumanModule.handleResponse(JSON.stringify(json));","        if (result === 'solved') {","            console.log('challenge solved');","            await sendRequest(url);","        } else if (result === 'cancelled') {","            console.log('challenge cancelled');","        }","        else if (result === 'false') {","        console.log('request was not blocked by Human');","        } catch (error) {","            console.error(error);","        }","    }","}"],"type":"codeListing"},{"text":"Understanding the block response","anchor":"Understanding-the-block-response","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The HUMAN’s Enforcer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:","type":"text"}]},{"type":"codeListing","code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"],"syntax":"json"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON contains metadata for the SDK."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your app should pass the whole JSON to the SDK via the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","type":"reference","isActive":true},{"type":"text","text":" function. Otherwise, the SDK won’t present a challenge to the user."}]}]}],"type":"orderedList"}]}],"metadata":{"roleHeading":"Article","modules":[{"name":"HUMAN"}],"title":"React Native Integration","role":"article"},"variants":[{"paths":["\/documentation\/human\/react_native_integration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/react_native_integration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","role":"symbol","url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","text":"HSBotDefenderChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleResponseWithResponse:data:callback:"}],"type":"topic","abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"title":"handleResponse(response:data:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"kind":"symbol","title":"HSAutomaticInterceptorType.intercept","url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"intercept","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","type":"topic","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","role":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"title":"HSAutomaticInterceptorType.none"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"kind":"symbol","title":"HSPolicy","url":"\/documentation\/human\/hspolicy","navigatorTitle":[{"kind":"identifier","text":"HSPolicy"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSPolicy"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"kind":"symbol","title":"start(appIds:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","navigatorTitle":[{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HSPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"topic","abstract":[{"text":"Start the SDK.","type":"text"}]},"https://reactnative.dev/docs/native-modules-android":{"titleInlineContent":[{"type":"text","text":"native module"}],"type":"link","url":"https:\/\/reactnative.dev\/docs\/native-modules-android","title":"native module","identifier":"https:\/\/reactnative.dev\/docs\/native-modules-android"},"https://reactnative.dev/":{"type":"link","identifier":"https:\/\/reactnative.dev\/","titleInlineContent":[{"text":"React Native","type":"text"}],"title":"React Native","url":"https:\/\/reactnative.dev\/"},"https://reactnative.dev/docs/native-modules-ios":{"titleInlineContent":[{"type":"text","text":"native module"}],"type":"link","url":"https:\/\/reactnative.dev\/docs\/native-modules-ios","title":"native module","identifier":"https:\/\/reactnative.dev\/docs\/native-modules-ios"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"start(appId:policy:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title","value":"handleResponseWithResponse:data:callback:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleResponseWithResponse:data:callback:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","value":"HSAutomaticInterceptorTypeIntercept","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title","value":"startWithAppIds:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","value":"startWithAppId:policy:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}