{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"HUMAN"}],"title":"visionOS Integration (sheet)"},"primaryContentSections":[{"content":[{"anchor":"Introduction","text":"Introduction","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"In this article we will learn how integrate the SDK to your visionOS app.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sheet option will present the HUMAN challenge in a sheet over the window the request has left from, this will disable the user to continue any interactions in the screen until the challenge is solved."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"You will need to add the sheet integration code to every view sending requests that might be blocked."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We will cover the following topics:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#how-to-start-the-sdk"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#bot-defender-integration","isActive":true}]},{"items":[{"content":[{"inlineContent":[{"text":"How to add the SDK’s HTTP headers to your URL requests.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How to handle the blocked request.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"How to present a challenge to the user in a sheet."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How to set custom parameters (optional).","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#account-defender-integration"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to enable it."}]}]},{"content":[{"inlineContent":[{"text":"How to notify HUMAN’s backend on outgoing URL requests from the app.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"How to set additional data (optional).","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"}]}]},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Some features, including the Doctor App, Automatic Interceptor and Hybrid App support, are not available in the SDK for visionOS yet. We will add those features soon."}],"type":"strong"}],"type":"paragraph"},{"level":2,"anchor":"How-to-start-the-SDK","type":"heading","text":"How to start the SDK"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the ","type":"text"},{"type":"codeVoice","code":"App"},{"text":"’s ","type":"text"},{"code":"init","type":"codeVoice"},{"type":"text","text":" function on visionOS."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should start the SDK on the "},{"type":"strong","inlineContent":[{"text":"main thread","type":"text"}]},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Note that some SDK features that exist in iOS are currently not available in visionOS."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"code":["import UIKit","import HUMAN","","@main","struct MyApp: App {","","    init() {","        startHumanSDK()","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t forget to change the "},{"code":"<APP_ID>","type":"codeVoice"},{"type":"text","text":" to your own AppID."}]},{"inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"We start the SDK as soon as possible and on the main thread.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We create a ","type":"text"},{"type":"codeVoice","code":"HSPolicy"},{"text":" instance. This object is used to configure the SDK’s behavior.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"We call the "},{"type":"codeVoice","code":"start"},{"type":"text","text":" function of the SDK. We provide the following parameters:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your AppID."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The policy object that we configured."}]}]}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: If your app communicates with several servers that have different AppID, you can call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},{"type":"text","text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK."}]},{"anchor":"Bot-Defender-integration","level":2,"type":"heading","text":"Bot Defender integration"},{"type":"heading","text":"How to add the SDK’s HTTP headers to your URL requests and handle the blocked request","anchor":"How-to-add-the-SDKs-HTTP-headers-to-your-URL-requests-and-handle-the-blocked-request","level":3},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK provides HTTP headers that should be added to your app’s URL requests. "},{"inlineContent":[{"text":"It is essential that those HTTP headers will be included on every URL request","type":"text"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You "},{"type":"strong","inlineContent":[{"text":"should not","type":"text"}]},{"text":" cache those HTTP headers. They contain a token with expiration date. The SDK manages this token to be up-to-date.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You should add the ","type":"text"},{"type":"codeVoice","code":"HSChallengeView"},{"type":"text","text":" for each view that could have blocked requests. The "},{"type":"codeVoice","code":"HSChallengeView"},{"text":" must be the first component in the ","type":"text"},{"code":"body","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"HSChallengeView","type":"codeVoice"},{"text":" will handle the presentation of the challenge.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"You should call the ","type":"text"},{"code":"HSChallengeModelViewHelper\/registerError(error:uuid:callback:)","type":"codeVoice"},{"type":"text","text":" function for every block error you get. You need to provide a unique identifier that represent the view which the "},{"code":"HSChallengeView","type":"codeVoice"},{"text":" is placed into. You may provide a callback that will be called once the challenge was solved\/cancelled.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You should call the ","type":"text"},{"code":"HSChallengeModelViewHelper\/unregister(uuid:)","type":"codeVoice"},{"text":" when your view is disappearing. This will release related resources to prevent a memory leak.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"code":["import SwiftUI","import HUMAN","","struct ContentView: View {","","    @State private var model = ViewModel()","        ","    var body: some View {","        VStack {","            HSChallengeView(uuid: model.challengeUUID)","            ","            HStack {","                Button(\"Send request\") {","                    model.performRequest()","                }.padding()","            }","        }","        .onDisappear() {","            HSChallengeModelViewHelper.unregister(uuid: model.challengeUUID)","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["import Foundation","import HUMAN","","@Observable","class ViewModel {","    ","    let myURL: URL","    let challengeUUID = UUID().uuidString","    ","    func performRequest() {","        sendUrlRequest(url: myURL) { result, error in","            if let error {","                HSChallengeModelViewHelper.registerError(error: error, uuid: challengeUUID) { result in","                    print(\"challenge result = \\(result)\")","                }","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","syntax":"swift","code":["import Foundation","import HUMAN","","func sendUrlRequest(url: URL, completion: @escaping (Bool, Error?) -> ()) {","    var request = URLRequest(url: url)","    let myHttpHeaders = [String : String]()","","    \/\/ config your request and HTTP headers...","","    let humanHttpHeaders = HumanSecurity.BD.headersForURLRequest(forAppId: \"<APP_ID>\")","    request.allHTTPHeaderFields = myHttpHeaders.merging(humanHttpHeaders) { $1 }","","    let dataTask = URLSession.shared.dataTask(with: request) { data, response, error in","        if let data = data, let response = response as? HTTPURLResponse {","            if let error = HumanSecurity.blockError(response: response, data: data) {","                completion(false, error)","                return","            }","            \/\/ handle the response...","        }","    }","    dataTask.resume()","}"]},{"type":"paragraph","inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"We add the ","type":"text"},{"code":"HSChallengeView","type":"codeVoice"},{"type":"text","text":" to the "},{"type":"codeVoice","code":"ContentView"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"body"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"We call the ","type":"text"},{"code":"HSChallengeModelViewHelper\/unregister(uuid:)","type":"codeVoice"},{"type":"text","text":" function when the "},{"code":"ContentView","type":"codeVoice"},{"type":"text","text":" is disappearing."}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Model \/ HTTP client:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"We get the SDK’s HTTP headers.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We add those HTTP headers to our URL requests."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We send the URL request.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We send the response to the SDK. The SDK will check if it’s a blocked request. If yes, it will return a block error.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"We return the block error back to the ","type":"text"},{"code":"ViewModel","type":"codeVoice"},{"type":"text","text":"."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"View Model:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"We declare a unique identifier ("},{"type":"codeVoice","code":"challengeUUID"},{"text":") for the view.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We call the ","type":"text"},{"code":"HSChallengeModelViewHelper\/registerError(error:uuid:callback:)","type":"codeVoice"},{"type":"text","text":" function when we get an error (the SDK hanldes blocked requests only and ignores other kinds of error)."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We provide an optional callback that will be called when the challenge was solved\/cancelled."}]}]}]}]}],"type":"unorderedList"},{"anchor":"What-should-I-do-when-a-request-is-blocked","type":"heading","text":"What should I do when a request is blocked","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Handle it as a failure.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Your app should handle the blocked request as a failure. However, you should consider that other windows in your app’s UI are still shown while the challenge is presented to the user. If the request was triggered by a user’s action, you should make it clear that the user may try again the same action.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Use the handler callback to write analyitics, logs, etc.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You may use the handler callback to retry the original request When appropriate. You should consider the following:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"The callback is called out of the original request’s scope. Meaning, you will need to ensure your app handles this case correctly.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The challenge could be canceled by the user. In this case, you should not retry the request because it will be blocked again."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"It’s possible that the retry attempt will be blocked as well. DO NOT assume that it will go through."}]}]}]}]}]},{"anchor":"Understanding-the-block-response","type":"heading","level":3,"text":"Understanding the block response"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The HUMAN’s Enfrocer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:"}]},{"type":"codeListing","syntax":"json","code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON contains metadata for the SDK."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"This metadata included inside the block error you get via the "},{"code":"HumanSecurity\/blockError(response:data:forAppId:)","type":"codeVoice"},{"type":"text","text":" fucntion."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Your app should pass the error object to the SDK via the ","type":"text"},{"code":"HSChallengeModelViewHelper\/registerError(error:uuid:callback:)","type":"codeVoice"},{"type":"text","text":" function with the view’s uuid. Otherwise, the SDK won’t presnet a challenge to the user."}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"heading","text":"How to set custom parameters for Bot Defender (optional)","level":3,"anchor":"How-to-set-custom-parameters-for-Bot-Defender-optional"},{"type":"paragraph","inlineContent":[{"text":"You can set custom parameters in order to configure HUMNAN’s backend with additional parameters.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android), with the key “","type":"text"},{"code":"custom_param[x]","type":"codeVoice"},{"text":"” where ","type":"text"},{"code":"[x]","type":"codeVoice"},{"text":" is a number between ","type":"text"},{"code":"1-10","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","isActive":true,"type":"reference"},{"text":" only after the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"type":"text","text":" function was already called."}]},{"type":"paragraph","inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"type":"codeListing","code":["import HUMAN","","func setCustomParametersForBotDefender() {","    do {","        var customParameters = [String: String]()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        try HumanSecurity.BD.setCustomParameters(parameters: customParameters, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"syntax":"swift"},{"level":2,"text":"Account Defender integration","type":"heading","anchor":"Account-Defender-integration"},{"type":"heading","level":3,"anchor":"How-to-enbale-Account-Defender-in-your-app","text":"How to enbale Account Defender in your app?"},{"inlineContent":[{"type":"text","text":"In order to enable Account Defedner, you should set the "},{"type":"codeVoice","code":"UserID"},{"type":"text","text":" of your current logged-in user in the SDK."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Here is an example of how it should be:","type":"text"}]},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"type":"codeListing","code":["import HUMAN","","func onUserLoggedIn(userID: String) {","    do {","        try HumanSecurity.AD.setUserId(userId: userID, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"syntax":"swift"},{"type":"heading","level":3,"text":"How to notify HUMAN’s backend on outgoing URL requests from the app","anchor":"How-to-notify-HUMANs-backend-on-outgoing-URL-requests-from-the-app"},{"inlineContent":[{"type":"text","text":"In order to allow Account Defender protect the user’s account, your app has to provide the SDK with outgoing URL requests."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import HUMAN","","func sendUrlRequest(url: URL) {","    do {","        try HumanSecurity.AD.registerOutgoingUrlRequest(url: url.absoluteString, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","","    \/\/ Send the request...","}"]},{"inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"We call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","isActive":true,"type":"reference"},{"type":"text","text":" function before we send the URL request."}]}]}],"type":"orderedList"},{"anchor":"How-to-set-additional-data-optional","text":"How to set additional data (optional)","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You can set additional data in order to configure HUMNAN’s backend with additional parameters.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Those parameters can be set with a dictionary."}],"type":"paragraph"},{"inlineContent":[{"text":"You should call the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)"},{"text":" only after the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","isActive":true},{"text":" function was already called.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["import HUMAN","","func setAdditionalDataForAccountDefender() {","    do {","        var additionalData = [String: String]()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        try HumanSecurity.AD.setAdditionalData(parameters: additionalData, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]}],"kind":"content"}],"sections":[],"kind":"article","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/human\/visionos_integration_sheet"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/visionos_integration_sheet"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"#bot-defender-integration":{"titleInlineContent":[{"type":"text","text":"Bot Defender integration"}],"url":"#bot-defender-integration","type":"link","identifier":"#bot-defender-integration","title":"Bot Defender integration"},"#how-to-start-the-sdk":{"titleInlineContent":[{"type":"text","text":"How to start the SDK"}],"url":"#how-to-start-the-sdk","type":"link","identifier":"#how-to-start-the-sdk","title":"How to start the SDK"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/registerOutgoingUrlRequest(url:forAppId:)":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","title":"registerOutgoingUrlRequest(url:forAppId:)","abstract":[{"type":"text","text":"Provide outgoing URL request to the Account Defender feature."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}]},"#account-defender-integration":{"titleInlineContent":[{"type":"text","text":"Account Defender integration"}],"url":"#account-defender-integration","type":"link","identifier":"#account-defender-integration","title":"Account Defender integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"title":"start(appId:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"role":"symbol","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"abstract":[{"text":"Set additional data that support Account Defender for given AppID.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","role":"symbol","url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","title":"setAdditionalData(parameters:forAppId:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdditionalData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"abstract":[{"type":"text","text":"Start the SDK."}],"kind":"symbol","title":"start(appIds:policy:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"policy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","role":"symbol","url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/setCustomParameters(parameters:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomParameters"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"title":"setCustomParameters(parameters:forAppId:)","url":"\/documentation\/human\/hsbotdefender\/setcustomparameters(parameters:forappid:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/title","op":"replace","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title","value":"startWithAppId:policy:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:policy:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title","op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments"},{"op":"replace","value":"startWithAppIds:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"startWithAppIds:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments","op":"replace"},{"value":"setCustomParametersWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}