{"metadata":{"roleHeading":"Article","title":"visionOS Integration (window)","modules":[{"name":"HUMAN"}],"role":"article"},"primaryContentSections":[{"content":[{"anchor":"Introduction","text":"Introduction","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"In this article we will learn how integrate the SDK to your visionOS app."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The window option will display the HUMAN challenge in a separate window,","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"the code integration will be added once, and cover all requests sent from anywhere in the app, background or foreground.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The challenge window does not block the window the user was interacting with, and can be moved to the side by the user,","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"however once blocked the calls will not go throw until the challenge is resolved.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"We will cover the following topics:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"#how-to-start-the-sdk","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#bot-defender-integration","isActive":true,"type":"reference"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"How to add the SDK’s HTTP headers to your URL requests.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to handle the blocked request."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"How to present a challenge to the user in a new window."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"How to set custom parameters (optional)."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#account-defender-integration"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"How to enable it.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How to notify HUMAN’s backend on outgoing URL requests from the app.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How to set additional data (optional).","type":"text"}]}]}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Note that in order to use challenge in a widnow you have to "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/visionos\/presenting-windows-and-spaces#Enable-multiple-simultaneous-scenes","isActive":true},{"type":"text","text":" in you app’s info.plist."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Some features, including the Doctor App, Automatic Interceptor and Hybrid App support, are not available in the SDK for visionOS yet. We will add those features soon."}],"type":"strong"}],"type":"paragraph"},{"anchor":"How-to-start-the-SDK","text":"How to start the SDK","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The most important thing is to start the SDK as soon as possible in your app flow. The reason for that is when your app will send an URL request to your server before the SDK was started, the request will not include the SDK’s HTTP headers. As a result, HUMAN’s Enforcer could block the request and the SDK will not be able to present a challenge to the user. The best place to start the SDK is in the ","type":"text"},{"code":"App","type":"codeVoice"},{"text":"’s ","type":"text"},{"code":"init","type":"codeVoice"},{"text":" function on visionOS.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You should start the SDK on the ","type":"text"},{"inlineContent":[{"type":"text","text":"main thread"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Note that some SDK features that exist in iOS are currently not available in visionOS."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"code":["import UIKit","import HUMAN","","@main","struct MyApp: App {","","    init() {","        startHumanSDK()","    }","","    func startHumanSDK() {","        do {","            let policy = HSPolicy()","            ","            try HumanSecurity.start(appId: \"<APP_ID>\", policy: policy)","        }","        catch {","            print(\"Error: \\(error)\")","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Don’t forget to change the ","type":"text"},{"code":"<APP_ID>","type":"codeVoice"},{"text":" to your own AppID.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Let’s talk about what we have in the code here:","type":"text"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"We start the SDK as soon as possible and on the main thread."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"We create a "},{"type":"codeVoice","code":"HSPolicy"},{"type":"text","text":" instance. This object is used to configure the SDK’s behavior."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"We call the "},{"type":"codeVoice","code":"start"},{"type":"text","text":" function of the SDK. We provide the following parameters:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Your AppID.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The policy object that we configured.","type":"text"}]}]}],"type":"unorderedList"}]}]},{"inlineContent":[{"text":"Note: If your app communicates with several servers that have different AppID, you can call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","type":"reference","isActive":true},{"type":"text","text":" function which allow you to pass an array of AppIDs. You should specify the relevant AppID for each API call in the SDK."}],"type":"paragraph"},{"level":2,"anchor":"Bot-Defender-integration","type":"heading","text":"Bot Defender integration"},{"level":3,"text":"How to add the SDK’s HTTP headers to your URL requests and handle the blocked request","anchor":"How-to-add-the-SDKs-HTTP-headers-to-your-URL-requests-and-handle-the-blocked-request","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK provides HTTP headers that should be added to your app’s URL requests. ","type":"text"},{"inlineContent":[{"type":"text","text":"It is essential that those HTTP headers will be included on every URL request"}],"type":"strong"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You ","type":"text"},{"inlineContent":[{"type":"text","text":"should not"}],"type":"strong"},{"text":" cache those HTTP headers. They contain a token with expiration date. The SDK manages this token to be up-to-date.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK handles the blocked request and present a challenge to the user.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You should note that the challenge window affects your application. You should remember to clean up the challenge window in case it is the last window left in the app. In the example below we added the onChange on scenePhase environment variable to check when a window is closed, in that case we will check if challenge window is the only other window and is showen and will close it, if you have a different place in the app where you clean up - you can move the code of closing the window in case it is open their.","type":"text"}]}]}]},{"inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"code":["import SwiftUI","import HUMAN","","@main","struct MyApp: App {","        ","    @Environment(\\.scenePhase) var scenePhase","    @Environment(\\.openWindow) private var openHumanChallengeWindow","    @Environment(\\.dismissWindow) private var dismissHumanChallengeWindow","    ","    init() {","        \/\/ start HUMAN...","    }","    ","    var body: some Scene {","        \/\/ your main window and content.","        WindowGroup {","            ContentView()","        }","        ","        \/\/ HUMAN's challenge window.","        WindowGroup(id: HSChallengeViewModel.name) {","            HSChallengeView()","        }","        .defaultSize(width: HSChallengeViewModel.width,","                     height: HSChallengeViewModel.height, depth: 0)","        .onChange(of: HSChallengeViewModel.shared.showChallenge, {","            if (HSChallengeViewModel.shared.showChallenge) {","                openHumanChallengeWindow(id: HSChallengeViewModel.name)","            }","            else {","                dismissHumanChallengeWindow(id: HSChallengeViewModel.name)","            }","        })","        .onChange(of: scenePhase) { oldPhase, newPhase in","             if (newPhase == .background && UIApplication.shared.connectedScenes.count == 2) {","                if (HSChallengeViewModel.shared.showChallenge) {","                    dismissHumanChallengeWindow(id: HSChallengeViewModel.name)","                }","            }","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Swift:"}],"type":"paragraph"},{"code":["import HUMAN","","func sendUrlRequest(url: URL) {","    var request = URLRequest(url: url)","    let myHttpHeaders = [String : String]()","","    \/\/ config your request and HTTP headers...","","    let humanHttpHeaders = HumanSecurity.BD.headersForURLRequest(forAppId: \"<APP_ID>\")","    request.allHTTPHeaderFields = myHttpHeaders.merging(humanHttpHeaders) { $1 }","","    let dataTask = URLSession.shared.dataTask(with: request) { data, response, error in","        if let data = data, let response = response as? HTTPURLResponse {","            let isHandled = HumanSecurity.handleResponse(response: response, data: data) { result in","                print(\"Challenge result = \\(result)\")","                \/\/ You may retry the request here.","            }","            if isHandled {","                print(\"Blocked response was handled by the SDK\")","            }","        }","    }","    dataTask.resume()","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"View (App):","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"We add the @Environment(.openWindow) and @Environment(.dismissWindow) properties and call them based on the ","type":"text"},{"code":"HSChallengeViewModel\/showChallenge","type":"codeVoice"},{"text":" observable in the SDK.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We add the challenge window in the ","type":"text"},{"code":"App","type":"codeVoice"},{"text":"’s ","type":"text"},{"code":"body","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We add the @Environment(.scenePhase) and make sure to close the challenge in case it is the last open window in the app.","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Model \/ HTTP client:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"We get the SDK’s HTTP headers.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We add those HTTP headers to our URL requests.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We send the URL request.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We send the response to the SDK. The SDK will check if it’s a blocked request. If yes, it will present a challenge to the user.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We print the challenge result (solved\/cancelled) in the completion handler.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"We may retry the request here.","type":"text"}],"type":"paragraph"}]}]}]}]},{"level":3,"text":"What should I do when a request is blocked","anchor":"What-should-I-do-when-a-request-is-blocked","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Handle it as a failure.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Your app should handle the blocked request as a failure. However, you should consider that your app’s UI is still shown while the challenge is presented to the user. If the request was triggered by a user’s action, you should make it clear that the user may try again the same action.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Use the handler callback to write analyitics, logs, etc.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"You may use the handler callback to retry the original request When appropriate. You should consider the following:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"The callback is called out of the original request’s scope. Meaning, you will need to ensure your app handles this case correctly.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The challenge could be canceled by the user. In this case, you should not retry the request because it will be blocked again.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"It’s possible that the retry attempt will be blocked as well. DO NOT assume that it will go through.","type":"text"}],"type":"paragraph"}]}]}]}]},{"anchor":"Understanding-the-block-response","type":"heading","level":3,"text":"Understanding the block response"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"The HUMAN’s Enfrocer, when it decides to block a request, returns a JSON string in the response’s body. The HTTP status code is 403. Here is an example of the response:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"json","code":["{","  \"vid\": \"928d7ab3-9cf1-11ee-a624-b802520f369f\",","  \"uuid\": \"fd01e6d6-9cf2-11ee-808c-acde48001122\",","  \"page\": \"PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiPgogICAgPHRpdGxlPkFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkLjwvdGl0bGU+CiAgICA8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9T3BlbitTYW5zOjMwMCIgcmVsPSJzdHlsZXNoZWV0Ij4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgICBmb250LWZhbWlseTogJ09wZW4gU2FucycsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgIGNvbG9yOiAjMDAwOwogICAgICAgIH0KCiAgICAgICAgYSB7CiAgICAgICAgICAgIGNvbG9yOiAjYzVjNWM1OwogICAgICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyIHsKICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICAgICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgICAgZmxleDogMTsKICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgfQoKICAgICAgICAuY29udGFpbmVyID4gZGl2IHsKICAgICAgICAgICAgd2lkdGg6IDEwMCU7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIH0KCiAgICAgICAgLmNvbnRhaW5lciA+IGRpdiA+IGRpdiB7CiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICAgIHdpZHRoOiA4MCU7CiAgICAgICAgfQoKICAgICAgICAuY3VzdG9tZXItbG9nby13cmFwcGVyIHsKICAgICAgICAgICAgcGFkZGluZy10b3A6IDJyZW07CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMDsKICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KCiAgICAgICAgLmN1c3RvbWVyLWxvZ28gewogICAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzAwMDsKICAgICAgICB9CgogICAgICAgIC5jdXN0b21lci1sb2dvID4gaW1nIHsKICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDFyZW07CiAgICAgICAgICAgIG1heC1oZWlnaHQ6IDUwcHg7CiAgICAgICAgICAgIG1heC13aWR0aDogMTAwJTsKICAgICAgICB9CgogICAgICAgIC5wYWdlLXRpdGxlLXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDI7CiAgICAgICAgfQoKICAgICAgICAucGFnZS10aXRsZSB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW4tcmV2ZXJzZTsKICAgICAgICB9CgogICAgICAgIC5jb250ZW50LXdyYXBwZXIgewogICAgICAgICAgICBmbGV4LWdyb3c6IDU7CiAgICAgICAgfQoKICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgfQoKICAgICAgICAucGFnZS1mb290ZXItd3JhcHBlciB7CiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgICAgICAgIGZsZXgtZ3JvdzogMC4yOwogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOwogICAgICAgICAgICBjb2xvcjogI2M1YzVjNTsKICAgICAgICAgICAgZm9udC1zaXplOiA3MCU7CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHsKICAgICAgICAgICAgaHRtbCwgYm9keSB7CiAgICAgICAgICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICA8L3N0eWxlPgogICAgPCEtLSBDdXN0b20gQ1NTIC0tPgo8L2hlYWQ+Cgo8Ym9keT4KPHNlY3Rpb24gY2xhc3M9ImNvbnRhaW5lciI+CiAgICA8ZGl2IGNsYXNzPSJjdXN0b21lci1sb2dvLXdyYXBwZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImN1c3RvbWVyLWxvZ28iPgogICAgICAgICAgICA8aW1nIHNyYz0iIiBhbHQ9IkxvZ28iLz4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS10aXRsZS13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWdlLXRpdGxlIj4KICAgICAgICAgICAgPGgxPlBsZWFzZSB2ZXJpZnkgeW91IGFyZSBhIGh1bWFuPC9oMT4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0iY29udGVudC13cmFwcGVyIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBpZD0icHgtY2FwdGNoYSI+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIEFjY2VzcyB0byB0aGlzIHBhZ2UgaGFzIGJlZW4gZGVuaWVkIGJlY2F1c2Ugd2UgYmVsaWV2ZSB5b3UgYXJlIHVzaW5nIGF1dG9tYXRpb24gdG9vbHMgdG8gYnJvd3NlIHRoZQogICAgICAgICAgICAgICAgd2Vic2l0ZS4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFRoaXMgbWF5IGhhcHBlbiBhcyBhIHJlc3VsdCBvZiB0aGUgZm9sbG93aW5nOgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDx1bD4KICAgICAgICAgICAgICAgIDxsaT4KICAgICAgICAgICAgICAgICAgICBKYXZhc2NyaXB0IGlzIGRpc2FibGVkIG9yIGJsb2NrZWQgYnkgYW4gZXh0ZW5zaW9uIChhZCBibG9ja2VycyBmb3IgZXhhbXBsZSkKICAgICAgICAgICAgICAgIDwvbGk+CiAgICAgICAgICAgICAgICA8bGk+CiAgICAgICAgICAgICAgICAgICAgWW91ciBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgY29va2llcwogICAgICAgICAgICAgICAgPC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICAgICAgPHA+CiAgICAgICAgICAgICAgICBQbGVhc2UgbWFrZSBzdXJlIHRoYXQgSmF2YXNjcmlwdCBhbmQgY29va2llcyBhcmUgZW5hYmxlZCBvbiB5b3VyIGJyb3dzZXIgYW5kIHRoYXQgeW91IGFyZSBub3QgYmxvY2tpbmcKICAgICAgICAgICAgICAgIHRoZW0gZnJvbSBsb2FkaW5nLgogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwPgogICAgICAgICAgICAgICAgUmVmZXJlbmNlIElEOiAjZmQwMWU2ZDYtOWNmMi0xMWVlLTgwOGMtYWNkZTQ4MDAxMTIyCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXItd3JhcHBlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icGFnZS1mb290ZXIiPgogICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgIFBvd2VyZWQgYnkKICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnBlcmltZXRlcnguY29tL3doeXdhc2libG9ja2VkIj5QZXJpbWV0ZXJYPC9hPgogICAgICAgICAgICAgICAgLCBJbmMuCiAgICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgIDwvZGl2Pgo8L3NlY3Rpb24+CjwhLS0gUHggLS0+CjxzY3JpcHQ+CiAgICB3aW5kb3cuX3B4QXBwSWQgPSAnUFhqOXk0UThFbSc7CiAgICB3aW5kb3cuX3B4SnNDbGllbnRTcmMgPSAnLy9jbGllbnQucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9tYWluLm1pbi5qcyc7CiAgICB3aW5kb3cuX3B4Rmlyc3RQYXJ0eUVuYWJsZWQgPSBmYWxzZTsKICAgIHdpbmRvdy5fcHhWaWQgPSAnOTI4ZDdhYjMtOWNmMS0xMWVlLWE2MjQtYjgwMjUyMGYzNjlmJzsKICAgIHdpbmRvdy5fcHhVdWlkID0gJ2ZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMic7CiAgICB3aW5kb3cuX3B4SG9zdFVybCA9ICcvL2NvbGxlY3Rvci1QWGo5eTRROEVtLnBlcmltZXRlcngubmV0JzsKPC9zY3JpcHQ+CjwhLS0gQ2FwdGNoYSAtLT4KPHNjcmlwdD4KICAgIHZhciBzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICBzLnNyYyA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnOwogICAgdmFyIHAgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnaGVhZCcpWzBdOwogICAgcC5pbnNlcnRCZWZvcmUocywgbnVsbCk7CiAgICBpZiAoZmFsc2UpIHsKICAgICAgICBzLm9uZXJyb3IgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIHMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgICAgICAgdmFyIHN1ZmZpeEluZGV4ID0gJy8vY2FwdGNoYS5wZXJpbWV0ZXJ4Lm5ldC9QWGo5eTRROEVtL2NhcHRjaGEuanM\/YT1jJm09MSZ1PWZkMDFlNmQ2LTljZjItMTFlZS04MDhjLWFjZGU0ODAwMTEyMiZ2PTkyOGQ3YWIzLTljZjEtMTFlZS1hNjI0LWI4MDI1MjBmMzY5ZicuaW5kZXhPZignY2FwdGNoYS5qcycpOwogICAgICAgICAgICB2YXIgdGVtcGVyZWRCbG9ja1NjcmlwdCA9ICcvL2NhcHRjaGEucGVyaW1ldGVyeC5uZXQvUFhqOXk0UThFbS9jYXB0Y2hhLmpzP2E9YyZtPTEmdT1mZDAxZTZkNi05Y2YyLTExZWUtODA4Yy1hY2RlNDgwMDExMjImdj05MjhkN2FiMy05Y2YxLTExZWUtYTYyNC1iODAyNTIwZjM2OWYnLnN1YnN0cmluZyhzdWZmaXhJbmRleCk7CiAgICAgICAgICAgIHMuc3JjID0gJy8vY2FwdGNoYS5weC1jZG4ubmV0L1BYajl5NFE4RW0vJyArIHRlbXBlcmVkQmxvY2tTY3JpcHQ7CiAgICAgICAgICAgIHAucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgcCk7CiAgICAgICAgfTsKICAgIH0KPC9zY3JpcHQ+CjwhLS0gQ3VzdG9tIFNjcmlwdCAtLT4KPC9ib2R5Pgo8L2h0bWw+Cg==\",","  \"appId\": \"PXj9y4Q8Em\",","  \"action\": \"captcha\",","  \"collectorUrl\": \"https:\/\/collector-pxj9y4q8em.perimeterx.net\"","}"]}]},{"content":[{"inlineContent":[{"type":"text","text":"The JSON contains metadata for the SDK."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Your app should pass the whole JSON to the SDK via the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","type":"reference"},{"text":" function. Otherwise, the SDK won’t presnet a challenge to the user.","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","level":3,"text":"How to set custom parameters for Bot Defender (optional)","anchor":"How-to-set-custom-parameters-for-Bot-Defender-optional"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can set custom parameters in order to configure HUMNAN’s backend with additional parameters."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Those parameters can be set with a dictionary (iOS) or an hash map (Android), with the key “"},{"type":"codeVoice","code":"custom_param[x]"},{"type":"text","text":"” where "},{"type":"codeVoice","code":"[x]"},{"type":"text","text":" is a number between "},{"type":"codeVoice","code":"1-10"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"You should call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)"},{"text":" only after the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"text":" function was already called.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"paragraph","inlineContent":[{"text":"Swift:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func setCustomParametersForBotDefender() {","    do {","        var customParameters = [String: String]()","        customParameters[\"custom_param1\"] = \"hello\"","        customParameters[\"custom_param2\"] = \"world\"","        try HumanSecurity.BD.setCustomParameters(parameters: customParameters, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]},{"anchor":"Account-Defender-integration","type":"heading","text":"Account Defender integration","level":2},{"anchor":"How-to-enbale-Account-Defender-in-your-app","type":"heading","text":"How to enbale Account Defender in your app?","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to enable Account Defedner, you should set the "},{"type":"codeVoice","code":"UserID"},{"type":"text","text":" of your current logged-in user in the SDK."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is an example of how it should be:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func onUserLoggedIn(userID: String) {","    do {","        try HumanSecurity.AD.setUserId(userId: userID, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"]},{"type":"heading","level":3,"text":"How to notify HUMAN’s backend on outgoing URL requests from the app","anchor":"How-to-notify-HUMANs-backend-on-outgoing-URL-requests-from-the-app"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to allow Account Defender protect the user’s account, your app has to provide the SDK with outgoing URL requests."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift:"}]},{"type":"codeListing","syntax":"swift","code":["import HUMAN","","func sendUrlRequest(url: URL) {","    do {","        try HumanSecurity.AD.registerOutgoingUrlRequest(url: url.absoluteString, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","","    \/\/ Send the request...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s talk about what we have in the code here:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"We call the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","isActive":true},{"text":" function before we send the URL request.","type":"text"}],"type":"paragraph"}]}]},{"anchor":"How-to-set-additional-data-optional","type":"heading","text":"How to set additional data (optional)","level":3},{"type":"paragraph","inlineContent":[{"text":"You can set additional data in order to configure HUMNAN’s backend with additional parameters.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Those parameters can be set with a dictionary."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","type":"reference","isActive":true},{"type":"text","text":" only after the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)"},{"type":"text","text":" function was already called."}]},{"inlineContent":[{"text":"Swift:","type":"text"}],"type":"paragraph"},{"code":["import HUMAN","","func setAdditionalDataForAccountDefender() {","    do {","        var additionalData = [String: String]()","        additionalData[\"my_key1\"] = \"hello\"","        additionalData[\"my_key2\"] = \"world\"","        try HumanSecurity.AD.setAdditionalData(parameters: additionalData, forAppId: \"<APP_ID>\")","    }","    catch {","        print(\"Error: \\(error)\")","    }","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/visionos_integration_window"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/visionos_integration_window"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"#account-defender-integration":{"url":"#account-defender-integration","identifier":"#account-defender-integration","type":"link","title":"Account Defender integration","titleInlineContent":[{"type":"text","text":"Account Defender integration"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/setCustomParameters(parameters:forAppId:)":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/setCustomParameters(parameters:forAppId:)","url":"\/documentation\/human\/hsbotdefender\/setcustomparameters(parameters:forappid:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomParameters","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"setCustomParameters(parameters:forAppId:)","kind":"symbol","abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"navigatorTitle":[{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/registerOutgoingUrlRequest(url:forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/registerOutgoingUrlRequest(url:forAppId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Provide outgoing URL request to the Account Defender feature."}],"navigatorTitle":[{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"title":"registerOutgoingUrlRequest(url:forAppId:)","url":"\/documentation\/human\/hsaccountdefender\/registeroutgoingurlrequest(url:forappid:)","kind":"symbol","type":"topic","role":"symbol"},"#how-to-start-the-sdk":{"url":"#how-to-start-the-sdk","identifier":"#how-to-start-the-sdk","type":"link","title":"How to start the SDK","titleInlineContent":[{"text":"How to start the SDK","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender/setAdditionalData(parameters:forAppId:)":{"abstract":[{"text":"Set additional data that support Account Defender for given AppID.","type":"text"}],"title":"setAdditionalData(parameters:forAppId:)","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender\/setAdditionalData(parameters:forAppId:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"url":"\/documentation\/human\/hsaccountdefender\/setadditionaldata(parameters:forappid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdditionalData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/handleResponse(response:data:callback:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/handleResponse(response:data:callback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"HSBotDefenderChallengeResult","preciseIdentifier":"c:@M@HUMAN@E@HSBotDefenderChallengeResult","kind":"typeIdentifier"},{"text":") -> ())?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"This function handles the URL request’s response and presents the block screen, if necessary.","type":"text"}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:callback:","kind":"identifier"}],"title":"handleResponse(response:data:callback:)","url":"\/documentation\/human\/hsbotdefender\/handleresponse(response:data:callback:)","kind":"symbol","type":"topic","role":"symbol"},"#bot-defender-integration":{"type":"link","identifier":"#bot-defender-integration","title":"Bot Defender integration","titleInlineContent":[{"type":"text","text":"Bot Defender integration"}],"url":"#bot-defender-integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:policy:)","title":"start(appIds:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"url":"\/documentation\/human\/humansecurity\/start(appids:policy:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:policy:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HSPolicy","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:policy:error:"}],"title":"start(appId:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:policy:)","role":"symbol","url":"\/documentation\/human\/humansecurity\/start(appid:policy:)"},"https://developer.apple.com/documentation/visionos/presenting-windows-and-spaces#Enable-multiple-simultaneous-scenes":{"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/visionos\/presenting-windows-and-spaces#Enable-multiple-simultaneous-scenes","title":"enable multiple windows","titleInlineContent":[{"text":"enable multiple windows","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/visionos\/presenting-windows-and-spaces#Enable-multiple-simultaneous-scenes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"setCustomParametersWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1setCustomParameters(parameters:forAppId:)\/fragments"},{"op":"replace","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1registerOutgoingUrlRequest(url:forAppId:)\/fragments"},{"op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender~1setAdditionalData(parameters:forAppId:)\/fragments"},{"op":"replace","value":"handleResponseWithResponse:data:callback:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleResponseWithResponse:data:callback:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1handleResponse(response:data:callback:)\/fragments"},{"op":"replace","value":"startWithAppIds:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:policy:)\/fragments"},{"op":"replace","value":"startWithAppId:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:policy:)\/fragments"}]}]}