{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeRenderFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The AppID that related to the event."}],"type":"paragraph"}],"name":"appId"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerenderfailed(forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerenderfailed(forappid:)"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRenderFailed(forAppId:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"botDefenderChallengeRenderFailed(forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderChallengeRenderFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate(im)botDefenderChallengeRenderFailedForAppId:","navigatorTitle":[{"kind":"identifier","text":"botDefenderChallengeRenderFailedForAppId:"}]},"abstract":[{"text":"Called when the challenge was failed to render.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"url":"\/documentation\/human\/hsbotdefenderdelegate","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","title":"HSBotDefenderDelegate"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeRenderFailed(forAppId:)":{"title":"botDefenderChallengeRenderFailed(forAppId:)","navigatorTitle":[{"kind":"identifier","text":"botDefenderChallengeRenderFailedForAppId:"}],"type":"topic","abstract":[{"type":"text","text":"Called when the challenge was failed to render."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRenderFailed(forAppId:)","kind":"symbol","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerenderfailed(forappid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderChallengeRenderFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"botDefenderChallengeRenderFailedForAppId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderChallengeRenderFailedForAppId:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"botDefenderChallengeRenderFailedForAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The AppID that related to the event.","type":"text"}]}],"name":"appId"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"HSBotDefenderDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title","op":"replace"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","op":"replace"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle","op":"replace"},{"value":"botDefenderChallengeRenderFailedForAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRenderFailed(forAppId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderChallengeRenderFailedForAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRenderFailed(forAppId:)\/fragments","op":"replace"}]}]}