{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)"},{"type":"text","text":" function for every URL request."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderdidupdateheaders(headers:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderdidupdateheaders(headers:forappid:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderDidUpdateHeaders(headers:forAppId:)"},"metadata":{"externalID":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate(im)botDefenderDidUpdateHeadersWithHeaders:forAppId:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:"}],"title":"botDefenderDidUpdateHeaders(headers:forAppId:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderDidUpdateHeaders","kind":"identifier"},{"text":"(","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"HUMAN"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderDidUpdateHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"headers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HTTP headers."}]}]},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID that related to the event.","type":"text"}]}]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender/headersForURLRequest(forAppId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","url":"\/documentation\/human\/hsbotdefender\/headersforurlrequest(forappid:)","role":"symbol","type":"topic","kind":"symbol","title":"headersForURLRequest(forAppId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headersForURLRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"abstract":[{"text":"Returns HTTP headers that should be added to the URL request.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderDidUpdateHeaders(headers:forAppId:)":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderDidUpdateHeaders(headers:forAppId:)","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderdidupdateheaders(headers:forappid:)","navigatorTitle":[{"text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","kind":"identifier"}],"title":"botDefenderDidUpdateHeaders(headers:forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderDidUpdateHeaders"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender\/headersForURLRequest(forAppId:)","isActive":true},{"type":"text","text":" function for every URL request."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"url":"\/documentation\/human\/hsbotdefenderdelegate","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","title":"HSBotDefenderDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"botDefenderDidUpdateHeadersWithHeaders:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"headers"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"headers","content":[{"inlineContent":[{"type":"text","text":"HTTP headers."}],"type":"paragraph"}]},{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID that related to the event."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"headersForURLRequestForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender~1headersForURLRequest(forAppId:)\/fragments"},{"value":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderDidUpdateHeaders(headers:forAppId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"botDefenderDidUpdateHeadersWithHeaders:forAppId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderDidUpdateHeaders(headers:forAppId:)\/fragments"},{"value":"HSBotDefenderDelegate","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments"},{"value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle"}]}]}