{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"]]},"metadata":{"externalID":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate(im)botDefenderRequestBlockedWithUrl:appId:","navigatorTitle":[{"text":"botDefenderRequestBlockedWithUrl:appId:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"HUMAN"}],"title":"botDefenderRequestBlocked(url:appId:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderRequestBlocked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderrequestblocked(url:appid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderrequestblocked(url:appid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderRequestBlocked(url:appId:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"botDefenderRequestBlocked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"url","content":[{"inlineContent":[{"text":"The request’s URL that was blocked. Will be ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" when ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"},{"type":"text","text":" is set to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none"},{"type":"text","text":" in the policy."}],"type":"paragraph"}]},{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID that related to the event."}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Called when a request was blocked."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"url":"\/documentation\/human\/hsbotdefenderdelegate","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","title":"HSBotDefenderDelegate"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderRequestBlocked(url:appId:)":{"title":"botDefenderRequestBlocked(url:appId:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"botDefenderRequestBlockedWithUrl:appId:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderRequestBlocked(url:appId:)","abstract":[{"text":"Called when a request was blocked.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderRequestBlocked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderrequestblocked(url:appid:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"url":"\/documentation\/human\/hsautomaticinterceptortype","title":"HSAutomaticInterceptorType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/none":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"HSAutomaticInterceptorType.none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeNone","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/none"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"botDefenderRequestBlockedWithUrl:appId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderRequestBlockedWithUrl:appId:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"botDefenderRequestBlockedWithUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request’s URL that was blocked. Will be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" when "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","isActive":true},{"type":"text","text":" is set to "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/none","isActive":true},{"type":"text","text":" in the policy."}]}]},{"name":"appId","content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title","value":"HSBotDefenderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderRequestBlocked(url:appId:)\/title","value":"botDefenderRequestBlockedWithUrl:appId:","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderRequestBlocked(url:appId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"botDefenderRequestBlockedWithUrl:appId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/title","value":"HSAutomaticInterceptorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1none\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeNone"}],"op":"replace"}]}]}