{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerendered(forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerendered(forappid:)"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeRendered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The AppID that related to the event."}],"type":"paragraph"}],"name":"appId"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeRendered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"HUMAN"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(pl)HSBotDefenderDelegate(im)botDefenderChallengeRenderedForAppId:","title":"botDefenderChallengeRendered(forAppId:)","role":"symbol","symbolKind":"method"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRendered(forAppId:)"},"abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate/botDefenderChallengeRendered(forAppId:)":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate\/botDefenderChallengeRendered(forAppId:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botDefenderChallengeRendered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsbotdefenderdelegate\/botdefenderchallengerendered(forappid:)","abstract":[{"type":"text","text":"Called when the challenge was render successfully."}],"title":"botDefenderChallengeRendered(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"url":"\/documentation\/human\/hsbotdefenderdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderDelegate"}],"title":"HSBotDefenderDelegate","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"botDefenderChallengeRenderedForAppId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"appId","content":[{"inlineContent":[{"text":"The AppID that related to the event.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"botDefenderChallengeRenderedForAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRendered(forAppId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"botDefenderChallengeRenderedForAppId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate~1botDefenderChallengeRendered(forAppId:)\/fragments","op":"replace"},{"value":"HSBotDefenderDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title","op":"replace"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","op":"replace"},{"value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle","op":"replace"}]}]}