{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"externalID":"c:@M@HUMAN@E@HSBotDefenderChallengeResult@HSBotDefenderChallengeResultCancelled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResultCancelled"}],"title":"HSBotDefenderChallengeResult.cancelled"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/cancelled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/cancelled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/cancelled"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"title":"HSBotDefenderChallengeResult","role":"symbol","navigatorTitle":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefenderchallengeresult"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/cancelled":{"title":"HSBotDefenderChallengeResult.cancelled","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/cancelled","kind":"symbol","url":"\/documentation\/human\/hsbotdefenderchallengeresult\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResultCancelled"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HSBotDefenderChallengeResultCancelled","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResultCancelled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HSBotDefenderChallengeResultCancelled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HSBotDefenderChallengeResult","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title"},{"op":"replace","value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle"},{"op":"replace","value":"HSBotDefenderChallengeResultCancelled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1cancelled\/title"},{"op":"replace","value":[{"text":"HSBotDefenderChallengeResultCancelled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1cancelled\/fragments"}]}]}