{"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"HUMAN"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/equatable-implementations"]}],"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"]]},"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/!=(_:_:)"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/!=(_:_:)":{"title":"!=(_:_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/!=(_:_:)","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/!=(_:_:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","title":"HSBotDefenderChallengeResult","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"kind":"symbol","role":"symbol","url":"\/documentation\/human\/hsbotdefenderchallengeresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","value":"HSBotDefenderChallengeResult"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}