{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/hashvalue"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@HUMAN@E@HSBotDefenderChallengeResult","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"HUMAN"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"extendedModule":"Swift","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hashValue"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hashValue","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"url":"\/documentation\/human\/hsbotdefenderchallengeresult","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","kind":"symbol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"title":"HSBotDefenderChallengeResult"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/hashValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hashValue","abstract":[],"type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/hashvalue","title":"hashValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"HSBotDefenderChallengeResult","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","op":"replace"},{"value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","op":"replace"},{"value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","op":"replace"}]}]}