{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/rawrepresentable-implementations"]}],"kind":"article","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hashValue"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hash(into:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"role":"collection","title":"HUMAN","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/hash(into:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hash(into:)","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"kind":"symbol","title":"hash(into:)","abstract":[],"url":"\/documentation\/human\/hsbotdefenderchallengeresult\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/hashValue":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/hashValue","abstract":[],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","role":"symbol","type":"topic","title":"hashValue","url":"\/documentation\/human\/hsbotdefenderchallengeresult\/hashvalue"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","url":"\/documentation\/human\/hsbotdefenderchallengeresult","title":"HSBotDefenderChallengeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","op":"replace","value":"HSBotDefenderChallengeResult"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","op":"replace","value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}