{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult"]]},"metadata":{"symbolKind":"case","modules":[{"name":"HUMAN"}],"title":"HSBotDefenderChallengeResult.solved","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solved"}],"roleHeading":"Case","navigatorTitle":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HSBotDefenderChallengeResult@HSBotDefenderChallengeResultSolved","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/solved"},"variants":[{"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/solved"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefenderchallengeresult\/solved"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solved"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult/solved":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solved"}],"kind":"symbol","navigatorTitle":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"type":"topic","title":"HSBotDefenderChallengeResult.solved","url":"\/documentation\/human\/hsbotdefenderchallengeresult\/solved","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult\/solved"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsbotdefenderchallengeresult","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","title":"HSBotDefenderChallengeResult","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"HSBotDefenderChallengeResultSolved"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"HSBotDefenderChallengeResultSolved"}]}]}},{"value":"HSBotDefenderChallengeResultSolved","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1solved\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult~1solved\/fragments","value":[{"text":"HSBotDefenderChallengeResultSolved","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","value":"HSBotDefenderChallengeResult","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}