{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/hsdetectionpolicy\/allowtouchdetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsdetectionpolicy\/allowtouchdetection"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"allowTouchDetection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"allowTouchDetection","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSDetectionPolicy(py)allowTouchDetection"},"kind":"symbol","abstract":[{"text":"Allow the SDK to intercept touches on the screen. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","url":"\/documentation\/human\/hsdetectionpolicy","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"title":"HSDetectionPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK’s detection.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSDetectionPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/allowTouchDetection":{"type":"topic","url":"\/documentation\/human\/hsdetectionpolicy\/allowtouchdetection","role":"symbol","title":"allowTouchDetection","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection","navigatorTitle":[{"text":"allowTouchDetection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Allow the SDK to intercept touches on the screen. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowTouchDetection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowTouchDetection"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title","value":"HSDetectionPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments","value":[{"kind":"identifier","text":"HSDetectionPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSDetectionPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/title","value":"allowTouchDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/fragments","value":[{"kind":"identifier","text":"allowTouchDetection"}]}]}]}