{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Allow the SDK to collect device motion data."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This property is relevant only for apps that use ","type":"text"},{"code":"CMMotionManager","type":"codeVoice"},{"type":"text","text":". The SDK is creating an instance of "},{"type":"codeVoice","code":"CMMotionManager"},{"text":" to monitor device’s motion. However, it’s not recommended to have more than one instance in the app. By setting this property to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", the SDK won’t create an instance of ","type":"text"},{"code":"CMMotionManager","type":"codeVoice"},{"type":"text","text":". This feature is disabled when "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection","isActive":true,"type":"reference"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":". Default is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/human\/hsdetectionpolicy\/allowdevicemotiondetection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsdetectionpolicy\/allowdevicemotiondetection"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowDeviceMotionDetection"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"]]},"sections":[],"metadata":{"title":"allowDeviceMotionDetection","role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@HUMAN@objc(cs)HSDetectionPolicy(py)allowDeviceMotionDetection","symbolKind":"property"},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/allowTouchDetection":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsdetectionpolicy\/allowtouchdetection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowTouchDetection","title":"allowTouchDetection","abstract":[{"text":"Allow the SDK to intercept touches on the screen. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"allowTouchDetection"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/allowDeviceMotionDetection":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsdetectionpolicy\/allowdevicemotiondetection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/allowDeviceMotionDetection","title":"allowDeviceMotionDetection","abstract":[{"text":"Allow the SDK to collect device motion data.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowDeviceMotionDetection"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"allowDeviceMotionDetection","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK’s detection.","type":"text"}],"navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","url":"\/documentation\/human\/hsdetectionpolicy","role":"symbol","title":"HSDetectionPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"allowDeviceMotionDetection","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"allowTouchDetection","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"allowTouchDetection"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowTouchDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowDeviceMotionDetection\/title","value":"allowDeviceMotionDetection"},{"value":[{"kind":"identifier","text":"allowDeviceMotionDetection"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1allowDeviceMotionDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title","value":"HSDetectionPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments","value":[{"text":"HSDetectionPolicy","kind":"identifier"}]},{"value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle"}]}]}