{"sections":[],"metadata":{"roleHeading":"Instance Method","title":"copy(with:)","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HSDetectionPolicy(im)copyWithZone:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"text":"Any","kind":"keyword"}],"modules":[{"name":"HUMAN"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","kind":"typeIdentifier","text":"NSZone"},{"text":"? = nil) -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/copy(with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"NSCopying.copy(with:)"},{"text":".","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsdetectionpolicy\/copy(with:)"]},{"paths":["\/documentation\/human\/hsdetectionpolicy\/copy(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK’s detection.","type":"text"}],"navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","url":"\/documentation\/human\/hsdetectionpolicy","role":"symbol","title":"HSDetectionPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy/copy(with:)":{"title":"copy(with:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/human\/hsdetectionpolicy\/copy(with:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy\/copy(with:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"copyWithZone:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title","op":"replace","value":"HSDetectionPolicy"},{"value":[{"kind":"identifier","text":"HSDetectionPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle","value":[{"text":"HSDetectionPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy~1copy(with:)\/fragments"}]}]}