{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"interceptorType","kind":"identifier"}],"externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(py)interceptorType","title":"interceptorType","symbolKind":"property","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptorType"},{"kind":"text","text":": "},{"text":"HSAutomaticInterceptorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","text":"HSAutomaticInterceptorType","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"mentions":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration"],"kind":"mentions"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/interceptorType":{"abstract":[],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/interceptortype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/interceptorType","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HSAutomaticInterceptorType","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"interceptorType","kind":"identifier"}],"type":"topic","title":"interceptorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"url":"\/documentation\/human\/native_easiest_implementation","role":"article","abstract":[],"title":"Native - Easiest Implementation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","kind":"article","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Ionic_Integration":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","url":"\/documentation\/human\/ionic_integration","kind":"article","abstract":[],"type":"topic","role":"article","title":"Ionic Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"kind":"symbol","role":"symbol","abstract":[{"text":"The Automatic Interceptor type.","type":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptortype","title":"HSAutomaticInterceptorType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","navigatorTitle":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/gRPC_Integration":{"kind":"article","abstract":[],"url":"\/documentation\/human\/grpc_integration","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","title":"gRPC Integration","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","url":"\/documentation\/human\/hsautomaticinterceptorpolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"type":"topic","role":"symbol","title":"HSAutomaticInterceptorPolicy","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Flutter_Integration":{"role":"article","abstract":[],"kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","url":"\/documentation\/human\/flutter_integration","type":"topic","title":"Flutter Integration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"interceptorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"interceptorType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","text":"HSAutomaticInterceptorType","preciseIdentifier":"c:@M@HUMAN@E@HSAutomaticInterceptorType"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptorType"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"interceptorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1interceptorType\/fragments","value":[{"text":"interceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title","value":"HSAutomaticInterceptorPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]}]}]}