{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"interceptedDomains"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setWithInterceptedDomains:forAppId:","kind":"identifier"}],"title":"set(interceptedDomains:forAppId:)","modules":[{"name":"HUMAN"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(im)setWithInterceptedDomains:forAppId:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"interceptedDomains","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"domains","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"List if your domains."}],"type":"paragraph"}],"name":"domains"},{"content":[{"inlineContent":[{"text":"The AppID of your account.","type":"text"}],"type":"paragraph"}],"name":"appId"}],"kind":"parameters"}],"abstract":[{"text":"Use this function to register domains which your app interact with. The SDK (when the ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/urlRequestInterceptionType","type":"codeVoice"},{"text":" is set to any value rather than ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/none","type":"codeVoice"},{"text":") intercepts URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. If you are using more than one AppID setting the domains is required. For example: “example.com”.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/set(intercepteddomains:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/set(intercepteddomains:forappid:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/set(interceptedDomains:forAppId:)","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/set(interceptedDomains:forAppId:)":{"type":"topic","role":"symbol","title":"set(interceptedDomains:forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/set(interceptedDomains:forAppId:)","abstract":[{"text":"Use this function to register domains which your app interact with. The SDK (when the ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/urlRequestInterceptionType","type":"codeVoice"},{"text":" is set to any value rather than ","type":"text"},{"code":"HSAutomaticInterceptorPolicy\/none","type":"codeVoice"},{"text":") intercepts URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. If you are using more than one AppID setting the domains is required. For example: “example.com”.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"interceptedDomains"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/set(intercepteddomains:forappid:)","navigatorTitle":[{"kind":"identifier","text":"setWithInterceptedDomains:forAppId:"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"kind":"symbol","title":"HUMAN","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"title":"HSAutomaticInterceptorPolicy","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setWithInterceptedDomains:forAppId:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithInterceptedDomains:forAppId:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setWithInterceptedDomains:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"domains"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List if your domains."}]}],"name":"domains"},{"content":[{"inlineContent":[{"type":"text","text":"The AppID of your account."}],"type":"paragraph"}],"name":"appId"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1set(interceptedDomains:forAppId:)\/title","value":"setWithInterceptedDomains:forAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1set(interceptedDomains:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setWithInterceptedDomains:forAppId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title","value":"HSAutomaticInterceptorPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]}]}]}