{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlSessionRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(cpy)urlSessionRequestTimeout","roleHeading":"Type Property","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSessionRequestTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","title":"urlSessionRequestTimeout","navigatorTitle":[{"text":"urlSessionRequestTimeout","kind":"identifier"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionrequesttimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionrequesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeoutInterval"},{"type":"text","text":" that you would like to set for the URLRequest when using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse"},{"text":"  or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","isActive":true},{"type":"text","text":" "},{"type":"text","text":"In those cases you would need to set the timeout of the request to 0 in order to enable the request to return only after the challenge is completed when blocked, without getting a time out error,"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"urlSessionRequestTimeout","type":"codeVoice"},{"type":"text","text":" will allow you to set the required timeout for the actual request, the default will be set to 60 as the default timeout for URLRequest."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptWithDelayedResponse":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","abstract":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","type":"reference","isActive":true},{"text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled.","type":"text"}],"title":"HSAutomaticInterceptorType.interceptWithDelayedResponse","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interceptWithDelayedResponse"}],"navigatorTitle":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse","kind":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionRequestTimeout":{"title":"urlSessionRequestTimeout","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionRequestTimeout","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionrequesttimeout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlSessionRequestTimeout"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"timeoutInterval"},{"text":" that you would like to set for the URLRequest when using ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse"},{"text":"  or ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","type":"reference","isActive":true},{"type":"text","text":" "},{"text":"In those cases you would need to set the timeout of the request to 0 in order to enable the request to return only after the challenge is completed when blocked, without getting a time out error,","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"urlSessionRequestTimeout"},{"text":" will allow you to set the required timeout for the actual request, the default will be set to 60 as the default timeout for URLRequest.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionRequestTimeout"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"role":"symbol","title":"HSAutomaticInterceptorPolicy","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the Automatic Interceptor.","type":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptAndRetryRequest":{"role":"symbol","type":"topic","title":"HSAutomaticInterceptorType.interceptAndRetryRequest","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptAndRetryRequest","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interceptAndRetryRequest"}],"abstract":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","isActive":true},{"type":"text","text":". When the challenge is solved, the SDK will send the original request one more time. Your request’s handler should receive the response from your server without knowing that the request was blocked and sent again. You should note that when the challenge is cancelled or when the second request is also blocked, then the behavior will be the same as the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse"},{"text":". In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled.","type":"text"}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptandretryrequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intercept"}],"url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","title":"HSAutomaticInterceptorType.intercept","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"abstract":[{"text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"type":"topic","kind":"symbol","title":"HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"urlSessionRequestTimeout"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"urlSessionRequestTimeout","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionRequestTimeout"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/title"},{"value":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/fragments"},{"op":"replace","value":"urlSessionRequestTimeout","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/title"},{"op":"replace","value":[{"kind":"identifier","text":"urlSessionRequestTimeout"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionRequestTimeout\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title","op":"replace","value":"HSAutomaticInterceptorPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},{"value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle"},{"value":"HSAutomaticInterceptorTypeInterceptAndRetryRequest","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/title"},{"value":[{"text":"HSAutomaticInterceptorTypeInterceptAndRetryRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptAndRetryRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","value":"HSAutomaticInterceptorTypeIntercept"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","value":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}],"op":"replace"}]}]}