{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"metadata":{"roleHeading":"Type Property","externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(cpy)urlSessionConfiguration","symbolKind":"property","title":"urlSessionConfiguration","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration"}],"navigatorTitle":[{"text":"urlSessionConfiguration","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","interfaceLanguage":"swift"},"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URLSessionConfiguration"},{"type":"text","text":" that should be used by the SDK. Default is "},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"urlSessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionConfiguration":{"url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionconfiguration","type":"topic","navigatorTitle":[{"text":"urlSessionConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionConfiguration","abstract":[{"type":"text","text":"The "},{"code":"URLSessionConfiguration","type":"codeVoice"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSessionConfiguration"},{"kind":"text","text":": "},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"}],"title":"urlSessionConfiguration","kind":"symbol","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","title":"HSAutomaticInterceptorPolicy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"urlSessionConfiguration","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"urlSessionConfiguration","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"NSURLSessionConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"urlSessionConfiguration"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"urlSessionConfiguration","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"urlSessionConfiguration"}]},{"op":"replace","value":"HSAutomaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"op":"replace"}]}]}