{"abstract":[{"text":"The ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" (the SDK will be the delegate). The SDK implements ","type":"text"},{"code":"willPerformHTTPRedirection","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"needNewBodyStream","type":"codeVoice"},{"text":" function in the ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":". However, if your ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":" implements other functions, like ","type":"text"},{"code":"didReceiveChallenge","type":"codeVoice"},{"text":", then you should provide your own delegate.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSURLSessionDelegate","text":"URLSessionDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(cpy)urlSessionDelegate","role":"symbol","title":"urlSessionDelegate","navigatorTitle":[{"kind":"identifier","text":"urlSessionDelegate"}],"roleHeading":"Type Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionDelegate":{"kind":"symbol","title":"urlSessionDelegate","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessiondelegate","navigatorTitle":[{"kind":"identifier","text":"urlSessionDelegate"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSessionDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate","text":"URLSessionDelegate"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionDelegate","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionDelegate"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" (the SDK will be the delegate). The SDK implements ","type":"text"},{"code":"willPerformHTTPRedirection","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"needNewBodyStream","type":"codeVoice"},{"type":"text","text":" function in the "},{"code":"URLSessionDelegate","type":"codeVoice"},{"text":". However, if your ","type":"text"},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":" implements other functions, like "},{"type":"codeVoice","code":"didReceiveChallenge"},{"type":"text","text":", then you should provide your own delegate."}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"kind":"symbol","title":"HSAutomaticInterceptorPolicy","url":"\/documentation\/human\/hsautomaticinterceptorpolicy","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"urlSessionDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"urlSessionDelegate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSURLSessionDelegate","text":"id<NSURLSessionDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionDelegate\/title","op":"replace","value":"urlSessionDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"urlSessionDelegate"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title","op":"replace","value":"HSAutomaticInterceptorPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}