{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionQueueDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy"]]},"abstract":[{"text":"The ","type":"text"},{"code":"OperationQueue","type":"codeVoice"},{"text":" that should be used by the SDK.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionQueueDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@objc(cs)HSAutomaticInterceptorPolicy(cpy)urlSessionQueueDelegate","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionQueueDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OperationQueue","preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"urlSessionQueueDelegate","navigatorTitle":[{"text":"urlSessionQueueDelegate","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionqueuedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionqueuedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","title":"HUMAN","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"url":"\/documentation\/human","kind":"symbol","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/human\/hsautomaticinterceptorpolicy","title":"HSAutomaticInterceptorPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy/urlSessionQueueDelegate":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy\/urlSessionQueueDelegate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionQueueDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OperationQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"OperationQueue"},{"type":"text","text":" that should be used by the SDK."}],"navigatorTitle":[{"text":"urlSessionQueueDelegate","kind":"identifier"}],"title":"urlSessionQueueDelegate","url":"\/documentation\/human\/hsautomaticinterceptorpolicy\/urlsessionqueuedelegate","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"urlSessionQueueDelegate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"urlSessionQueueDelegate"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"NSOperationQueue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"urlSessionQueueDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HSAutomaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle"},{"op":"replace","value":"urlSessionQueueDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionQueueDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"urlSessionQueueDelegate"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy~1urlSessionQueueDelegate\/fragments"}]}]}