{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"challengeCancelled"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/humanerrorcode\/challengecancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode\/challengecancelled"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Challenge was cancelled."}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeCancelled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"HumanErrorCode.challengeCancelled","roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"HumanErrorCodeChallengeCancelled","kind":"identifier"}],"modules":[{"name":"HUMAN"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"challengeCancelled","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeChallengeCancelled"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/challengeCancelled":{"title":"HumanErrorCode.challengeCancelled","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/challengeCancelled","role":"symbol","url":"\/documentation\/human\/humanerrorcode\/challengecancelled","kind":"symbol","type":"topic","navigatorTitle":[{"text":"HumanErrorCodeChallengeCancelled","kind":"identifier"}],"abstract":[{"type":"text","text":"Challenge was cancelled."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"challengeCancelled","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"HumanErrorCodeChallengeCancelled","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HumanErrorCodeChallengeCancelled"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"HumanErrorCodeChallengeCancelled","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title","value":"HumanErrorCode"},{"value":[{"text":"HumanErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeCancelled\/title","value":"HumanErrorCodeChallengeCancelled","op":"replace"},{"value":[{"text":"HumanErrorCodeChallengeCancelled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1challengeCancelled\/fragments"}]}]}