{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanerrorcode\/httpbodyinputstreamreadfailed"]},{"paths":["\/documentation\/human\/humanerrorcode\/httpbodyinputstreamreadfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Failed to read body from input stream of the request."}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/httpBodyInputStreamReadFailed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"HumanErrorCode.httpBodyInputStreamReadFailed","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeHttpBodyInputStreamReadFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"HUMAN"}]},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/httpBodyInputStreamReadFailed":{"title":"HumanErrorCode.httpBodyInputStreamReadFailed","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/httpBodyInputStreamReadFailed","abstract":[{"type":"text","text":"Failed to read body from input stream of the request."}],"url":"\/documentation\/human\/humanerrorcode\/httpbodyinputstreamreadfailed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"HumanErrorCodeHttpBodyInputStreamReadFailed","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title","value":"HumanErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments","value":[{"text":"HumanErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1httpBodyInputStreamReadFailed\/title","value":"HumanErrorCodeHttpBodyInputStreamReadFailed"},{"value":[{"kind":"identifier","text":"HumanErrorCodeHttpBodyInputStreamReadFailed"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1httpBodyInputStreamReadFailed\/fragments","op":"replace"}]}]}