{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/missingAppId"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"variants":[{"paths":["\/documentation\/human\/humanerrorcode\/missingappid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode\/missingappid"]}],"abstract":[{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","type":"reference"},{"type":"text","text":" or "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","isActive":true,"type":"reference"},{"text":" functions were called without any AppID.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"missingAppId","kind":"identifier"}],"externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeMissingAppId","roleHeading":"Case","title":"HumanErrorCode.missingAppId","modules":[{"name":"HUMAN"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"HumanErrorCodeMissingAppId","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"missingAppId","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:delegate:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"start(appId:delegate:policy:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:delegate:policy:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appIds:delegate:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/missingAppId":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"missingAppId","kind":"identifier"}],"title":"HumanErrorCode.missingAppId","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/missingAppId","abstract":[{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","type":"reference"},{"type":"text","text":" or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)"},{"type":"text","text":" functions were called without any AppID."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeMissingAppId"}],"url":"\/documentation\/human\/humanerrorcode\/missingappid"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"HumanErrorCodeMissingAppId","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"HumanErrorCodeMissingAppId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"HumanErrorCodeMissingAppId","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"startWithAppId:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/fragments"},{"value":"startWithAppIds:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/fragments"},{"value":"HumanErrorCodeMissingAppId","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1missingAppId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1missingAppId\/fragments","value":[{"text":"HumanErrorCodeMissingAppId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title","value":"HumanErrorCode"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments","value":[{"kind":"identifier","text":"HumanErrorCode"}],"op":"replace"}]}]}