{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/human\/humanerrorcode\/requestwasblocked"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode\/requestwasblocked"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/requestWasBlocked","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestWasBlocked"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"HumanErrorCode.requestWasBlocked","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeRequestWasBlocked"}],"symbolKind":"case","externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeRequestWasBlocked","modules":[{"name":"HUMAN"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requestWasBlocked","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"abstract":[{"text":"URL request was blocked by Human.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/requestWasBlocked":{"navigatorTitle":[{"text":"HumanErrorCodeRequestWasBlocked","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestWasBlocked"}],"title":"HumanErrorCode.requestWasBlocked","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/requestWasBlocked","abstract":[{"text":"URL request was blocked by Human.","type":"text"}],"type":"topic","url":"\/documentation\/human\/humanerrorcode\/requestwasblocked","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"HumanErrorCodeRequestWasBlocked","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"HumanErrorCodeRequestWasBlocked","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"HumanErrorCodeRequestWasBlocked","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title","op":"replace","value":"HumanErrorCode"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments","value":[{"text":"HumanErrorCode","kind":"identifier"}],"op":"replace"},{"value":"HumanErrorCodeRequestWasBlocked","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1requestWasBlocked\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1requestWasBlocked\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeRequestWasBlocked"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}