{"abstract":[{"type":"text","text":"The SDK failed to perform the operation. Make sure to call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","isActive":true,"type":"reference"},{"text":" function.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/humanerrorcode\/startwasnotcalled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode\/startwasnotcalled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startWasNotCalled","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeStartWasNotCalled","symbolKind":"case","role":"symbol","modules":[{"name":"HUMAN"}],"roleHeading":"Case","title":"HumanErrorCode.startWasNotCalled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startWasNotCalled","kind":"identifier"}],"navigatorTitle":[{"text":"HumanErrorCodeStartWasNotCalled","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startWasNotCalled"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/startWasNotCalled":{"navigatorTitle":[{"text":"HumanErrorCodeStartWasNotCalled","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The SDK failed to perform the operation. Make sure to call the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)"},{"text":" function.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startWasNotCalled","url":"\/documentation\/human\/humanerrorcode\/startwasnotcalled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startWasNotCalled","kind":"identifier"}],"title":"HumanErrorCode.startWasNotCalled","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:delegate:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"start(appId:delegate:policy:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"HumanErrorCodeStartWasNotCalled","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HumanErrorCodeStartWasNotCalled"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HumanErrorCodeStartWasNotCalled"}]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startWasNotCalled\/title","value":"HumanErrorCodeStartWasNotCalled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startWasNotCalled\/fragments","value":[{"text":"HumanErrorCodeStartWasNotCalled","kind":"identifier"}]},{"op":"replace","value":"startWithAppId:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}]},{"op":"replace","value":"HumanErrorCode","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HumanErrorCode"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments"}]}]}