{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startCalledMoreThanOnce"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCalledMoreThanOnce","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/human\/humanerrorcode\/startcalledmorethanonce"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/humanerrorcode\/startcalledmorethanonce"]}],"metadata":{"role":"symbol","modules":[{"name":"HUMAN"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startCalledMoreThanOnce","kind":"identifier"}],"title":"HumanErrorCode.startCalledMoreThanOnce","externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeStartCalledMoreThanOnce","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)"},{"text":" or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","type":"reference"},{"type":"text","text":" functions were called more than once."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appId:delegate:policy:)":{"url":"\/documentation\/human\/humansecurity\/start(appid:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","title":"start(appId:delegate:policy:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/startCalledMoreThanOnce":{"navigatorTitle":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"kind":"symbol","abstract":[{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appId:delegate:policy:)","type":"reference"},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","isActive":true},{"type":"text","text":" functions were called more than once."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/startCalledMoreThanOnce","url":"\/documentation\/human\/humanerrorcode\/startcalledmorethanonce","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startCalledMoreThanOnce","kind":"identifier"}],"title":"HumanErrorCode.startCalledMoreThanOnce","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity/start(appIds:delegate:policy:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(pl)HumanDelegate","text":"HumanDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@HUMAN@objc(cs)HSPolicy","text":"HSPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity\/start(appIds:delegate:policy:)","kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appIds:delegate:policy:)","url":"\/documentation\/human\/humansecurity\/start(appids:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"HumanErrorCodeStartCalledMoreThanOnce"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"startWithAppId:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appId:delegate:policy:)\/fragments","op":"replace"},{"value":"HumanErrorCodeStartCalledMoreThanOnce","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startCalledMoreThanOnce\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1startCalledMoreThanOnce\/fragments","value":[{"text":"HumanErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/title","value":"startWithAppIds:delegate:policy:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity~1start(appIds:delegate:policy:)\/fragments"},{"op":"replace","value":"HumanErrorCode","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title"},{"op":"replace","value":[{"text":"HumanErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments"}]}]}