{"metadata":{"roleHeading":"Case","modules":[{"name":"HUMAN"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenWasNotGenerated"}],"title":"HumanErrorCode.tokenWasNotGenerated","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCodeTokenWasNotGenerated"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@HUMAN@E@HumanErrorCode@HumanErrorCodeTokenWasNotGenerated"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tokenWasNotGenerated","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/human\/humanerrorcode\/tokenwasnotgenerated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/humanerrorcode\/tokenwasnotgenerated"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/tokenWasNotGenerated"},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode":{"title":"HumanErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"url":"\/documentation\/human\/humanerrorcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HumanErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanErrorCode/tokenWasNotGenerated":{"url":"\/documentation\/human\/humanerrorcode\/tokenwasnotgenerated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenWasNotGenerated"}],"abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"type":"topic","title":"HumanErrorCode.tokenWasNotGenerated","kind":"symbol","navigatorTitle":[{"text":"HumanErrorCodeTokenWasNotGenerated","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanErrorCode\/tokenWasNotGenerated","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HumanErrorCodeTokenWasNotGenerated"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeTokenWasNotGenerated"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"HumanErrorCodeTokenWasNotGenerated"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/title","value":"HumanErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode\/fragments","value":[{"kind":"identifier","text":"HumanErrorCode"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1tokenWasNotGenerated\/title","op":"replace","value":"HumanErrorCodeTokenWasNotGenerated"},{"op":"replace","value":[{"kind":"identifier","text":"HumanErrorCodeTokenWasNotGenerated"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanErrorCode~1tokenWasNotGenerated\/fragments"}]}]}