{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefendererrortype\/challengewassolved"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefendererrortype\/challengewassolved"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"]]},"metadata":{"role":"symbol","externalID":"c:@M@HUMAN@E@HSBotDefenderErrorType@HSBotDefenderErrorTypeChallengeWasSolved","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorTypeChallengeWasSolved"}],"title":"HSBotDefenderErrorType.challengeWasSolved","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeWasSolved","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"HUMAN"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasSolved"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeWasSolved"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"url":"\/documentation\/human","role":"collection","kind":"symbol","title":"HUMAN","type":"topic","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/challengeWasSolved":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HSBotDefenderErrorTypeChallengeWasSolved","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeWasSolved","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasSolved","abstract":[],"type":"topic","url":"\/documentation\/human\/hsbotdefendererrortype\/challengewassolved","title":"HSBotDefenderErrorType.challengeWasSolved"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"url":"\/documentation\/human\/hsbotdefendererrortype","type":"topic","navigatorTitle":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"abstract":[],"title":"HSBotDefenderErrorType","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HSBotDefenderErrorTypeChallengeWasSolved","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HSBotDefenderErrorTypeChallengeWasSolved"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"HSBotDefenderErrorTypeChallengeWasSolved"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HSBotDefenderErrorTypeChallengeWasSolved","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasSolved\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasSolved\/fragments","value":[{"text":"HSBotDefenderErrorTypeChallengeWasSolved","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","value":"HSBotDefenderErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"op":"replace"}]}]}