{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"challengeWasCancelled"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}],"title":"HSBotDefenderErrorType.challengeWasCancelled","role":"symbol","symbolKind":"case","externalID":"c:@M@HUMAN@E@HSBotDefenderErrorType@HSBotDefenderErrorTypeChallengeWasCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"challengeWasCancelled","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"HUMAN"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasCancelled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/human\/hsbotdefendererrortype\/challengewascancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefendererrortype\/challengewascancelled"]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"type":"topic","kind":"symbol","title":"HUMAN","url":"\/documentation\/human","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/challengeWasCancelled":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/challengeWasCancelled","kind":"symbol","navigatorTitle":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefendererrortype\/challengewascancelled","role":"symbol","abstract":[],"title":"HSBotDefenderErrorType.challengeWasCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"challengeWasCancelled","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"role":"symbol","title":"HSBotDefenderErrorType","url":"\/documentation\/human\/hsbotdefendererrortype","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderErrorType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"HSBotDefenderErrorTypeChallengeWasCancelled","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HSBotDefenderErrorTypeChallengeWasCancelled"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}]}]}},{"value":"HSBotDefenderErrorTypeChallengeWasCancelled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasCancelled\/title"},{"value":[{"text":"HSBotDefenderErrorTypeChallengeWasCancelled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1challengeWasCancelled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","value":"HSBotDefenderErrorType"},{"op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments"},{"op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}