{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","metadata":{"modules":[{"name":"HUMAN"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"]]},"variants":[{"paths":["\/documentation\/human\/hsbotdefendererrortype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/Equatable-Implementations"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/!=(_:_:)":{"url":"\/documentation\/human\/hsbotdefendererrortype\/!=(_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"!=(_:_:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/!=(_:_:)","role":"symbol","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSBotDefenderErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"url":"\/documentation\/human\/hsbotdefendererrortype","kind":"symbol","abstract":[],"title":"HSBotDefenderErrorType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","value":"HSBotDefenderErrorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}]},{"value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle"}]}]}