{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/requestWasBlocked","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorTypeRequestWasBlocked"}],"role":"symbol","externalID":"c:@M@HUMAN@E@HSBotDefenderErrorType@HSBotDefenderErrorTypeRequestWasBlocked","modules":[{"name":"HUMAN"}],"roleHeading":"Case","title":"HSBotDefenderErrorType.requestWasBlocked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestWasBlocked"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestWasBlocked","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsbotdefendererrortype\/requestwasblocked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsbotdefendererrortype\/requestwasblocked"]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType/requestWasBlocked":{"role":"symbol","type":"topic","title":"HSBotDefenderErrorType.requestWasBlocked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestWasBlocked"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorTypeRequestWasBlocked"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType\/requestWasBlocked","url":"\/documentation\/human\/hsbotdefendererrortype\/requestwasblocked"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","title":"HSBotDefenderErrorType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBotDefenderErrorType"}],"url":"\/documentation\/human\/hsbotdefendererrortype"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HSBotDefenderErrorTypeRequestWasBlocked","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HSBotDefenderErrorTypeRequestWasBlocked","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HSBotDefenderErrorTypeRequestWasBlocked","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1requestWasBlocked\/title","op":"replace","value":"HSBotDefenderErrorTypeRequestWasBlocked"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType~1requestWasBlocked\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorTypeRequestWasBlocked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","op":"replace","value":"HSBotDefenderErrorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","op":"replace","value":[{"text":"HSBotDefenderErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}