{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"metadata":{"modules":[{"name":"HUMAN"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/Equatable-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype\/equatable-implementations"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"type":"topic","title":"!=(_:_:)","url":"\/documentation\/human\/hsautomaticinterceptortype\/!=(_:_:)","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/!=(_:_:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"url":"\/documentation\/human\/hsautomaticinterceptortype","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","title":"HSAutomaticInterceptorType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"HSAutomaticInterceptorType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title"},{"op":"replace","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}