{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype\/hashvalue"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/hashValue"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","extendedModule":"Swift","role":"symbol","title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"HUMAN"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@HUMAN@E@HSAutomaticInterceptorType","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/hashValue":{"url":"\/documentation\/human\/hsautomaticinterceptortype\/hashvalue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/hashValue","kind":"symbol","abstract":[],"role":"symbol","type":"topic","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"title":"hashValue"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"url":"\/documentation\/human\/hsautomaticinterceptortype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"navigatorTitle":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"title":"HSAutomaticInterceptorType","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","abstract":[{"text":"The Automatic Interceptor type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","kind":"symbol","role":"collection","url":"\/documentation\/human","type":"topic","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"title":"HUMAN"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","op":"replace","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]}]}]}