{"abstract":[{"text":"Same as ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","type":"reference"},{"text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"modules":[{"name":"HUMAN"}],"externalID":"c:@M@HUMAN@E@HSAutomaticInterceptorType@HSAutomaticInterceptorTypeInterceptWithDelayedResponse","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"title":"HSAutomaticInterceptorType.interceptWithDelayedResponse"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/interceptWithDelayedResponse":{"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/interceptWithDelayedResponse","title":"HSAutomaticInterceptorType.interceptWithDelayedResponse","abstract":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept"},{"type":"text","text":". The SDK delays the error response to your app until the user solve or cancel the challenge. In order to delay the request’s response to your handler until the user interacts with the challenge, you must disable the request’s timeout. Otherwise, your handler will receive a timeout error and you might not know that your request was blocked nor the challenge was solved\/cancelled."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/interceptwithdelayedresponse"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","title":"HUMAN","role":"collection","url":"\/documentation\/human","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"url":"\/documentation\/human\/hsautomaticinterceptortype","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"type":"topic","role":"symbol","kind":"symbol","title":"HSAutomaticInterceptorType","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","title":"HSAutomaticInterceptorType.intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/title","value":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1interceptWithDelayedResponse\/fragments","value":[{"text":"HSAutomaticInterceptorTypeInterceptWithDelayedResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title","value":"HSAutomaticInterceptorTypeIntercept","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments","value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"op":"replace"}]}]}