{"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"title":"HSAutomaticInterceptorType.intercept","externalID":"c:@M@HUMAN@E@HSAutomaticInterceptorType@HSAutomaticInterceptorTypeIntercept","modules":[{"name":"HUMAN"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"text":"URLSession.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"WKWebView."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any 3rd party library which based on URLSession (like Alamofire)."},{"type":"text","text":" "},{"type":"text","text":"Notice that the SDK cannot intercept requests from SFSafariViewController."}]}]}],"type":"orderedList"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype\/intercept"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human\/hsautomaticinterceptortype\/intercept"]}],"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","abstract":[{"type":"text","text":"The Automatic Interceptor type."}],"navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"url":"\/documentation\/human\/hsautomaticinterceptortype","title":"HSAutomaticInterceptorType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType/intercept":{"role":"symbol","type":"topic","url":"\/documentation\/human\/hsautomaticinterceptortype\/intercept","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType\/intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}],"title":"HSAutomaticInterceptorType.intercept","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","abstract":[{"identifier":"HUMAN_logo.png","type":"image"}],"title":"HUMAN","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/human"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HSAutomaticInterceptorTypeIntercept","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HSAutomaticInterceptorTypeIntercept","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HSAutomaticInterceptorType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"},{"value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle"},{"value":"HSAutomaticInterceptorTypeIntercept","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/title"},{"value":[{"kind":"identifier","text":"HSAutomaticInterceptorTypeIntercept"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType~1intercept\/fragments"}]}]}