{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/human"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/human"]}],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"HUMAN is a cybersecurity company that protects organizations by disrupting digital fraud and abuse. We leverage modern defense to disrupt the economics of cybercrime by increasing the cost to cybercriminals while simultaneously reducing the cost of collective defense. Today we verify the humanity of more than 20 trillion digital interactions per week across advertising, marketing, e-commerce, government, education and enterprise security, putting us in a position to win against cybercriminals. HUMAN was named one of the ","type":"text"},{"identifier":"https:\/\/time.com\/collection\/time100-companies-2023\/6285152\/human-security\/","isActive":true,"type":"reference"},{"text":". Protect your digital business with HUMAN. To Know Who’s Real, visit ","type":"text"},{"isActive":true,"identifier":"https:\/\/www.humansecurity.com","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"],"generated":true,"anchor":"Articles","title":"Articles"},{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"],"anchor":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"],"title":"Protocols","anchor":"Protocols"},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorDomain","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorDomain"]},{"anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"],"title":"Enumerations"}],"metadata":{"role":"collection","modules":[{"name":"HUMAN"}],"roleHeading":"Framework","title":"HUMAN","externalID":"HUMAN","symbolKind":"module"},"sections":[],"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Integration_Guide":{"role":"article","kind":"article","url":"\/documentation\/human\/integration_guide","title":"Integration Guide","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDoctorAppPolicy":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSDoctorAppPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the Doctor App.","type":"text"}],"navigatorTitle":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","url":"\/documentation\/human\/hsdoctorapppolicy","role":"symbol","title":"HSDoctorAppPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorDomain":{"role":"symbol","kind":"symbol","url":"\/documentation\/human\/humansecurityerrordomain","title":"HumanSecurityErrorDomain","abstract":[{"text":"Human’s error domain. This will be included in errors objects that generated in the SDK. List of error codes is defined in ","type":"text"},{"type":"codeVoice","code":"HumanSecurityErrorCode"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorDomain","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HumanSecurityErrorDomain"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurityErrorType":{"title":"HumanSecurityErrorType","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"HumanSecurityErrorType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/human\/humansecurityerrortype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HumanSecurityErrorType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HumanSecurity":{"abstract":[{"text":"Human Security main class. You should interact with it in order to setup and start the SDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity","url":"\/documentation\/human\/humansecurity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HumanSecurity"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HumanSecurity"}],"title":"HumanSecurity"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_upgrade_from_v3":{"type":"topic","abstract":[{"type":"text","text":"There are few major changes in the SDK’s API. In this article we will cover all of them."}],"kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","url":"\/documentation\/human\/how_to_upgrade_from_v3","role":"article","title":"How to upgrade from v3"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_window":{"abstract":[],"kind":"article","url":"\/documentation\/human\/visionos_integration_window","role":"article","title":"visionOS Integration (window)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Flutter_Integration":{"type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","url":"\/documentation\/human\/flutter_integration","role":"article","title":"Flutter Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAccountDefender":{"abstract":[],"kind":"symbol","url":"\/documentation\/human\/hsaccountdefender","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSAccountDefender"}],"title":"HSAccountDefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","navigatorTitle":[{"text":"HSAccountDefender","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSDetectionPolicy":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSDetectionPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK’s detection.","type":"text"}],"navigatorTitle":[{"text":"HSDetectionPolicy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","url":"\/documentation\/human\/hsdetectionpolicy","role":"symbol","title":"HSDetectionPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HUMANVersionString":{"abstract":[{"text":"Project version string for HUMAN.","type":"text"}],"kind":"symbol","url":"\/documentation\/human\/humanversionstring","role":"symbol","fragments":[{"text":"HUMANVersionString","kind":"identifier"}],"title":"HUMANVersionString","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HUMANVersionString","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSError":{"navigatorTitle":[{"text":"HSError","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/human\/hserror","title":"HSError","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSError","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Hybrid_App_Integration":{"url":"\/documentation\/human\/hybrid_app_integration","abstract":[],"title":"Hybrid App Integration","kind":"article","role":"article","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_Verify_the_SDK_Integration_in_Your_App":{"abstract":[],"kind":"article","url":"\/documentation\/human\/how_to_verify_the_sdk_integration_in_your_app","role":"article","title":"How to Verify the SDK Integration in Your App","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefender":{"title":"HSBotDefender","abstract":[],"navigatorTitle":[{"text":"HSBotDefender","kind":"identifier"}],"url":"\/documentation\/human\/hsbotdefender","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefender","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN":{"kind":"symbol","role":"collection","title":"HUMAN","url":"\/documentation\/human","abstract":[{"type":"image","identifier":"HUMAN_logo.png"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Ionic_Integration":{"role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","abstract":[],"title":"Ionic Integration","type":"topic","url":"\/documentation\/human\/ionic_integration","kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/React_Native_Integration":{"abstract":[],"kind":"article","type":"topic","url":"\/documentation\/human\/react_native_integration","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","title":"React Native Integration"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Basic_Implementation":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","title":"Native - Basic Implementation","url":"\/documentation\/human\/native_basic_implementation","role":"article","kind":"article","type":"topic","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HUMANVersionNumber":{"fragments":[{"text":"HUMANVersionNumber","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/humanversionnumber","abstract":[{"text":"Project version number for HUMAN.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HUMANVersionNumber","title":"HUMANVersionNumber","role":"symbol","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/How_to_Test-the_SDK-in_Your_App":{"title":"How to Test the SDK in Your App","kind":"article","role":"article","url":"\/documentation\/human\/how_to_test-the_sdk-in_your_app","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App","abstract":[{"text":"Testing the SDK integration in your app is essential to ensure the best experience for your users.","type":"text"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorDomain":{"title":"HSBotDefenderErrorDomain","url":"\/documentation\/human\/hsbotdefendererrordomain","type":"topic","abstract":[{"text":"Bot Defender’s error domain. This will be included in errors objects that generated in the SDK. List of error codes is defined in ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"HSBotDefenderErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorDomain"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderChallengeResult":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HSBotDefenderChallengeResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hsbotdefenderchallengeresult","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","title":"HSBotDefenderChallengeResult","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorType":{"kind":"symbol","abstract":[{"text":"The Automatic Interceptor type.","type":"text"}],"title":"HSAutomaticInterceptorType","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"url":"\/documentation\/human\/hsautomaticinterceptortype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","navigatorTitle":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}]},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderErrorType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSBotDefenderErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"url":"\/documentation\/human\/hsbotdefendererrortype","kind":"symbol","abstract":[],"title":"HSBotDefenderErrorType","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSHybridAppPolicy":{"abstract":[{"type":"text","text":"The policy that define the behaviour of the Hybrid App support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HSHybridAppPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"HSHybridAppPolicy"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","kind":"symbol","title":"HSHybridAppPolicy","url":"\/documentation\/human\/hshybridapppolicy","role":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSBotDefenderDelegate":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HSBotDefenderDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"HSBotDefenderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate","type":"topic","title":"HSBotDefenderDelegate","url":"\/documentation\/human\/hsbotdefenderdelegate"},"HUMAN_logo.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.perimeterx.mobile-sdk\/HUMAN_logo.png"}],"alt":"HUMAN","identifier":"HUMAN_logo.png"},"https://time.com/collection/time100-companies-2023/6285152/human-security/":{"identifier":"https:\/\/time.com\/collection\/time100-companies-2023\/6285152\/human-security\/","titleInlineContent":[{"text":"TIME100 Most Influential Companies of 2023","type":"text"}],"title":"TIME100 Most Influential Companies of 2023","type":"link","url":"https:\/\/time.com\/collection\/time100-companies-2023\/6285152\/human-security\/"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Easiest_Implementation":{"abstract":[],"kind":"article","type":"topic","url":"\/documentation\/human\/native_easiest_implementation","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","title":"Native - Easiest Implementation"},"https://www.humansecurity.com":{"identifier":"https:\/\/www.humansecurity.com","titleInlineContent":[{"text":"www.humansecurity.com","type":"text"}],"title":"www.humansecurity.com","type":"link","url":"https:\/\/www.humansecurity.com"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/Native_Advanced_Functionality":{"url":"\/documentation\/human\/native_advanced_functionality","kind":"article","title":"Native - Advanced Functionality","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","abstract":[],"role":"article","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/visionOS_Integration_sheet":{"type":"topic","url":"\/documentation\/human\/visionos_integration_sheet","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","kind":"article","abstract":[],"role":"article","title":"visionOS Integration (sheet)"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSPolicy":{"role":"symbol","navigatorTitle":[{"text":"HSPolicy","kind":"identifier"}],"abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"HSPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HSPolicy","kind":"identifier"}],"type":"topic","url":"\/documentation\/human\/hspolicy","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/gRPC_Integration":{"title":"gRPC Integration","url":"\/documentation\/human\/grpc_integration","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","kind":"article","abstract":[],"role":"article","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/HUMAN/HSAutomaticInterceptorPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","type":"topic","abstract":[{"type":"text","text":"The policy that define the behaviour of the Automatic Interceptor."}],"title":"HSAutomaticInterceptorPolicy","kind":"symbol","navigatorTitle":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"url":"\/documentation\/human\/hsautomaticinterceptorpolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Flutter_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Test-the_SDK-in_Your_App","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_Verify_the_SDK_Integration_in_Your_App","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/How_to_upgrade_from_v3","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Hybrid_App_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Integration_Guide","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Ionic_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Advanced_Functionality","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Basic_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/Native_Easiest_Implementation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/React_Native_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/gRPC_Integration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_sheet","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/visionOS_Integration_window"],"generated":true,"title":"Articles","anchor":"Articles"},{"title":"Classes","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAccountDefender","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefender","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDetectionPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSDoctorAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSHybridAppPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurity"],"generated":true,"anchor":"Classes"},{"title":"Protocols","anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderDelegate"]},{"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HUMANVersionNumber","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HUMANVersionString"],"generated":true},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSAutomaticInterceptorType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderChallengeResult","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HSBotDefenderErrorType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/HUMAN\/HumanSecurityErrorType"],"anchor":"Enumerations","title":"Enumerations","generated":true}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"HSDoctorAppPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/title","op":"replace"},{"value":[{"text":"HSDoctorAppPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDoctorAppPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSDoctorAppPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/title","value":"HumanSecurityErrorType"},{"value":[{"kind":"identifier","text":"HumanSecurityErrorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HumanSecurityErrorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurityErrorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/title","value":"HumanSecurity","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/fragments","value":[{"kind":"identifier","text":"HumanSecurity"}],"op":"replace"},{"op":"replace","value":[{"text":"HumanSecurity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HumanSecurity\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/title","value":"HSAccountDefender"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/fragments","value":[{"kind":"identifier","text":"HSAccountDefender"}],"op":"replace"},{"op":"replace","value":[{"text":"HSAccountDefender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAccountDefender\/navigatorTitle"},{"op":"replace","value":"HSDetectionPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/title"},{"value":[{"text":"HSDetectionPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSDetectionPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSDetectionPolicy","kind":"identifier"}]},{"op":"replace","value":"HSError","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/title"},{"value":[{"kind":"identifier","text":"HSError"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSError\/navigatorTitle","op":"replace","value":[{"text":"HSError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/title","op":"replace","value":"HSBotDefender"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/fragments","value":[{"kind":"identifier","text":"HSBotDefender"}]},{"op":"replace","value":[{"text":"HSBotDefender","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefender\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/title","op":"replace","value":"HSBotDefenderChallengeResult"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"HSBotDefenderChallengeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderChallengeResult\/navigatorTitle","value":[{"text":"HSBotDefenderChallengeResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/title","value":"HSAutomaticInterceptorType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HSAutomaticInterceptorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorType\/navigatorTitle","op":"replace","value":[{"text":"HSAutomaticInterceptorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/title","value":"HSBotDefenderErrorType","op":"replace"},{"value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"HSBotDefenderErrorType"}],"op":"replace"},{"value":"HSHybridAppPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/fragments","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSHybridAppPolicy\/navigatorTitle","op":"replace","value":[{"text":"HSHybridAppPolicy","kind":"identifier"}]},{"value":"HSBotDefenderDelegate","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/fragments","value":[{"kind":"identifier","text":"HSBotDefenderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSBotDefenderDelegate\/navigatorTitle","value":[{"text":"HSBotDefenderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/title","value":"HSPolicy","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/fragments","op":"replace","value":[{"text":"HSPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSPolicy"}],"op":"replace"},{"op":"replace","value":"HSAutomaticInterceptorPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/fragments","value":[{"text":"HSAutomaticInterceptorPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1HUMAN~1HSAutomaticInterceptorPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"HSAutomaticInterceptorPolicy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}